### ISSUE TITLE
CodeChecker store fails (sqlite)

### ISSUE THREAD

**Issue by pspe** [Ericsson/codechecker#1005]
Git tag information    : 6.0.1-8-ga3d8f81   
I am using sqlite. My system: Ubuntu 17.04

I ran the command:
`CodeChecker check -b "make clean;make" -o "/home/peters/codechecker_results"`
which worked fine. At least some .plist files two .json and one .json.lock file have been created in the directory ~/codechecker_results

Then I tried:
`CodeChecker store /home/peters/codechecker_results/ -n test`
which failed with the following error message:
`[13:25] - Storing analysis results for run 'test'`
`[13:25] - Storage failed: 'unicode' does not have the buffer interface`

I executed the store-command with the verbose debug option turned on, which then returns the following log messages:
[store.log](https://github.com/Ericsson/codechecker/files/1362532/store.log)

**Comment by whisperity** [comment]
Could you please, at first glance, execute `CodeChecker parse ~/codechecker_results`? There is something amiss in communicating with the server.

What does the server say? Could you please start the server with `--verbose debug` turned on in the server console too, and provide the output of the server too?

**Comment by pspe** [comment]
here is the log of the parse command:
[parse.log](https://github.com/Ericsson/codechecker/files/1362613/parse.log)

and the verbose output of the startup of the server:
[server.log](https://github.com/Ericsson/codechecker/files/1362616/server.log)

and that's the output of the server for the starup and a subsequent call of the store command
[server_with_store.log](https://github.com/Ericsson/codechecker/files/1362622/server_with_store.log)

**Comment by whisperity** [comment]
Most strange.

`[14:10:57] {SERVER} - client_db_access_server.py:245 do_POST() - 127.0.0.1:53088 -- [Anonymous] POST /Default/v6.1/CodeCheckerService`

It's as if the storing of the results fire, but somehow the server connection ends.

You could try modifying the `libcodechecker/libhandlers/store.py` file (the package needs to be re`make`d afterwards!) so that a full stack trace is printed. (I believe the *actual* error reason gets eaten somewhere in creating the output.)

Change

```py
    except Exception as ex:
        LOG.info("Storage failed: " + str(ex))
        sys.exit(1)
    finally:
        os.remove(zip_file)
```

to

```py
    except Exception as ex:
        LOG.info("Storage failed: ")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        os.remove(zip_file)
```

**Comment by pspe** [comment]
here's the log of the store with traceback
[store_traceback.log](https://github.com/Ericsson/codechecker/files/1362916/store_traceback.log)

**Comment by pspe** [comment]
I seems, that the traceback messages have not been written into the log file I uploaded. When I'm again on that computer (Monday) I'll include them.

**Comment by pspe** [comment]
That's the output including the traceback
[store_traceback.log](https://github.com/Ericsson/codechecker/files/1367482/store_traceback.log)

**Comment by whisperity** [comment]
I'm really sorry you are experiencing this issue. There is something problematic when the code tries to actually send the bug reports to the server. The server doesn't receive any data as the client crashes before actual transmission can take place.

@team: Encoding the `version` parameter into the Thrift transport makes the code bail out.

@pspe: What does `CodeChecker version` gives to you as an output?

**Comment by gyorb** [comment]
@pspe what python version do you use?

**Comment by pspe** [comment]
thanks for your effort and for the great tool! 

@whisperity 
my `CodeChecker version` output is:

`Base package version          | 6.0.1`
`Package build date            | 2017-10-06T16:05`
`Git commit ID (hash)          | a3d8f812c236bedfcc89a5cb331156e4a4d66ab4`
`Git tag information           | 6.0.1`
`Configuration schema          | v6.0`
`Database schema               | v6.0`
`Server supported API (Thrift) | 6.1`
`Client API (Thrift)           | 6.1`

@gyorb 
`python --version`
gives:
Python 2.7.13

**Comment by gyorb** [comment]
Is it possible that the thrift can not encode the `context.version` here:
https://github.com/Ericsson/codechecker/blob/3a68635d789276cace2ada19c67534e04c1384ff/libcodechecker/libhandlers/store.py#L323-L327

@pspe could you check if modifying the `massStoreRun` like this works?
```
client.massStoreRun(args.name, 
                     args.tag if 'tag' in args else None, 
                     str(context.version), 
                     b64zip, 
                     'force' in args) 
```

**Comment by pspe** [comment]
@whisperity 
Great! That solved it. Storage of the result works now without error message. The run appeared successfully in the "runs" list and in the browser as well.

Thanks a lot!

**Comment by gyorb** [comment]
Thank @pspe  for the feedback, we will fix this.

**Comment by gyorb** [comment]
@pspe could you check the thrift-compiler version with `thrift --version`?
Another question did you create the python virtual environment with the `make venv` command?

**Comment by pspe** [comment]
my thrift version is: Thrift version 0.9.1

and I created the python virtual environment with `make venv`

**Comment by gyorb** [comment]
@pspe I thought there was some version mismatch but this is the right setup. Thanks!

**Comment by whisperity** [comment]
Isn't the Python version on 16.04 LTS 2.7.12 instead of .13? There could have been a change that file reads are Unicode. Seeing I couldn't reproduce this on a stock install.

**Comment by gyorb** [comment]
We read the `config.json` not as an utf-8 file. On the content we call the `json.loads` which will return an unicode string for all of the strings in the config file. This is the right behavior. 
Why there was no problem on our systems is a good question.
