### ISSUE TITLE
ldlogger unnecessarily logs linking actions

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1037]
There should be an env variable introduced in ldlogger which enables the logging of linking actions explicitly. By default it should not be logged.

~~~~
	{
		"directory": "/home/ednikru/work/codechecker/TinyXML",
		"command": "/usr/bin/g++ -o /home/ednikru/work/codechecker/TinyXML/xmltest /home/ednikru/work/codechecker/TinyXML/tinyxml.o /home/ednikru/work/codechecker/TinyXML/tinyxmlparser.o /home/ednikru/work/codechecker/TinyXML/xmltest.o /home/ednikru/work/codechecker/TinyXML/tinyxmlerror.o /home/ednikru/work/codechecker/TinyXML/tinystr.o",
		"file": "/home/ednikru/work/codechecker/TinyXML/tinystr.o"
	}
~~~~

**Comment by Xazax-hun** [comment]
Note that this might be useful in the future for CTU to know the linking graph. But it is definitely redundant for non-ctu analyses.

**Comment by whisperity** [comment]
In introducing that toggle, be careful, as some projects can end up having no separate compilation and link actions.
