### ISSUE TITLE
password.json based authentication

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1039]
`password.json` is not generated automatically
`password.json` usage should be better documented with examples.

**Comment by bruntib** [comment]
The usage of `~/.codechecker.passwords.json` is documented here:
https://github.com/Ericsson/codechecker/blob/master/docs/authentication.md#preconfigured-credentials. Do we need further description?

According to the documentation this file is not created automatically but has to be created manually based on a given template.

**Comment by gyorb** [comment]
Thanks! I've did not check the documentation, my bad.
