### ISSUE TITLE
Redundant switches in analyze?

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#1051]
It is possible to set the name switch both for analyze and store. Which one will be applied if they differ? Do we need both of them? This is very confusing.

**Comment by whisperity** [comment]
`store`'s help explains it.

`analyze --name` only prepares the report folder to contain a name. If no `--name` is given to `store`, it will try to make a name out of the output_dir's contents. If can't, it throws an error. If `--name` **is** given to `store`, it takes priority.
