### ISSUE TITLE
multiple roles in the credential file for the same service

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1057]
For example if there are two role to a particular web service then the following credentials file will not work, because the dictionary keys are the same.
```
{
"client_autologin" : true,
"credentials": {
    "webserver:8001": "admin:admin"
    "webserver:8001": "user:user"
  }
}
```

**Comment by bruntib** [comment]
In this case the value part could be either a string or a list:
```json
{
  "client_autologin" : true,
  "credentials": {
    "webserver:8001": ["admin:admin", "user:user"],
    "webserver:8002": "user:user"
  }
}
```

**Comment by bruntib** [comment]
I think we didn't support this use case because if multiple users are enumerated in the .json file then the server doesn't know which user is performing the given action. So a user name also has to be provided e.g. in the `--url` argument: `username@host:port`.

**Comment by gyorb** [comment]
In this case if the user wants to auto login with different credentials he needs to change the credentials file, or manage multiple credentials files manually.

**Comment by csordasmarton** [comment]
As we discussed on a meeting we do not want to support this.
