### ISSUE TITLE
table of content for the docs

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1074]
We have more and more documentation it would be nice to have a table of content in the docs for easier navigation.
For example user guide is quite long and there are many sections.

**Comment by bruntib** [comment]
GitHub doesn't support table of contents in its markdowns. There are tools for this (https://github.com/ekalinin/github-markdown-toc) which can be integrated into our build system if needed. Maybe it's enough to extend `venv-dev` with this tool.

**Comment by csordasmarton** [comment]
This tool only generates the toc, but not the anchors. So if I click on an item at the toc, it won't jump to the correct position.

**Comment by gyorb** [comment]
@bruntib if we generate the toc only at packaging time it will be still hard to navigate on our user guides viewed online on github.
