### ISSUE TITLE
ldlogger instead of intercept build

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1091]
intercept-build should be used only as a fallback if ldlogger is not available in `CodeChecker log`

at package build time if `intercept-build` is available in the path do not build ldlogger we could add an extra argument to build the ldlogger even if the intercept-build is in the path

**Comment by bruntib** [comment]
How can we fall back to `intercept-build` to our `ldlogger`? Our logger is just a set of .`so` files which are loaded in `LD_PRELOAD` environment variable. Should we simply check its existence? These will always exist, because we deliver them together with CodeChecker.

By the way what is the `ldlogger` binary in the `bin` directory and what do we use this for?

**Comment by gyorb** [comment]
The current behaviour is that if `intercept-build` is found we use that even if `ldlogger` is built into the package:
https://github.com/Ericsson/codechecker/blob/cb144db7358fbb3666e4b3f5aa04130642779538/libcodechecker/log/build_manager.py#L70-L91

This should be changed that we use `ldlogger` if it is available in the package and not `intercept-build` even if `intercept-build` is in the path.
I mentioned an extra packaging flag where we could build a package without the `ldlogger`. Right now if the `intercept-build` in the `PATH` at package build time we will not build and pack the `ldlogger`.
In OSX environment we should build it that way. The install guide's OSX part should be updated too.  

The ldlogger binary is used/called by the ldlogger.so to save and process the compilation commands.

**Comment by steakhal** [comment]
@dkrupp @csordasmarton WDT about this one?
I've seen [deadlocks ](https://reviews.llvm.org/D118439) using intercept-build.
In addition to this, starting from `clang-13` the official llvm releases [will contain intercept-build](https://github.com/llvm/llvm-project/commit/d9cf8291e7ef26317c13ed9a4e9bd88855166d5d), which raises the probability of hitting such bugs.

**Comment by csordasmarton** [comment]
@steakhal We will try to fix it in the next release.

**Comment by steakhal** [comment]
I started working on it, but I decided to work on something else.
However, I'll paste my branch here. Might help others.
https://github.com/steakhal/codechecker/tree/prefer-ldlogger
