### ISSUE TITLE
upgrade sqlachemy to 1.1.11

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1107]

**Comment by Xazax-hun** [comment]
Qny specific reason fot 1.1.11? It lloks like 1.1.15 is the newest.

**Comment by Xazax-hun** [comment]
And what about the other dependencies? They have new versions as well.

**Comment by gyorb** [comment]
@Xazax-hun the reason for v1.1.11 is that there is some internal dependency checking and this was the newest version which was checked.
