### ISSUE TITLE
Slow database clean up

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#1130]
Database clean up operation uses the following operation:
https://github.com/Ericsson/codechecker/blob/c7d4dfccf6d7d3ecd791e60660512d1ba0b3a1e6/libcodechecker/server/db_cleanup.py#L12-L22

The SQL query looks like this:
```sql
DELETE FROM files
WHERE
  files.id NOT IN (
    SELECT bug_path_events.file_id
    FROM bug_path_events
    GROUP BY bug_path_events.file_id) AND
  files.id NOT IN (
    SELECT bug_report_points.file_id
    FROM bug_report_points
    GROUP BY bug_report_points.file_id)
```
This operation is extremely slow because the `reports` table has a `foreign key constraint`.  It has to lookup in reports table which rows reference the removable file id.

I try to run this query on my database:
- `637652 reports`
- `17042 files`

The above query would like to remove `7000` rows from the file table. I didn't wait the end of this operation, I've stopped this query after `>600000ms`.

*Solution*: create an index on file_id column in reports table
```sql
CREATE INDEX reports_file_id ON reports (file_id);
```

**Comment by csordasmarton** [comment]
https://www.postgresql.org/message-id/op.ta8kk1aqcigqcu%40apollo13

**Comment by whisperity** [comment]
SQLite needs a special PRAGMA to enable foreign key checks. Is there a way to momentarily disable all foreign key constraints at connection start and then change this to enabled foreign keys on PostgreSQL?
