### ISSUE TITLE
Incorrection documentation about "cmd login"

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#1133]
On the doc https://github.com/Ericsson/codechecker/blob/master/docs/authentication.md
we can read:
> The user can log in onto the server by issuing the command CodeChecker cmd login -h host -p port -u username -pw passphrase.

which is incorrect according to the code https://github.com/Ericsson/codechecker/blob/7a518174df70de3b2d6acba8f8914dc9551e8807/tests/libtest/codechecker.py#L39

**Comment by dkrupp** [comment]
and we should also replace ~/.codechecker_passwords.json to ~/.codechecker.passwords.json

**Comment by sylvestre** [comment]
Thanks!
