### ISSUE TITLE
Prevent concurrent storage of the same run name from multiple shared servers

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1138]
CodeChecker can be scaled by using multiple codechecker servers with a single DB backend.

In this case however, if a run storage event starts in parallel through different codechecker servers, the storage results will interfere and get corrupted.

Prevent this from happening by registering a flag in the db that a run is under update.

**Comment by Xazax-hun** [comment]
This is only the artifact of updating a run right? Checking in multiple runs or updating independent runs is still ok. Maybe changing the title of the bug would be a good idea to be less scary.

**Comment by whisperity** [comment]
Yes. It deals with the case of one server already handling a store operation and another server starting another store to the same run, as currently the storage lock is the server's state, whereas the database itself could be shared.
