### ISSUE TITLE
--enable-all with other options doesn't run most of the clang-tidy checkers

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#1148]
I am running the command:
`CodeChecker check -j 13 -b "hg pull -u && hg update -r default && ./mach build -j 23" -o codechecker-results --enable-all --enable alpha --disable google-readability-casting --disable llvm-include-order --disable google-readability-braces-around-statements
`

Unfortunately, with this serie of enable/disable, most of the clang-tidy checkers are not executed.

**Comment by whisperity** [comment]
Could you upload the contents of `./codechecker-results/metadata.json`, particularly the value of the `checkers` dict? IIRC that dict contains every checker that was executed in the particular analysis.

**Comment by sylvestre** [comment]
I am getting this list:
`"clang-tidy": ["bugprone-integer-division", "bugprone-suspicious-memset-usage", "bugprone-undefined-memory-manipulation", "cert-dcl58-cpp", "cppcoreguidelines-special-member-functions", "google-build-namespaces", "google-global-names-in-headers", "misc-assert-side-effect", "misc-bool-pointer-implicit-conversion", "misc-dangling-handle", "misc-definitions-in-headers", "misc-fold-init-type", "misc-forward-declaration-namespace", "misc-forwarding-reference-overload", "misc-inaccurate-erase", "misc-incorrect-roundings", "misc-inefficient-algorithm", "misc-lambda-function-name", "misc-macro-repeated-side-effects", "misc-misplaced-const", "misc-misplaced-widening-cast", "misc-move-const-arg", "misc-move-constructor-init", "misc-move-forwarding-reference", "misc-new-delete-overloads", "misc-noexcept-move-constructor", "misc-non-copyable-objects", "misc-redundant-expression", "misc-sizeof-container", "misc-sizeof-expression", "misc-string-compare", "misc-string-constructor", "misc-string-literal-with-embedded-nul", "misc-suspicious-enum-usage", "misc-suspicious-missing-comma", "misc-suspicious-semicolon", "misc-swapped-arguments", "misc-throw-by-value-catch-by-reference", "misc-unconventional-assign-operator", "misc-undelegated-constructor", "misc-uniqueptr-reset-release", "misc-unused-raii", "misc-use-after-move", "misc-virtual-near-miss"]},
`
As you can see, for example, there is no modernize-* clang tidy checker.
