### ISSUE TITLE
remove paths from run results if the bug remains in run

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1155]
Say RUN1 is being updated with local reports REPORT_LOCAL.

Says REPORT_LOCAL contains reports with hash  H1234. RUN1 also contains reports for hash H1234. Today, the detection status of all the reports with H1234 in RUN1 that was not present in REPORT_LOCAL is set to `resolved`. These reports should be removed instead from RUN1 during the run update.

The reason is, that in many cases the bug remains in the run, but paths of the reports change a little, then we keep the old reports with resolved status, however the bug in fact remains in the system. So we are collecting reports with old invalid paths and so the report set grows indefinitely large.

**Comment by bruntib** [comment]
While solving this issue we have to keep in mind that by removing reports we won't be able to provide history information about the runs, i.e. presenting the reports found in an earlier storage session in the same run.
We could somewhat save this history feature by maintaining the date of finding/updating of the report. This way by filtering on date we can find the reports of a previous run, but even in this case the non-deleted reports will be shown.
