### ISSUE TITLE
new number of files column in statistics tab

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1161]
Add number of files column in the Checker statistics tab to show in how many individual source files were the bug found

**Comment by Xazax-hun** [comment]
Does this really adds value over how many times a certain kind of bug was found?

**Comment by dkrupp** [comment]
This was a user request. I guess it tells the user how many individual source files are affected by the given bug. So is it focused over a small set of files or scattered to a large fileset.

**Comment by gyorb** [comment]
This would be an expensive query, discuss further.

**Comment by csordasmarton** [comment]
As we discussed personally we do not want to do this because it would be a very expensive query.
