### ISSUE TITLE
remove dbversion table and config

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1204]
We have alembic to handle database schema versioning.
The old dbversion table is not needed. Database version info can be removed from the config file.too.

**Comment by whisperity** [comment]
And from the versioning script of #1083 too.

**Comment by whisperity** [comment]
The `package_context` and `libhandlers/version` scripts also need to be updated.

**Comment by csordasmarton** [comment]
Database version information from the config file was removed in #2270.

**Comment by Xazax-hun** [comment]
Sorry for the offtopic, I just wonder do we want to keep the migration scripts indefinitely? Or is it sensible to say we support the migration up to 2-3 years and remove migration scripts older than that? (To avoid potential maintenance burden, and they are in some sense essentially untested. I assume we did not rerun all of them after the Python 3 conversion.)

**Comment by gyorb** [comment]
I do not think there is a lot of maintenance burden. If needed with alembic you can manually trigger schema upgrades and downgrades if it is necessary. Keeping all the changes makes it possible to switch to any state.
Right now if you create a new empty database alembic initializes it by going over all the changes and applying them to get to the last state, so they are used.

The database works even after the python3 conversion, I used a db created with an older version and started a newer server to use that, I did not experience any problems.
