### ISSUE TITLE
Files attempting to be added multiple times at failure ZIP creation

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#1219]
@sylvestre gets this error which can result in the `check` command hanging indefinitely.

```
data/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/libcodechecker/analyze/analysis_manager.py:454: UserWarning: Duplicate name: u'sources-root/data/jenkins/workspace/firefox-codechecker/media/libvpx/config/linux/x64/vpx_config.h' zipfile.ZIP_DEFLATED)
/data/jenkins/workspace/update-codechecker/build/CodeChecker/lib/python2.7/libcodechecker/analyze/analysis_manager.py:454: UserWarning: Duplicate name: u'sources-root/data/jenkins/workspace/firefox-codechecker/media/libvpx/libvpx/vpx/vpx_integer.h' zipfile.ZIP_DEFLATED)
[ERROR] [00:28] - Analyzing 'blockd.c' with clangsa failed.
```

**Comment by whisperity** [comment]
Extra information: analysis was run without ctu but with debug checkers enabled. This perhaps creates an output from which the same file is sucked up multiple times into the fail zip.

Tagging @martong as he was the last who modified this part of the code. The issue is free for grabs otherwise!

**Comment by gyorb** [comment]
debug checkers should not be enabled, the provide non parseable output, it is useful mainly for checker or analyzer developement

**Comment by whisperity** [comment]
They are not enabled by `--enable-all`. Unless `-e debug` is explicitly given, they stay disabled.
I don't think the disabled state of them should be enforced. CodeChecker can be useful for checker development too, to see quickly what changed when the developer altered the checker logic a bit.

This issue seems to be unrelated to the fact of debug hecklers running. Something at zip creation is amiss and doesn't make sure of no duplication of files.

**Comment by whisperity** [comment]
Doesn't seem to be an issue. :neutral_face: I've checked the code, and the writing of the ZIP is exception-handled. Also, we are using a `set`, so the list of files to be written into the failure-ZIP should be uniqued.

https://github.com/Ericsson/codechecker/blob/master/libcodechecker/analyze/analysis_manager.py#L408-L425

Strangely, your log reports the issue to `analysis_manager:454` which line doesn't even contain any ZIP actions, and haven't ever, I've gone back to CodeChecker `5.8` to check...

The "duplicate entry" is only a warning. It looks like ZIPs which contain the same file multiple times can still be handled (both `unzip`, WinZIP, Total Commander and `file-roller` handles them well) but this warning is only issued at the closing of the ZIP's context manager. I will fix this in a PR shortly.

I can't seem to figure out why the same header is attempted to be added twice into the ZIP...

@sylvestre Can you please specify which versions of Clang and CodeChecker you are using? Also, run an analysis with `--verbose debug` (so that CodeChecker's output contains more information) **but** with the `debug.` checkers **disabled**.

**Comment by csordasmarton** [comment]
Please try to run this with the latest CodeChecker. If you still experience this problem, please feel free to reopen it.
