### ISSUE TITLE
logout in the web browser

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1220]
currently it is not possible to logout in the browser

**Comment by whisperity** [comment]
We need to be careful about really wanting this and throwing away WWW-Authenticate! Once the credentials are no longer in the request header, a load balancer giving the request to another server will force the user to reauthenticate.

Assuming we don't just attempt the solutions at hijacking WWW-Authenticate to force a logout somehow. It's not allowed as pet the HTTP standard.
