### ISSUE TITLE
Language is not always detected properly

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1228]
It seems that the build action language is not always detected properly in in log_parser.py  and in vendor/build-logger/src/ldlogger-tool-gcc.c

The rule for setting the languages shall be the following
```
If g++ compiler is used
  if (-x switch is set)
      the language is set according to the -x switch (c or c++)
  else
       the language is c++

If gcc compiler is used
  if (-x switch is set)
      the language is set according to the -x switch (c or c++)
  else
       the language is set based on source file extension
```

**Comment by bruntib** [comment]
Determining the language is not this easy. A build command may contain several source files and different `-x` flags may belong to them specifying different languages.

**Comment by whisperity** [comment]
Also, what if Clang is used? Calling `clang` with a C++ file succeeds in building the object file, it's only an error when linking that it tries some freakish C-like linkage rules. And no `-x whatever` needs to emitted to the build log for this.

**Comment by bruntib** [comment]
This feature has been solved.
