### ISSUE TITLE
Add shortcut and button to get the next search results in the webgui code viewer

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#124]
Currently the only way to get the next searh result is to hit ctrl+F again, and then return.

**Comment by dkrupp** [comment]
Try to use the browsers's built in search tab. Disable code mirror internal find.
Load the whole source file by codemirror.

**Comment by bobszi** [comment]
This can be done via CodeMirrors viewportMargin attribute. However:

"viewportMargin: integer
(...) You should usually leave it at its default, 10. Can be set to Infinity to make sure the whole document is always rendered, and thus the browser's text search works on it. This will have bad effects on performance of big documents."

**Comment by bobszi** [comment]
"viewportMargin: Infinity" has terrible and inconsistent performance, even on files below 2k lines.
Browser search seems to not be a preferable solution for searching in a source file.

**Comment by dkrupp** [comment]
-create a patch for codemirror in the packaging script
-check if codemirror already has a bug ticker reporting this fault. if not, write one and submit the patch as a solution.

**Comment by bobszi** [comment]
Could not find any issues regarding this.

**Comment by bobszi** [comment]
Wouldnt a simple help [?] button in the EditorHeader suffice? It could show a small how-to for the search if the mouse cursor hovers over it.
