### ISSUE TITLE
Bug hash generation for indented code

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#1241]
Suppose we analyze and store the following code:
```cpp
int main()
{
    sizeof(42); // Bug
    return 0;
}
```
Next, we change the indentation from 4 spaces to 2 spaces, analyze the code again and store it:
```cpp
int main()
{
  sizeof(42); // Bug
  return 0;
}
```
When we analyze the code again it will generate a different bug hash for the same bug because we doesn't `trim` the line when we generate the bug hash in case of clang tidy.
So in the Bug overview I will see the following:
 - /home/ecsomar/projects/simple/main.cpp @ Line 2 -> **Resolved**
 - /home/ecsomar/projects/simple/main.cpp @ Line 2 ->  **New**

I think it would be better to trim the line when we generate a bug hash.

**Comment by bruntib** [comment]
The hash contains the column number where the line begins. Should we remove that too? Does anybody know what was the reason of including the column number?

**Comment by csordasmarton** [comment]
@bruntib The hash contains the column number where the `bug` begins, not the line!
If we remove this column number and a line contains multiple bugs it will generate the same bug hash for these bugs.
```cpp
int main() {
  sizeof(42); sizeof(43);
}
```
In the above example it would generate same bug hash for `sizeof(42);` and `sizeof(43);`.
