### ISSUE TITLE
Consider using containing context in hashes for clang-tidy and clang warnings

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1250]
The hashes for Clang-tidy and clang warnings are generated from the source code line , column and reporting checker identifier.

These hashes can easily collide if there is a clang-tidy warning for a line of code that repeats itself thought the code.

To make findings more unique I suggest to use context of the finding for generating the hash.
That is the including namespace, class, function name.

There are several hash clashes for example in xerces-c-3.1.1/src/xercesc/validators/schema/TraverseSchema.cpp
for misc-throw-by-value-catch-by-reference findings

To generate such a hash, most probably we need to use the clang parser.

**Comment by gyorb** [comment]
Until the external tool is available the tidy hash fix is reverted #1349 so the hash generated for the tidy reports will not change now.
The fix #1291 should be re done if the tool will be available. The corresponding issue #1241 is reopened.

**Comment by csordasmarton** [comment]
As we discussed on a meeting we do not want to go to this direction. We are recommending to the users to use context free hash instead of context sensitive and we will support migration from old hashes to a new one (#2628).
