### ISSUE TITLE
server startup can be slow due to long dangling file garbage collection

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1261]
In practice it can take up to 2 minutes per product, which is too long.

Also due to this slowness change the log level of this message to INFO.

[2017-12-15 13:33:27] {DB CLEANUP} [16633] <139784428640000> - db_cleanup.py:10 remove_unused_files() - Garbage collection of dangling files started...

**Comment by gyorb** [comment]
Is this still slow with the new fileid index in the report table?

**Comment by dkrupp** [comment]
yes, 2 minutes on a large product DB

**Comment by csordasmarton** [comment]
The log level has been changed but we should check why the clean up is too slow.

**Comment by niuzhi** [comment]
Dear Gyorgy Orban：
**I installed codechecker5.8 in ubuntu system, but when I run CodeChecker analyze, I report the following error. How to deal with this issue? Thank you
================================================================
(venv) root@niuzhi:~# CodeChecker analyze ./compile.json -o ./results
[00:46] - Previous analysis results in '/root/results' have been removed, overwriting with current result
[00:46] - Starting static analysis ...
[ERROR] [00:46] - Analyzing dlqoscommon.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

[00:46] - [2/1235] clangsa analyzed global.c successfully.
[00:46] - [3/1235] clangsa analyzed CommQue.c successfully.
[ERROR] [00:46] - Analyzing dlschdmcm.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

[ERROR] [00:46] - Analyzing mcm_init.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

[ERROR] [00:46] - Analyzing dlcomp.c with clangsa failed.
[ERROR] [00:46] - clang: error: unknown argument: '-mno-sched-prolog'
clang: error: unknown argument: '-mno-apcs-frame'

**Comment by gyorb** [comment]
@niuzhi I've created a separate issue for your error, #1265  we should continue the discussion there.

**Comment by csordasmarton** [comment]
@gyorb It is possible that #1377 solved this problem. We should check it.

**Comment by gyorb** [comment]
I failed to reproduce this with the new db schema.
File cleanup is done not only at server start but if a run is removed so if the runs are cleaned regularly the cleanup at the server start should not take too much time.
