### ISSUE TITLE
ImportError: cannot import name _psutil_linux

### ISSUE THREAD

**Issue by srujithreddy** [Ericsson/codechecker#1273]
Hello, 

I ran into an error when tried to use below command

CodeChecker log -b "cd ../../ && make fastclean && make all -j$ncpu" -o $where/Step_1_make.json

Error:

[WARNING] [2017-12-28 14:49] - Couldn't import module for subcommand 'log'... ignoring.
ImportError: cannot import name _psutil_linux

I don't see this error when I run the command for the first time. When I re-run the command then I see this issue. 

I have psutils installed in my machine!

**Comment by whisperity** [comment]
`psutil` doesn't have to be installed on your machine, but in the environment CodeChecker is running from. Make sure that every time you issue the CodeChecker command, you have the virtual environment `source`d.

**Comment by srujithreddy** [comment]
thanks for the comment. I made 2 scripts. utils.sh and script1.sh

utils.sh

#!/bin/bash
codechecker_path="$PWD/codechecker"
ncpu=`nproc`
if [ -z "$ncpu" ] ; then
ncpu="1"
fi
export PATH="$codechecker_path/build/CodeChecker/bin:$PATH"
source "$codechecker_path/venv/bin/activate"

and script1.sh

source "utils.sh"
where=`pwd`
CodeChecker log -b "cd ../../ && make fastclean && make all -j$ncpu" -o $where/make.json

I think I am sourcing virtual environment in utils.sh. Please let me know if I am missing any point.

**Comment by srujithreddy** [comment]
Hello, I looked further and I see I am in virtual environment but looks like virtual environment is missing some psutil files. 

At codechecker/venv/local/lib/python2.7/site-packages/psutil location, I don't see _psutil_linux file and that's the reason I see import failure. 

Is there any work around ? or is it a known issue ?

**Comment by whisperity** [comment]
Haven't seen this issue before, assuming people properly set up their environments, by using `make venv`. You can try manually installing the dependencies, after sourceing the virtualenv you can do in the CodeChecker source folder: `pip -r install .ci/python_requirements` (or `pip install -r`, I'm not sure about the order of the arguments). But this is exactly what `make venv` should have done.

I did a fresh `make venv` is a subfolder on my computer and the thing sets up properly. `_psutil_linux` is a binary:

    -rwxrwxr-x  1 whisperity whisperity 47752 Dec 28 20:27 _psutil_linux.so*

Worst case, could you try renaming (or entirely removing) the `venv` folder and then execute `make venv`? It could be that for some nasty reason your computer can't compile this binary.

**Comment by srujithreddy** [comment]
thanks for the comments. I didn't realized that _psutil_linux is a .so file. In the make file, looks like I am deleting all .so files which resulted in this problem. I modified my make file rules and it works now.

**Comment by whisperity** [comment]
🙂 Make (ha-ha) sure that CodeChecker is **way outside** your project folder, so that no make commands can touch what CodeChecker runs from.
