### ISSUE TITLE
In diff view the bug path tree is not shown when viewing a report

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1275]
See for example
http://cc.elte.hu:15002/Default/#baseline=redis_2017-12-08_19%3A51%3A44_noXTU&newcheck=redis_2017-12-08_19%3A51%3A44_XTU&difftype=0&tab=redis_2017-12-08_19%3A51%3A44_noXTU_diff_redis_2017-12-08_19%3A51%3A44_XTU&reportHash=2b52e295324591c6c3d28825da41c399&report=7577&subtab=2b52e295324591c6c3d28825da41c399

![image](https://user-images.githubusercontent.com/8030953/34523332-48316366-f097-11e7-8f80-705a19862a24.png)

**Comment by whisperity** [comment]
It is visible for me when opened on my home computer. Windows 7 x64, Firefox 56.0.2

**Comment by whisperity** [comment]
Could be related to #767. Opening the diff and the file from the start page and **not** via a link shows the bugs. There is no output in the developer console which would indicate an error.

**Comment by dkrupp** [comment]
yes it only appears from the start page. Clicking on the link or CTRL-F5 fixes the issue. There is no error in the console.
