### ISSUE TITLE
Selectable compiler binary at package build

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#13]
Introduce a command line parameter
--clang /path/to/clang/binary

to specify to codechecker which clang binary should be used.
If this parameter is not specified, then the path specified config.json file should be used.

**Comment by bruntib** [comment]
This issue seems to be outdated, as this can be configured in config/package_layout.json. Would we like to add this flag anyway?

**Comment by gyorb** [comment]
this issue can be closed, manual config file editing is possible, or available clang in the PATH can be changed
