### ISSUE TITLE
add an option to `CodeChecker cmd results` to return the number of findings only

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1324]
Introduce a new option for 
`CodeChecker cmd results`
`-c` to return the number of filtered reports only (instead of all findings).

**Comment by whisperity** [comment]
It should instead be added to `CodeChecker cmd sum`. This feature fits the purpose of that command much better. Alternatively, just extend sum's output to *always* contain this information.

**Comment by csordasmarton** [comment]
This has been resolved in #1328.
