### ISSUE TITLE
detection status viewing and filtering together with uniqueing

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1337]
Improve the current behavior and UI which can be a bit confusing for the users.
Right now the filtering of the detection statuses is not disabled if uniqueing is enabled and multiple runs were selected.

* only one run is selected:
  - detection status can be shown
  - filtering based on detection status is available

* multiple runs selected:
 detection status can not be calculated if uniqueing is enabled because the report
could be found with different detection statuses in different runs 
   - disable detection status filter
   - do not show detection status values

**Comment by whisperity** [comment]
"Disable detection status filter" should not just include the normal "grey out and turn off the buttons" but also a small note that it is disabled due to "Unique bugs" being enabled.
