### ISSUE TITLE
At least 1 report directory should be mandatory for parse command

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1343]
Do not accept 0 positional arguments for parse command as it can lead misleading behavior as it will not find reports as either `CodeChecker analyze` or ` CodeChekcer  check` has default output report directory.

So at least 1 positional arguments must be mandatory.

```
usage: CodeChecker parse [-h] [-t {plist}] [-e {html}] [-o OUTPUT_PATH] [-c]
                         [--suppress SUPPRESS] [--export-source-suppress]
                         [--print-steps]
                         [--verbose {info,debug,debug_analyzer}]
                         [file/folder [file/folder ...]]

Parse and pretty-print the summary and results from one or more 'codechecker-
analyze' result files.

positional arguments:
  file/folder           The analysis result files and/or folders containing
                        analysis results which should be parsed and printed.
                        (default: /home/ednikru/.codechecker/reports)
```

**Comment by whisperity** [comment]
This heavily contradicts the default behaviour of `CodeChecker analyze` which will use the folder under the "workspace" for output.

Why are we making it so hard for people who just want to use CodeChecker with default settings?
