### ISSUE TITLE
CodeChecker log generated json can't handle filenames with spaces

### ISSUE THREAD

**Issue by gerazo** [Ericsson/codechecker#1366]
If I have a file called "lib 2.cpp" it breaks the system as CodeChecker log functionality does not escape the filename in the generated json. The generated command in json is:

```
	"command": "/usr/bin/g++-5 -Wall -c example/lib 2.cpp example/main.cpp"
```
From here, other scripts building on this json break.

**Comment by gyorb** [comment]
@gerazo could you verify that #1501 resolves this issue?

**Comment by gerazo** [comment]
I've tested this on my projects with spaces. Everything is working fine: The buildlog is correctly generated with excapes. The analyzer can eat the submitted parameters and the analysis results are as expected. :+1:
