### ISSUE TITLE
show run configuration in the run overview

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#139]
include the following info:

- [ ] clang version
- [x] codechecker command parameters
- [x] enabled/disabled checkers
- [x] checker config

**Comment by AlexTelon** [comment]
This would be very helpful because right now there is no way I know of that I can see which checkers are enabled when I run. I can deduce it from my -e ericsson  and -d alpha and so on. But it would be nice with a list to see if you have everything you wanted.
