### ISSUE TITLE
Do not highlight last bug path message if not absolutely last

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#1395]
Currently, the last bug path message is highlighted in *red* colour even if the bug path continues later on in another file. This is true for every file if the bug path jumps back and forth. The red colour makes the user believe it is the reason for the bug report, but sometimes it's just an "Entered call from..." line, sometimes along with many others directly before it, those written in blue.

**Comment by gyorb** [comment]
On the long term it would be good to think about coloring based on the "main" section in the report plist as an alternative. The data from there is used at the report listing.
It is possible that the last bug event and the main section point to a slightly different locations, however when the bug paths are shown we just render the event/control nodes from the path and the "main" section is not rendered.
