### ISSUE TITLE
Codechecker is unusable on big projects with some history

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#1399]
Codechecker becomes unusable when used on big projects like Firefox with more than 60 runs.

For example, it takes minutes to run the "Checkers statistics" or gather runs results.

**Comment by whisperity** [comment]
Are you using a PostgreSQL or a SQLite database as the report storage backend? In case of SQLite, it is well advised to move to Postgres. CodeChecker can get slow on SQLite due to how SQLite works, and I don't think SQLite databases were meant to be used for large-scale deploys.

**Comment by sylvestre** [comment]
PostgreSQL.
As said in an private email thread, there are way too many open many XHR channels.
Having a quick look to queries, the following query is way to slow (took 11 seconds):
`SELECT runs.id AS runs_id, runs.name AS runs_name, count(DISTINCT reports.bug_id) AS count_1 FROM reports LEFT OUTER JOIN files ON reports.file_id = files.id LEFT OUTER JOIN review_statuses ON review_statuses.bug_hash = reports.bug_id LEFT OUTER JOIN runs ON reports.run_id = runs.id GROUP BY runs.id ORDER BY runs.name;
`

EXPLAIN ANALYZE returns:

```
 Sort  (cost=971423.58..971423.70 rows=47 width=58) (actual time=118272.064..118272.121 rows=47 loops=1)
   Sort Key: runs.name
   Sort Method: quicksort  Memory: 28kB
   ->  GroupAggregate  (cost=941548.03..971422.27 rows=47 width=58) (actual time=40967.029..118270.606 rows=47 loops=1)
         Group Key: runs.id
         ->  Sort  (cost=941548.03..951505.95 rows=3983170 width=58) (actual time=40945.528..49395.365 rows=3996305 loops=1)
               Sort Key: runs.id
               Sort Method: external sort  Disk: 265648kB
               ->  Hash Left Join  (cost=3.06..205367.35 rows=3983170 width=58) (actual time=0.718..25652.204 rows=3996305 loops=1)
                     Hash Cond: (reports.run_id = runs.id)
                     ->  Seq Scan on reports  (cost=0.00..150595.70 rows=3983170 width=41) (actual time=0.407..11691.156 rows=3996305 loops=1)
                     ->  Hash  (cost=2.47..2.47 rows=47 width=25) (actual time=0.232..0.232 rows=47 loops=1)
                           Buckets: 1024  Batches: 1  Memory Usage: 3kB
                           ->  Seq Scan on runs  (cost=0.00..2.47 rows=47 width=25) (actual time=0.023..0.111 rows=47 loops=1)
 Planning time: 1.179 ms
 Execution time: 118505.962 ms

```

**Comment by sylvestre** [comment]
This is also visible on the processing side. It takes more than half a day to import data:
```
Total number of reports: 57236
----=================----
[09:36] - Storing analysis results for run 'firefox_201802030936'
[21:25] - Storage finished successfully.
```

(and this is just a partial generation)

**Comment by gyorb** [comment]
Yes we know about the problem. Did you try our latest 6.5.1 release? We did some schema modifications which should improve importing the data.

In the other query the slow part is calculating the unique reports, we know about this problem and we are thinking about some solutions.

**Comment by sylvestre** [comment]
I updated with trunk, schema updated, still very slows on List of runs and checker statistics

**Comment by sylvestre** [comment]
Another example of inefficient query:

```
EXPLAIN ANALYZE   SELECT reports.run_id AS reports_run_id, reports.detection_status AS reports_detection_status, count(DISTINCT reports.bug_id) AS count_1 FROM reports GROUP BY reports.run_id, reports.detection_status
;
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=854883.18..895763.43 rows=47 width=41) (actual time=10934.702..38096.090 rows=48 loops=1)
   Group Key: run_id, detection_status
   ->  Sort  (cost=854883.18..865103.13 rows=4087978 width=41) (actual time=10921.290..15401.348 rows=4087978 loops=1)
         Sort Key: run_id, detection_status
         Sort Method: external merge  Disk: 203800kB
         ->  Seq Scan on reports  (cost=0.00..154452.78 rows=4087978 width=41) (actual time=0.023..4962.117 rows=4087978 loops=1)
 Planning time: 0.157 ms
 Execution time: 38152.597 ms
(8 rows)
```
with 
```
select count(*) from reports;
  count  
---------
 4087978
(1 row)

```

An index would probably help here...

**Comment by sylvestre** [comment]
Trying to delete a non existing run:
```
[DEBUG][2018-03-06 10:26:26] {system} [23863] <140149699856128> - client.py:274 setup_client() - returning service client
[WARNING][2018-03-06 10:26:58] {system} [23863] <140149699856128> - cmd_line_client.py:69 check_run_names() - The run named 'firefox_201711230944' was not found.
```

Took 32 seconds to detect that the run doesn't exist.

**Comment by bruntib** [comment]
Since the opening of this ticket there were many performance improvements. If you still experience further performance problems, please, reopen this ticket.

**Comment by sylvestre** [comment]
I have been deleting old builds to keep ~10 of them to mitigate the performance regressions.
With 2 111 992 of reports, the performances are acceptable.

**Comment by sylvestre** [comment]
thanks :)

**Comment by sylvestre** [comment]
@bruntib performances regressed significantly recently. Is that a known issue? thanks
