### ISSUE TITLE
Two copies of every issue?

### ISSUE THREAD

**Issue by danielpoirot** [Ericsson/codechecker#1405]
I have just installed Clang 3.9 and CodeChecker 6.6.0. I am analyzing FFMPEG 2.8.11 in a fresh directory (no other runs). 
I am getting two copies of each finding (and each empty finding) which are exactly the same:

siguser@ubuntu:~/work/ffmpeg-2.8.11/build/results$ diff zerocodec.c_0b7db2c77077c46a6d23143c9163c03c.plist zerocodec.c_13f1cc50acdd1d278353991c28940578.plist 

siguser@ubuntu:~/work/ffmpeg-2.8.11/build/results$ cat zerocodec.c_13f1cc50acdd1d278353991c28940578.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
 <key>clang_version</key>
<string>clang version 3.9.1-4ubuntu3~16.04.2 (tags/RELEASE_391/rc2)</string>
 <key>files</key>
 <array>
 </array>
 <key>diagnostics</key>
 <array>
 </array>
</dict>
</plist>

**Comment by whisperity** [comment]
This is seemingly not an issue at first glance. Two report files can happen for these two reasons:

 * You also installed Clang-Tidy. In this case, each source file is analyzed twice with both analyzers, resulting in one analyzer giving one output, and the other analyzer giving the other one. If the file contains no issues that either analyzer can find, the result will be empty.
 * FFMpeg's build toolchain builds the same source file with two different configuration (e.g. for testing, or for a different architecture). In this case, the build database will command CodeChecker to run two analyses (for the A and B configuration), which will result in two outputs from the two separate analysis. Of course, if the file contains no defects, both results will be empty.

**Comment by bruntib** [comment]
This is the normal behavior. Separate .plist files belong to ClangSA and ClangTidy. This can be reproduced with a simple "Hello world" too.
