### ISSUE TITLE
Build action map is created twice?

### ISSUE THREAD

**Issue by martong** [Ericsson/codechecker#1420]
When both clangsa and tidy is turned on I receive the following debug warnings:
```
Multiple entires in compile database with the same (source, target) pair:
```
But the compile command json does not contain such multiple entries.
Perhaps we call the function `def create_actions_map(actions, manager)` twice on the same object.

**Comment by gyorb** [comment]
I found this issue and in the upcoming statistics support pull request it will be fixed.
