### ISSUE TITLE
Skip linking action from compilation_database

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1436]
Linking actions are not used for the analysis. Introduce a new flag for
CodeChecker log subcommand to skip linking actions.
`
--skip-linking
`
This way the compile_commands.json will be smaller.

**Comment by gyorb** [comment]
maybe we could generate a separate `link_commands.json` file?

**Comment by whisperity** [comment]
Isn't `CodeChecker analyze` ignoring link commands anyways?

**Comment by gyorb** [comment]
Yes, analyze is ignoring them but the commands are there in the file. If there is a lot of linking actions this file can be quite big. Loading up and parsing json can be quite slow.

**Comment by dkrupp** [comment]
Good idea! Lets keep linking actions in link_commands.json separate file.

**Comment by gyorb** [comment]
The skipping of the linking actions is done, but I still think that collecting the linking actions in a separate file can be valuable. I've created a separate issue for that #1482

Another change in the logging in connection to this modification is in #1480
