### ISSUE TITLE
consistent report/bug counting

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1443]
Report count and unique bug count can be confusing because they provide different numbers, multiple reports can belong to the same bug.
There is no bug uniqueing in the `parse` command it lists all the reports.

To use one consistent numbering everywhere use report counting without uniqueing by default.

### Runs view changes:
- [x] number of reports (without uniqueing all reports except the resolved  report count)
- [x] `number of reports` should be renamed to `number of reports without fixed` or a popup window should describe how it is counted
- [x] detection status (do not count with uniqueing)

### Bug list view changes:
- [x] by default uniqueing is disabled (optionally it can be turned on)

### Checker statistics changes:
- [x] statistics should not be calculated using uniqueing

### Command line changes:
- [ ] `results` viewing and filtering should not use uniqueing 
- [x]  `sum` should be in sync with the statistics view on the UI (no uniqueing)

### The numbers should be calculated like this:
- [x] __Number of reports__
  - number of unresolved reports
  - number of reports = non unique all reports - resolved - false positive - intentional

- [x] __Detection status__
  - show non unique numbers  ( review status is not included in the counting!)

- [x] __Checker/Severity statistics__
  - unique by default
  - if multiple runs are selected reports are counted multiple times
  - add unique button

- [x] __All reports__
   - non unique by default
   - set default filters to (unreviewed, confirmed, new, reopened, unresolved)

- [x] __Diff__
   - non unique by default
   - set default filters to (unreviewed, confirmed, new, reopened, unresolved)
 
- [x] __Tag diff__
   - non unique by default
   - set default filters to (unreviewed, confirmed, new, reopened, unresolved)
   - hash list based calculated based on dates detected, fixed

**Comment by dkrupp** [comment]
would be great to include these fixes in the 6.6 if possible
