### ISSUE TITLE
Sanitize command line json outputs?

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#1455]
CodeChecker cmd runs will omit a list. Every element will be an object with a single entry, the run name. We might rather have one object as output with the run names as keys instead. It would be easier to process that way.

Also, some commands output multiple JSON lists. Maybe it would be better to always output a single object and give a name to the lists?

**Comment by bruntib** [comment]
As far as I can see this issue has been resolved. If you can see further incorrect JSON outputs, please reopen the ticket.
