### ISSUE TITLE
Enable passwordless token based authentication

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1462]
Today a jenkins script can authenticate itself using the username/password stored in the 
.codechecker.passwords.json
described by:
https://github.com/Ericsson/codechecker/blob/master/docs/authentication.md#-preconfigured-credentials

It is not a good practice to store passwords in text files.

A user should be able to generate a token from command line, that can be used to authenticate in the name of the given user.
Extend the codechecker login command with the
`
--generate-token option
`
which generates a new token to the stdout.

This token then can be used as ~/.codechecker.passwords.json file.

For example
CodeChecker cmd login -u ednikru --generate-token
Authentication successful. The generated token is: 12345678
You can use this in .codechecker.passwords.json instead of your password.
```
.codechecker.passwords.json 
{
"client_autologin" : true,
"credentials": {
"localhost:8080" : "ednikru:12345678",
}
}
```

**Comment by whisperity** [comment]
Adding a new option to `cmd login` is superfluous. At a successful login, a token is generated and saved in `~/.codechecker.session.json`. To fetch such a token without it getting intermingled with your user's configuration, you can always override the `HOME` environment variable (which Python's `~`-expander uses!).

    echo "password" | HOME=/tmp/foobar CodeChecker cmd login username
    cat /tmp/foobar/.codechecker.session.json

**Comment by gyorb** [comment]
@whisperity we talked with @csordasmarton about creating a new sub command something like this and do not put it under the `cmd login`:
To generate a new token:
`CodeChecker cmd token new --url ... --description "my ci token" username`
List active tokens for the users at the server:
`CodeChecker cmd token list --url ... username`
Remove active token from the server created by the user which is not needed anymore:
`CodeChecker cmd token remove --url ... username token_to_remove`
