### ISSUE TITLE
Skipfile works only with absolute paths and not with relative paths

### ISSUE THREAD

**Issue by martong** [Ericsson/codechecker#1502]
Also,
```
-*
```
does not exclude all files.

Also,
```
-.*
```
does not exclude all files.

A path must always start with `/` otherwise it has no effect.

**Comment by gyorb** [comment]
If you use a relative path is should start with a `*`.

**Comment by gyorb** [comment]
@martong I could not reproduce, `-*` excludes everything for me. Do you have other entries in you skip file?

**Comment by martong** [comment]
@gyorb 
Yes. The use case is to analyse only one file.
```
+/home/egbomrt/WORK/CodeCheckerProjects/protobuf/src/google/protobuf/util/field_comparator.cc
-/*
```

**Comment by csordasmarton** [comment]
It works for me and it is documented at here: https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/user_guide.md#skip. There is also a warning: `To skip everything use the -* mark. Watch out for the order!`.

We have also introduced a new `file` option for the analyze command which can be used to analyze only the given files from your compilation database. For more information see #2552.
