### ISSUE TITLE
allow skip list to separately specify what should be analyzed and shown

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1525]
The skip list currently controls which files should not be analyzed and shown in the result set.
for example
```
+/module1/a.c
-/module1/*
```
means that only `a.c` will be analyzed and the results only from `a.c` will be shown.

However it may be possible in case of CTU analysis, that a report report starts out from `a.c`  ends in `b.c`, and we would like to see these findings too.

Therefore  it is proposed to let the users to control the analysis and the result rendering separately:

```
{
analyze:[
"+/module1/a.c",
"-/module1/*"]
parse:[
"+/module1/*"]
}
```

With the proposed format only `a.c` will be analyzed, but results that end in other files than `a.c` under `module1` will also be shown.

It is also proposed to change the skip list format to json.

The old skip list format shall also be accepted due to backward compatibility.

**Comment by Xazax-hun** [comment]
I think this is error prone and in case this list is not maintained, it could do more harm. Maybe we should always generate the statistics and ASTs for all files?

**Comment by csordasmarton** [comment]
You can use two separate skip files for analyze and parse.
