### ISSUE TITLE
Parse and display notes from the plist output

### ISSUE THREAD

**Issue by Szelethus** [Ericsson/codechecker#1539]
Notes have recently been added to the CSA's plist output. If this is done, the `-analyzer-config notes-as-events=true` flags should be removed from the default parameters.
Phabricator link: https://reviews.llvm.org/D45407

**Comment by Xazax-hun** [comment]
Note that, this will only be available after clang 7 is released.

**Comment by Szelethus** [comment]
Ping, now that this clang7.0 is out, we should fix this issue.
