### ISSUE TITLE
UncheckedReturnValue works on too small sample set

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#1589]
alpha.ericsson.statisticsbased.UncheckedReturnValue checker calculates statistics even if 1 function call sample is available.

See for example the finding for xerces StringPool.cpp Line 164
```
 addNewEntry(stringData);
-->Return value is not checked in call to 'addNewEntry' (but it should be, based on call statistics)
```

**Comment by gyorb** [comment]
@whisperity this configuration parameter is set in the statistics collector part in CodeChecker so this should be modified here

**Comment by dkrupp** [comment]
New default value (10) is given by this pull request https://github.com/Ericsson/codechecker/pull/1728
