### ISSUE TITLE
review status is not set

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1647]
1. set a codechecker review comment in the source code
2. store the results (review status is set properly)
3. change the review status in the browser to unreviewed
4. change the review status comment in the source code to something else (or keep the previous)
5. store the reports again
6. review status is not updated in the database

**Comment by csordasmarton** [comment]
@gyorb If the source code of a file hasn't been changed before the store command we do not send that file to the server so we can't change the review status back. If we would like to do so we should send all the project files.

**Comment by gyorb** [comment]
After some discussion we will send the files to the server if they contain a review status comment.
