### ISSUE TITLE
dynamic gcc/g++ compilation flag filtering

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#1747]
Handle gcc/g++ compilation flags dynamically not in the current hard coded lists in the option parser.
CodeChecker should get the supported compilation flags from the clang compiler used for analysis 
and filter out the gcc/g++ flags which are not available in clang.

The available compilation flags from clang can be listed with these commands:
```
  clang --help  
  clang --cc1 --help
```

Compilation flags passed to various build stages should be skipped or forwarded in a proper format:
```
  -Xanalyzer <arg>        Pass <arg> to the static analyzer
  -Xassembler <arg>       Pass <arg> to the assembler
  -Xclang <arg>           Pass <arg> to the clang compiler
  -Xlinker <arg>          Pass <arg> to the linker
  -Xpreprocessor <arg>    Pass <arg> to the preprocessor
```

**Comment by dkrupp** [comment]
Clang does not list its parameters precisely enough to be used in automated parameter filtering.
