### ISSUE TITLE
Runtime failure on archlinux

### ISSUE THREAD

**Issue by iamsergio** [Ericsson/codechecker#1775]
Following the exact instructions, on archlinux I get:

$ CodeChecker check -b make -o ~/result
Traceback (most recent call last):
  File "/home/test1/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 20, in <module>
    from shared.ttypes import RequestFailed
  File "/home/test1/codechecker/build/CodeChecker/lib/python2.7/gencodechecker/shared/ttypes.py", line 9, in <module>
    from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
ImportError: cannot import name TFrozenDict

$ thrift --version
Thrift version 0.11.0

According to the Linux requirements this thrift version should work ?

**Comment by Xazax-hun** [comment]
The documentation is not great about this detail but which thrift version is installed in your pip environment? It should match the thrift compiler version that is installed in your system.
Could you check if you can get it work with matching versions?

**Comment by iamsergio** [comment]
I don't know much about python, but I randomly edited requirements_py/requirements.txt and the error is gone ;)

It's now slowly running, but clangsa is taking 3 minutes per translation unit. Is there a way to use more cores ?

**Comment by iamsergio** [comment]
thanks @whisperity, that worked!
