### ISSUE TITLE
Multiple configuration option for the same checker

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#1791]
Multiple configuration options are given for the same checker:
https://github.com/Ericsson/codechecker/blob/53c1d55dae1600d5290f369129b1ade37e02c47e/config/config.json#L21

https://github.com/Ericsson/codechecker/blob/53c1d55dae1600d5290f369129b1ade37e02c47e/config/config.json#L31

One of them has to be removed.

By the way, ESLint can recognize duplicated keys: https://eslint.org/docs/rules/no-dupe-keys
Can we enable it in Codacy?

**Comment by gyorb** [comment]
It is enabled in codacy and it finds the problems.
