### ISSUE TITLE
--tidy-config checks are ignored by clang-tidy

### ISSUE THREAD

**Issue by irishrover** [Ericsson/codechecker#1798]
**Description**
Any checks passed via `--tidy-config` file or via `.clang-tidy` file are ignored by `clang-tidy` as `CodeChecker` always passes `--checks` to `clang-tidy` while command-line checks override any checks from config files according to `clang-tidy` help.

**CodeChecker version**
6.81

**To Reproduce**
1) Create a file "clang.config" with a content `{ 'Checks': '-*,bugprone-parent-virtual-call'}`.
2) Run `clang-tidy -checks="*" --explain-config --config="$(cat clang.config)"`
(This call is what `CodeChecker analyze ./compile_commands.json --analyzers=clang-tidy -j8 -i SKIP_FILE --tidy-config clang.config --timeout 600 --clean -o ./REPORTS` does)

**Expected behavior**
`--explain-config` prints the `bugprone-parent-virtual-call` check as the only enabled.

**Actual behavior**
`--explain-config` prints all the checks as enabled.

**Desktop**
 - OS: platform independent
 - Browser independent

**Comment by VladAdGad** [comment]
@gyorb any updates?

**Comment by sandroandrade** [comment]
Hi there, any plans ahead to fixing this? It's indeed unfortunate we cannot set clang-tidy checks in a per project basis.

**Comment by csordasmarton** [comment]
@irishrover, @VladAdGad, @sandroandrade I created a patch (#3203) which may solve this problem.

With my solution if the file specified by the `--tidy-config` option contains a `Checks` key or the `Checks` option is specified through the `--analyzer-config` option the `-checks` option will be skipped from the actual clang-tidy analyzer command, so only the checkers what specified in the `Checks` key will be used on analysis.

What do you think?

**Comment by sandroandrade** [comment]
On Mon, Feb 22, 2021 at 10:48 AM Márton Csordás <notifications@github.com>
wrote:

> @irishrover <https://github.com/irishrover>, @VladAdGad
> <https://github.com/VladAdGad>, @sandroandrade
> <https://github.com/sandroandrade> I created a patch (#3203
> <https://github.com/Ericsson/codechecker/pull/3203>) which may solve this
> problem.
>
> With my solution if the file specified by the --tidy-config option
> contains a Checks key or the Checks option is specified through the
> --analyzer-config option the -checks option will be skipped from the
> actual clang-tidy analyzer command, so only the checkers what specified in
> the Checks key will be used on analysis.
>
> What do you think?
>

Hi Márton,

Thanks for handling that. Yes, I'd say that's already enough for having per
project clang-tidy setup. Additionally, checking the existence of a
.clang-tidy (not sure if "take-config-from-directory=true" parameter was
created for that purpose) would be a definitive +1.
<https://github.com/Ericsson/codechecker/issues/3119>

Sandro

**Comment by csordasmarton** [comment]
@sandroandrade Maybe what we can do in this case is when the `take-config-from-directory=true` is set, we will not set the `-checks` parameter at all for the `clang-tidy` call, so the analyzer will get all checkers from the `.clang-tidy` files. How does it sound for you?

**Comment by sandroandrade** [comment]
Yes, looks like a good plan!
