### ISSUE TITLE
Better database cleanups?

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#1834]
I saws a few problems by inspecting a sqlite database after all the runs were deleted:
* Comments and review statuses were not deleted
* The space on the disk was not reclaimed

Note that it is not clear whether it is a good idea to garbage collect review statuses and comments as bugs that are disappeared in one run might rematerialize in the next. It would be great to have an option though (even if only in a form of a command line tool) to purge the comments and review statuses as well. 

For reclaiming the unused disk space we should use the vacuum tool (available both in postgres and sqlite). We should either have a command line tool for reclaiming the unused disk space or run it occasionally automatically. What do you think?

**Comment by whisperity** [comment]
Is this complexity really necessary? In case of Postgres, vacuuming is only a config option on the database to enable `AUTOVACUUM`. As for deleting the stuff from the database properly, there's a command-line tool that already exists for it: `rm`.

**Comment by Xazax-hun** [comment]
Does SQLite have autovacuum? If so, maybe we should just turn it on when we create the SQLite database.

The `rm` command is great if you want to purge *ALL* the runs. But it is not great if you want to purge *SOME* of the runs, with the comments and revision statuses included. Although, I am not sure if users would actually understand the implications (i.e. losing the bug suppressions for future runs originating from the deleted run and unused at the moment of deletion).

**Comment by gyorb** [comment]
Comments and review statuses are not deleted by design. As you already mentioned if a report is found again in a later or other run the previous user comments will be available again which can be a valuable information.
For SQLite I think we did not give too much thought about it because SQLite is not meant to be used as a long running production database for projects.

**Comment by csordasmarton** [comment]
We do some database cleanups but we do not want to remove comments and review statuses.
