### ISSUE TITLE
WebUI unresponsive when session expires

### ISSUE THREAD

**Issue by mblythe86** [Ericsson/codechecker#1835]
**Describe the bug**
When using authentication on the CodeChecker server, webUI sessions will expire after a configurable amount of time.  If the session expires while a user still has the webUI open, it will become unresponsive instead of redirecting the user back to the login page.

**CodeChecker version**
6.8.1

**To Reproduce**
1. Start the CodeChecker server with authentication enabled (I used LDAP, but it's probably the same for everything)
2. open the WebUI and log in
3. leave the page to sit idle until the session expires
4. attempt to interact with the WebUI, especially opening a new run or report, etc.  Observe that nothing happens (or a loading icon will spin indefinitely).

**Expected behavior**
I'd expect the WebUI to prompt the user to log in again.

**Desktop (please complete the following information)**
 - OS: server running on Linux, browser running on Win 10.
 - Browser: Firefox
 - Version: 63.0.3

**Comment by csordasmarton** [comment]
This has been fixed in #2057.
