### ISSUE TITLE
Correct way to convert clang-tidy .rst to .md correctly rendered by CodeChecker

### ISSUE THREAD

**Issue by irishrover** [Ericsson/codechecker#1857]
I'm trying to convert all the clang-tidy checks docs from .rst into .md compatible with CodeChecker markdown renderer (https://github.com/markedjs/marked).

All available .rst files for clang-tidy can be found here: https://github.com/llvm-mirror/clang-tools-extra/tree/master/docs/clang-tidy/checks

I apply pandoc this way: 

`> pandoc -t markdown_github -o bugprone-use-after-move.rst.md  bugprone-use-after-move.rst`

The result looks OK, but a bit simplified. What's the correct way to do this? Thanks.

**Comment by gyorb** [comment]
Hi, I did not try to convert them yet, but we do not use the github style markdown for the documentation.
Did you try without giving any specific markdown type or with some other types (commonmark, markdown, markdown_strict)
There is an [example file](https://github.com/Ericsson/codechecker/blob/5363e384627befa42ed58b8dd9a9b7c6eb225ba3/docs/checker_docs/core_division_by_zero.md) but it was written long time ago by hand.
What was not converted properly? Maybe something can be fine tuned on the markedjs side too where the html page is rendered.

**Comment by irishrover** [comment]
Hi. 
It's how rendered markdown_github is shown in a real browser and in CodeCheckere "Show Documentation" popup:

![Browser](https://user-images.githubusercontent.com/3619202/51426973-abd6bc80-1c02-11e9-8272-186188881035.png)

![PopUp](https://user-images.githubusercontent.com/3619202/51426972-ab3e2600-1c02-11e9-8a8e-3a7331f2ad23.png)

**Comment by gyorb** [comment]
We can enable syntax highlight for the documentation too  #1859
