### ISSUE TITLE
profile name conflict with checker or checker group name

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2056]
If I try to list the `portability` checkers I get this error, we should think about the profile naming or handle this differently. The same applies for the new `security` profile.
```
CodeChecker checkers --profile portability
[ERROR 2019-04-10 14:58] - Profile name 'portability' conflicts with a checker(-group) name.
[ERROR 2019-04-10 14:58] - Please choose another profile name in '....config/config.json and rebuild.
```

**Comment by gyorb** [comment]
#2058 solves the problem of the listing but we should discuss the handling/priority of the profiles compared to the checkers and checker groups.

How can I enable the `security` or `portability` checker group, not the profile on the command line?

**Comment by bruntib** [comment]
I think we could choose from these options (feel free to extend the list):

- Profile name should be the default. If the user needs a checker group then he or she needs to use the dot or dash character which is the part of the checkers' names. The logic behind this is that for checker names a name prefix is needed. So `-e security` enables the profile and `-e security.` or `security-` enables checker groups depending on whether StaticAnalyzer or ClangTidy group is meant.
- We could force the users using some prefix when he or she needs to enable a profile: `-e Profile:security` vs. `-e security`.
- In a perfect world the `security` profile and `security` checker group should contain the same set of checkers. Why do we have `security` or `portability` profile at all? Profiles shouldn't be thematic but severity based such as `default`, `sensitive` or `extreme`.

Personally I vote on the 3rd option. We always have debates on what checkers should be included in specific profiles. And any other option which allows checker groups and profiles with the same name will choose one of them by default and it will never be obvious which one it is.

**Comment by gyorb** [comment]
This issue is connected to #2383
