### ISSUE TITLE
--ignore skipfile does not filter anything in parse command with HTML format

### ISSUE THREAD

**Issue by hpwxf** [Ericsson/codechecker#2077]
**Describe the bug**
Option `--ignore skipfile` does not filter anything in parse command with HTML format.
Without HTML format, the filtering is ok.

**CodeChecker version**
Base package version | 6.10.0
Package build date   | 2019-04-16T13:40
Git commit ID (hash) | 9b7e4bd73594f1094a4366c4a596cf792d3e71e2
Git tag information  | 6.10

**To Reproduce**
Steps to reproduce the behavior
1. Using a `SkipFile` which filters everything (e.g.: `-/*`)
2a. Run `CodeChecker parse  -i SkipFile -o ./report -e html ./results`
3a. Execution summary reports all defects
whereas
2b. Run `CodeChecker parse  -i SkipFile -o ./report ./results`
3b. Execution summary reports no defect (all files filtered as expected)

**Expected behavior**
An HTML report where files have been filtered according to `SkipFile` content

**Desktop (please complete the following information)**
 - OS: Linux (Ubuntu 18 in Docker)

**Comment by csordasmarton** [comment]
This problem was resolved in #2089 so I will close this issue.
