### ISSUE TITLE
fix pylint unused-argument warnings

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2081]
W0613 - Warns when a function or method argument is not used.

**Comment by Kishore-abhimanyu** [comment]
can you assign me this issue?

**Comment by Kishore-abhimanyu** [comment]
I don't see this warning, do you want me to fix other pylint warnings?

**Comment by gyorb** [comment]
@Kishore-abhimanyu if you checked and there are not such warnings that is great.
This issue can be closed if this rule is checked automatically by pylint during the tests.
Please check how pylint related issue was resolved (by extending the pylintrc files) in #2082

**Comment by bruntib** [comment]
#4279
