### ISSUE TITLE
fix pylint unused-wildcard-import warnings

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2082]
W0614 - Warns when an imported module or variable is not used from a 'from X import *' style import.

Only import what is used.

**Comment by TheDatumGirl** [comment]
Hi @gyorb 

[Assumption : by wildcard imports you mean import * ] 

I was looking into this and I noticed a few things as below : 
1. As per my noob checking, the codebase doesn't have any such wildcard imports , apart from the below in Contributiing.md : 
> from codeCheckerDBAccess.ttypes import *
So adding an enable in our .pylintrc should be enough. 
2. Also the above API imports mentioned in CONTRIBUTING.md seem obsolete , since most of the codebase actually uses the below standard : from codechecker_api.codeCheckerDBAccess_v6 import codeCheckerDBAccess

These might be wrong insights and any guidance from you on this would be great :)

**Comment by gyorb** [comment]
Hi @meghajain-1711,

Yes I meant that the module contents should not be imported like this `import *`.

1.
If there is no such import that would be great we try to avoid it.
The issue is still open because this pylint warning is not checked automatically, there are multiple pylintrc files (for CodeChecker and the smaller tools) which could be extended with the `unused-wildcard-import` rule so they are automatically checked by travis or in the development environment with the `make pylint` command.
```
./tools/codechecker_report_hash/.pylintrc
./tools/report-converter/.pylintrc
./.pylintrc
./analyzer/tools/statistics_collector/.pylintrc
./analyzer/tools/merge_clang_extdef_mappings/.pylintrc
```

2.
Yes the example in the contribution guide is a bit outdated because there was a bigger refactoring for the api modules and we forgot to update the documentation. The modules are not imported like that anymore and update there would be great too, with the example you mentioned.

Do you plan to work on this?

**Comment by meghajain-1711** [comment]
I would love to work on it , if you could please assign it to me :) 

Thanks a ton for your clarification and guidance !

**Comment by gyorb** [comment]
No problem let us know it you have further questions!

**Comment by meghajain-1711** [comment]
Thanks @gyorb ! No issues as such, I have updated the pylintrc and contributing docs in my workspace , will be opening a PR soon. 
I did not find relevant documentation related to how to test these. 
Even though I found this sample json : tools/report-converter/tests/unit/pylint_output_test_files/simple.json.

Kindly guide me to any testing documentation that I might have missed,

**Comment by gyorb** [comment]
There are multiple make targets which you can execute in the top of the repository during the development. There is a short guide for the [test targets]( https://github.com/Ericsson/codechecker/blob/master/docs/tests.md). Probably the test and/or the contribution guide could be extended with the `make pylint` and `make pycodestyle` targets. Those should be executed first during development, however the other test targets like `test_analyze` execute them before actually executing the other tests so they are not left out.

After updating the pylintrc files you can execute the `make pylint` command which will only execute pylint on the repository and report if there are any warnings.

The file you mentioned `tools/report-converter/tests/unit/pylint_output_test_files/simple.json` is just a test file for the pylint report converter. Multiple analyzer and linter outputs can be converted to be stored to the web server.

**Comment by meghajain-1711** [comment]
Hi @gyorb , 

Thanks for all your guidance. 
I have updated the pylintrc as we discussed above, tested it and submitted a pullrequest. 

I am creating a separate commit with documentation updates :
1. Contributing.md has API reference updated
2. Updating make pylint and make pycodestyle in contributing.md and test docs

Hope thats fine :)

**Comment by gyorb** [comment]
Hi @meghajain-1711,

Thanks for your contribution!
Yes, two separate commits with the changes you mentioned would be great.
