### ISSUE TITLE
add support to enable Z3 Theorem Prover

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2087]
Add support to enable the [Z3 Theorem Prover](https://github.com/Z3Prover/z3) if it is available during analysis.

This option is only available for the clang static analyzer.
If we choose to extend our top level command line with it, it should be under
the clang static analyzer flags like ctu.

We should give some warning to the user if Z3 is enabled on the command line but the clang used for analysis is not built with it.

**Comment by Xazax-hun** [comment]
I am not sure if Z3 support is ready for the users as its performance is really bad. But using Z3 for refutation is great and probably should be the default when Z3 support is available.

**Comment by gyorb** [comment]
It will not be turned on by default it will be just an option so the user can experiment with it. Later if the performance is good enough we could enable it by default. We will see.

**Comment by Xazax-hun** [comment]
I see. I just wanted to be sure that there is no misunderstanding and you really wanted to add Z3 support (as in using Z3 as the default constraint solver) rather than adding refutation support (as in using Z3 for cross checking the built in constraint solver for bugs).

**Comment by gyorb** [comment]
For the refutation I think I will create a separate issue. It depends on a clang with Z3 but needs to be enabled with different flags.
