### ISSUE TITLE
Alpha checkers are no longer listed under -analyzer-checker-help since Clang 9.0.0.

### ISSUE THREAD

**Issue by Szelethus** [Ericsson/codechecker#2148]
Once Clang 9.0.0. is out, alpha checkers are no longer listed in -analyzer-checker-help. Clang has to be invoked with the following flags to retrieve the pre-9.0.0. list:
```
clang -cc1 -analyzer-checker-help -analyzer-checker-help-alpha
```
Before migrating to 9.0.0., we need to fix this so `CodeChecker checkers` displays alpha checkers once again.

**Comment by csordasmarton** [comment]
This was implement in #2287.
