### ISSUE TITLE
usability: CodeChecker should not require sourcing init.sh

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#215]
the CodeChecker script itself should source the required environment variables, so that users do not need to source the init.sh manually.

**Comment by bobszi** [comment]
Maybe we could repurpose bin/CodeChecker to be a wrapper shell script that sources init.sh then calls a file that contains the same code bin/CodeChecker currently contains.

**Comment by gyorb** [comment]
Fixed
