### ISSUE TITLE
clang does not support the following gcc parameters

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#221]
this causes the analysis to fail

-maccumulate-outgoing-args
-fno-toplevel-reorder

clang: error: unknown argument: '-fcall-saved-rdi'
clang: error: unknown argument: '-fcall-saved-rsi'
clang: error: unknown argument: '-fcall-saved-rdx'
clang: error: unknown argument: '-fcall-saved-rcx'
clang: error: unknown argument: '-fcall-saved-r8'
clang: error: unknown argument: '-fcall-saved-r9'
clang: error: unknown argument: '-fcall-saved-r10'
clang: error: unknown argument: '-fcall-saved-r11'
clang: error: unknown argument: '-fcall-saved-rdi'
clang: error: unknown argument: '-fcall-saved-rsi'
clang: error: unknown argument: '-fcall-saved-rdx'
clang: error: unknown argument: '-fcall-saved-rcx'
clang: error: unknown argument: '-fcall-saved-r8'
clang: error: unknown argument: '-fcall-saved-r9'
clang: error: unknown argument: '-fcall-saved-r10'
clang: error: unknown argument: '-fcall-saved-r11'

filter these from the build commands

**Comment by startergo** [comment]
When testing:
```
build -p MdeModulePkg/MdeModulePkg.dsc -t GCC5 -a X64

```

Build quits at:
```
Building ... /UDK/MdeModulePkg/Library/DxeCoreMemoryAllocationLib/DxeCoreMemoryAllocationLib.inf [X64]
clang: error: unknown argument: '-maccumulate-outgoing-args'

```

**Comment by csordasmarton** [comment]
@startergo This problem is not a CodeChecker problem, this is related to your project build system configuration. You gave an unknown option to your clang compiler.

**Comment by Xazax-hun** [comment]
I think the argument is that CodeChecker should filter this option as it already does with other options. And I agree.

**Comment by csordasmarton** [comment]
@Xazax-hun We will filter out this option when using the CodeChecker log command and using gcc compiler:
https://github.com/Ericsson/codechecker/blob/6adf0e7e5e8c2630eb11a4f2e3aa66e604b8af4c/analyzer/codechecker_analyzer/buildlog/log_parser.py#L112
By the way in @startergo comment I do not see any CodeChecker command call.
