### ISSUE TITLE
Automatically detect new web deployment and (offer)? reload of browser page

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#2228]
**Is your feature request related to a problem? Please describe.**

When a new version of CodeChecker is released and a server is upgraded, client browsers might still have the old JS deployment cached away, which could subtly break the site.

## Describe the solution you'd like

Detect mismatch of *deployment* version and force flushing of the cache, preferably without manual user interaction. One way could be to change the filenames of the deployed script either in the release itself or transparently by using an URL rewrite in the server.

 1. A web browser opens the landing page. 
 2. A trivial non-changing API call queries the server what is the version/hash/identifier of the web deployment. 
 3. The client loads all the other scripts by including this version/hash in the request.
 4. The server understands the version/hash in the request and rewrites the query &ndash; this way, the files physically in the server's image could still retain `loginView.js` and such names without the ugly hash messing it up.

+1 of this solution could allow better automatic minifying of resources to conserve network.

## Describe alternatives you've considered
MTMT (The Database of Hungarian Academic Publications) on the login page creates a pop-up for the user "A new version of the editor site is available, do you want to load it?" with a Yes/No button. Clicking 'Yes' reloads the page in some manner, I do not have to press `Ctrl`-`R` or similar. (I am unsure about what pressing *No* does... :wink:)

Although an automatic option done e.g. by various big webapps like Facebook would be preferred.

**Comment by gyorb** [comment]
I was thinking to address this issue by setting some cache invalidation time for the browsers, so after some time (1day, few hours?) they will download the js and other files again.
