### ISSUE TITLE
introduce new profile and checker name format for ambiguous naming

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2383]
checker and profile name can conflict.
There is only a warning given now
```
CodeChecker analyze -e security -o reports cmp.json    
[WARNING 2019-10-10 09:51] - Profile name 'security' conflicts with a checker(-group) name.
```

```sh
CodeChecker checkers --profile list
 default
 sensitive
 security
 portability
 extreme
```
```
CodeChecker checkers  |grep security
...
 security.insecureAPI.UncheckedReturn
 security.insecureAPI.bcmp
 security.insecureAPI.bcopy
 ...
```

We should introduce some way for the user to be able to distinguish between the profile and checker names (between analyzers too, they might conflict)

Something like this:
```
CodeChecker analyze -e profile:security -e clangsa:security -e clang-tidy:security ...
```

The warning should be extended with some information and the analysis should not start.

**Comment by bruntib** [comment]
In #2809 there is a suggestion to also include `guideline:` as a prefix which enables checkers belonging to a specific coding guideline rule.
