### ISSUE TITLE
Skip handler must be run before compiler options parsing not after

### ISSUE THREAD

**Issue by irishrover** [Ericsson/codechecker#2396]
**Describe the bug**

Command line options handling is invoked even for skipped files as skip_handler is invoked after the handling, see:
https://github.com/Ericsson/codechecker/blob/master/analyzer/codechecker_analyzer/cmd/analyze.py#L590

vs

https://github.com/Ericsson/codechecker/blob/master/analyzer/codechecker_analyzer/cmd/analyze.py#L630

**CodeChecker version**

```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.11.0                                  
Package build date   | 2019-10-19T13:50                        
Git commit ID (hash) | 93d5cb005ae3efc08fcdf50695d82daaa59d2d03
Git tag information  | 6.11                                    
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.11.0                                  
Package build date            | 2019-10-19T13:50                        
Git commit ID (hash)          | 93d5cb005ae3efc08fcdf50695d82daaa59d2d03
Git tag information           | 6.11                                    
Server supported API (Thrift) | 6.21                                    
Client API (Thrift)           | 6.21                                    
------------------------------------------------------------------------

```

**To Reproduce**

Create a skip file with the only line:

`-*`

and feed it to the CodeChecker when analyzing the large project like Chromium. The preparation will take a lot of time and extra memory.

**Expected behavior**
As all the files are skipped, the preparation is expected to be fast.

**Desktop (please complete the following information)**
 - OS: any

**Comment by gyorb** [comment]
Sorry for the late reply I think the changes in  #2367 modified the behavior.
Do you use `--ctu` for the analysis?

**Comment by irishrover** [comment]
> Do you use `--ctu` for the analysis?

No.
