### ISSUE TITLE
Add a heartbeat and readiness url

### ISSUE THREAD

**Issue by scphantm** [Ericsson/codechecker#2410]
Deploying this in a k8s cluster, you always include in your deployer a liveliness and readiness url.  This is how k8s knows if the pod is running or not.  At the moment, i have to use /Default/index.html as the url for both of them.  problem is that the readiness system pings every 5 seconds.  thats a lot of cpu cycles on the server side serving the full index page simply for the purpose of proving that it can.

Consider adding 2 urls to your base, so it would be something like

localhost:8001/liveness.html
localhost:8001/readiness.html

liveness would simply say the server is running.  it can literally be a completely blank html page served up by simplehttp.  it doesn't need to be any more complicated than that

readiness, i would add a little bit.  This thing is backed by either sqlite or postgres.  So for readiness, i would probably run a simple DB query.  Maybe count the products in the system or something.  but readiness would verify that the system can do a back and forth transaction.

Adding these two shouldn't take much time but it would end up saving a LOT of cpu cycles for us guys running k8s.

**Comment by csordasmarton** [comment]
@scphantm I created a solution for this (see: #2411). What do you think. Is it good for you?

**Comment by scphantm** [comment]
yea, code looks like it will work.
