### ISSUE TITLE
Disable **ALL** Clang diagnostics

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#2418]
**Is your feature request related to a problem? Please describe.**
Sometimes I would like to run an analysis with **strictly** only those things enabled and producing reports that *I* want to enable - e.g. when developing my own checker. However, the implicit enabling of Clang diagnostics really mess checking results up, as one has to always manually delete the reports from the runs (thanks for that feature, BTW.)

**Describe the solution you'd like**
`-d w` or `-d W` or something should work. Something concise that disables all warnings (that are possible to disabled, anyhow).

According to Clang docs, [`-w`](https://clang.llvm.org/docs/UsersManual.html#cmdoption-w) disables every warning.

**Describe alternatives you've considered**
I've tried: `-e w`, `-d w`, `-d W`, `-d weverything`, `-e Wno-everything`, `-d wall`, and various other combination, none of which seem to work.
For some, no extra information is generated, only that the diagnostics are still present. For some, I get that, e.g. `wall is an invalid checker name`.

I've considered doing a run a normal, collecting all reports from `parse`, manually building a list of warnings that were emitted and re-running the analyses with those diagnostics turned off, but thi is not feasible when anything longer than a few minutes per analysis is being done, e.g. SA runs.

On a small example (not on a real Tidy invocation as it's *multiple entire screens* long!) I've tried giving `-w` directly to Tidy, or not giving it, or "enabling the warnings":

For a given dummy code:
```c++
void f(int a, int b, int c) {}
int main(int argc, char** argv) { return argc; }
```

Without giving anything, or giving `-w`:
```
$ clang-tidy -checks=-*,cppcoreguidelines-avoid-adjacent-arguments-of-same-type ./a.cpp
a.cpp:1:8: warning: 3 adjacent arguments for 'f' of similar type ('int') are easily swapped by mistake [cppcoreguidelines-avoid-adjacent-arguments-of-same-type]
void f(int a, int b, int c) {}
       ^
a.cpp:1:26: note: last argument in the adjacent range here
void f(int a, int b, int c) {}
                         ^
```

Giving `-W -Wall -Wextra`:

```
$ clang-tidy -checks=-*,cppcoreguidelines-avoid-adjacent-arguments-of-same-type ./a.cpp -- -W -Wall -Wextra
5 warnings generated.
a.cpp:1:8: warning: 3 adjacent arguments for 'f' of similar type ('int') are easily swapped by mistake [cppcoreguidelines-avoid-adjacent-arguments-of-same-type]
void f(int a, int b, int c) {}
       ^
a.cpp:1:26: note: last argument in the adjacent range here
void f(int a, int b, int c) {}
                         ^
Suppressed 4 warnings (4 with check filters).
```

The 4 warnings auto-suppressed by Tidy are the 3 unused variables (`a`, `b` and `c`) in `f` and the `argv` (unused) in `main`. I'm not sure how I could manually get Tidy to give them out, but the difference between the invocations is visible in this one line.

**Additional context**
Latest CodeChecker release, Clang-Tidy built from upstream. Same behaviour present with pre-built Clang release binaries, so the issue is on CodeChecker's side.

**Comment by whisperity** [comment]
To compare, when viewed on the server's side, the following happens for one particular project:

![Screenshot_20191031_132147](https://user-images.githubusercontent.com/1969470/67946345-74f5f400-fbe1-11e9-9f4d-3cd615ea0c2d.png)

I want to only see my own checker, and no warnings of any sort.

**Comment by csordasmarton** [comment]
@whisperity Did you try the `-d Weverything`/`-d Wno-everything` option:

```sh
CodeChecker analyze -o ./reports ./build.json -d Weverything
```

**Comment by whisperity** [comment]
> @whisperity Did you try the `-d Weverything`/`-d Wno-everything` option:
> 
> ```shell
> CodeChecker analyze -o ./reports ./build.json -d Weverything
> ```

Huh.
Seems like that was the only option I *actually* forgot to try...
