### ISSUE TITLE
Create multiple HTML files from multiple Plist files

### ISSUE THREAD

**Issue by CleanHit** [Ericsson/codechecker#2428]
Can I use this tool to generate (static) **HTML** files from a bunch of **Plist** files. I have some open source licenses that need to be converted to (static) HTML files. I know it's an overkill to use this tool only for this purpose, but I didn't find any other IOS tools for this task.

**Comment by csordasmarton** [comment]
@CleanHit You can use our [plist-to-html](https://github.com/Ericsson/codechecker/tree/master/tools/plist_to_html) tool (which is part of CodeChecker but can be built and run separately) to generate HTML files from multiple plist files or you can use the [`CodeChecker parse`](https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/user_guide.md#parse) command.

```bash
# Use plist-to-html to generate HTML files from plist files.
plist-to-html -o ./html_directory ./plist_directory

# Use CodeChecker to generate HTML files from plist files.
CodeChecker parse -e html -o ./html_directory ./plist_directory
```

**Comment by CleanHit** [comment]
Thank you. So, for the stand alone usage I need to download the content of the /plist_to_html folder and follow the instructions in the `README.md` file, am I right?

**Comment by csordasmarton** [comment]
Yes, you are right.

**Comment by CleanHit** [comment]
@csordasmarton Unfortunately it didn't create the html files. If I understand it correctly, the the script is searching for some specific attributes to parse. None of my `plist` files have **Checker name** or **Number of reports** in them. The `plist` files consist of license descriptions from open source projects for example like yours.

**Comment by csordasmarton** [comment]
@CleanHit This tool can only be used to convert `plist` files which contains diagnostics which were generated by the Clang Static Analyzer or Cppcheck. You can see an [example](https://github.com/Ericsson/codechecker/blob/master/analyzer/tests/projects/macros/macros.plist) in our test suite.

If you have a custom format of plist file you can write a simple python script which would parse and generate a HTML file from each plist file. You can use the [`plistlib`](https://docs.python.org/2.7/library/plistlib.html) library to parse a plist file and you can use [`Template strings`](https://docs.python.org/3.4/library/string.html#template-strings) to generate HTML files from these.
