### ISSUE TITLE
.plist filename collision

### ISSUE THREAD

**Issue by josod** [Ericsson/codechecker#2435]
[case.zip](https://github.com/Ericsson/codechecker/files/3869276/case.zip)

**Source files with equal filename (not path) generates and overwrites the filename.plist result file during analysis step**

Filename hash generation don't include the buildaction directory.

**CodeChecker version**
You can get version info by running `CodeChecker version`:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.10.1                                  
Package build date   | 2019-11-20T13:20                        
Git commit ID (hash) | 76d1ea88faa9467563a7dc1ce28d2b03ee77c5d7
Git tag information  | 6.10.1                                  
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.10.1                                  
Package build date            | 2019-11-20T13:20                        
Git commit ID (hash)          | 76d1ea88faa9467563a7dc1ce28d2b03ee77c5d7
Git tag information           | 6.10.1                                  
Server supported API (Thrift) | 6.20                                    
Client API (Thrift)           | 6.20                                    
------------------------------------------------------------------------

**To Reproduce**
unzip case.zip
./test.sh

**Expected behavior**
What you expected to happen.
...[
INFO 2019-11-20 13:51] - See --help and the user guide for further options about parsing and storing the reports.
[INFO 2019-11-20 13:51] - ----=================----
[INFO 2019-11-20 13:51] - Analysis length: 0.631727933884 sec.
4  <----- EXPECTED   but ACTUAL : 2

i
**Desktop (please complete the following information)**
 - OS: linux
 - Browser NaN
 - Version NaN

**Additional context**
Add any other context about the problem.

**Comment by gyorb** [comment]
Thanks for reporting the problem, we will check it.
