### ISSUE TITLE
log compile commands with absolute paths

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2447]
Introduce environment variable to to convert the relative file paths to absolute during logging.
Source file, include paths ...

If the compile command database contains relative file paths the generated reports (clang, cppcheck) will contain relative file paths too.
After the analysis is done the CodeChecker store command will not know where the files (with relative path) are.

With this change the logged compilation database could be used with other tools to generate the reports with absolute file paths.

Cmake with the `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON ` converts the include paths and source files to absolute (if set correctly in the cmake file)

**Comment by bruntib** [comment]
This is closed by #2479.
