### ISSUE TITLE
CodeChecker analyze and parse fails for non ascii. 

### ISSUE THREAD

**Issue by josod** [Ericsson/codechecker#2454]
**Describe the bug**
CodeChecker analyze and parse fails for non ascii. 
    * Hash code for filename generation fails if filename (or path, e.g., see bug report #2435)) contains non ascii letters.
    * Hash code generation fails when the source file contains non ascii letters.

In python 2.7 string.encode() is defaulted to "Default encoding is the current default string encoding", i.e, ascii. 

Note!
string.encode() is defaulted to  str.encode(encoding="utf-8", errors="strict") in python 3.x

**CodeChecker version**
Base package version | 6.10.1

**To Reproduce**
Build a compile_commands.json for attached case.cpp.txt 
CodeChecker analyze  compile_commands.json  -o out -e extreme
CodeChecker parse out**Expected behavior**
What you expected to happen.

How to fix:
The hashlib.md5(somestring.encode()) str.encode(...) calls in codechecker_common/parse.py  and  analyzers/result_handler_base.py should probably use  utf-8  encodings.

[case.cpp.txt](https://github.com/Ericsson/codechecker/files/3901630/case.cpp.txt)

**Desktop (please complete the following information)**
 - OS: linux

**Additional context**

**Comment by josod** [comment]
Wrong filename in error report,  codechecker_common/parse.py  should have been  codechecker_common/report.py

**Comment by csordasmarton** [comment]
@josod Thank you for catching this bug. I can reproduce this on the following source code:
```cpp
void foo(int z) {
  if (z == 0)
    int x = 1 / z; // °
}

int main() {
}
```
with the following command: `CodeChecker analyze -o ~/reports/ ~/build.json`.

There was multiple places where we forgot to encode the string to utf-8. I created a patch which will solve this problem: #2457.
