### ISSUE TITLE
The database of some product cannot be connected

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#2495]
ON the main product listing page, if you have more than 60 products, when you reload the page some of them randomly fails to connect.

Error message in the webui.
"Failed to connect to the database"

**Comment by csordasmarton** [comment]
@dkrupp I think increasing the [max_connections](https://www.postgresql.org/docs/9.4/runtime-config-connection.html) parameter will solve your problem in case of PSQL.
