### ISSUE TITLE
Comments not updated with system comment about review status change when review status is changed

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#2497]
**Describe the bug**
If the review status is changed, a "system comment" is generated since #2032. However, unless the "report view" is closed and re-opened, or a manual comment is posted, the comment list is not updated and remains empty/how it was before.

**CodeChecker version**
6.11 - 6.22.2

**To Reproduce**
1. Open any report
2. Change review status
3. Open comment view
4. See nothing (or if comments were there previously, see nothing has changed)

**Expected behaviour**
Somehow make sure the comments are re-queried when the comment view is opened / or is open when the GUI knows the user did a change that invoked creation of a comment.

Automatically tell the sidebar to update its contents (incl. the "Comments (n)" number) when review status is changed. We should keep this consistent in future features if we know it'll involve a comment update.

The comments should be queried (or updated) when the user opens the comment view (as it is not open by default). I would personally prefer this: closing and opening the comment "sidebar" should do a query.

One, I think a bit more ugly approach, would be to offer a "refresh" button that refreshes just the comment sidebar.

**Desktop (please complete the following information)**
 - OS: Ubuntu Linux
 - Browser: Firefox
 - Version: 71.0

**Comment by gyorb** [comment]
Yes, with the current UI this is a known behavior the page needs to be reloaded to show the new events.

We can think about how to improve it @csordasmarton ? Maybe connecting the update to some user action on the UI, like what you mentioned open/close the comments view?
