### ISSUE TITLE
Deleting a comment with a non-ASCII char in it throws (non-fatal) exception

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#2499]
**Describe the bug**
If a comment with a non-ASCII char in it is deleted on the Web GUI, a non-fatal exception is thrown in the logger instead of the "comment deleted" log.

**CodeChecker version**
6.11 release

**To Reproduce**
1. Go to a bug.
2. Create a comment with non-ascii stuff in it: `Æ ALTADOON вниспериты óáááááááűűűűŐŐŐŐŐŐ`
3. Click on the trash icon and confirm the deletion.
4. Observe error:

~~~~
Traceback (most recent call last):
  File "/home/whisperity/CodeChecker/python/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/home/whisperity/CodeChecker/python/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/whisperity/CodeChecker/python/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/home/whisperity/CodeChecker/python/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
Logged from file report_server.py, line 1611
~~~~

There is no stack trace and code context into the API handler, and the shown stack trace is near useless.

**Expected behaviour**
Either display the non-ASCII stuff in the log, or print the "normal" `Comment deleted` information, but without a "preview" of the deleted text. It works for ASCII:

~~~~
[INFO 2019-12-17 16:20] - Comment 'blah...' was removed from bug hash 'd41d8cd98f00b204e9800998ecf8427e' by 'Anonymous'.
~~~~

Perhaps like this:

~~~~
[INFO 2019-12-17 16:20] - Comment (with unprintable UTF-8) was removed from bug hash 'd41d8cd98f00b204e9800998ecf8427e' by 'Anonymous'.
~~~~

**Desktop (please complete the following information)**
 - OS: Ubuntu Linux 18.04 LTS
 - Interpreter: Python 2.7.13 (default, Sep 30 2019, 15:44:25) by [GCC 6.3.0] on linux2

**Comment by csordasmarton** [comment]
I tried it with the latest CodeChecker and it does not throw me such an exception. Changing to python3 solved this issue.
