### ISSUE TITLE
Findbugs/SpotBugs support

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2519]
support the conversion of Findbugs and SpotBugs analysis reports to the format which CodeChecker can store

the [report-converter](https://github.com/Ericsson/codechecker/tree/1d855af1d005b45a253637a6fa23cf01fbae9401/tools/report-converter) should be extended to be able to convert the analysis reports to the right format
and generate the report hash if needed.

**Comment by csordasmarton** [comment]
#2535 will support SpotBugs.

**Comment by gyorb** [comment]
The feature is available since 6.12.0
