### ISSUE TITLE
MacOS instructions are missing `virtualenv` requirement

### ISSUE THREAD

**Issue by themightyoarfish** [Ericsson/codechecker#2526]
**Describe the bug**
[The instructions](https://github.com/Ericsson/codechecker#mac-os-x) neglect to mention one crucial step:

```
pip2 install virtualenv
``` 

**CodeChecker version**

1d855af1d005b45a253637a6fa23cf01fbae9401

**To Reproduce**
Steps to reproduce the behaviour:

1. Run command `make venv_osx` in repository root
2. Observe error due to missing `virtualenv` executable

**Comment by csordasmarton** [comment]
@themightyoarfish I checked our [travis](https://github.com/Ericsson/codechecker/blob/master/.travis.yml#L90) configuration file and we are also installing this package on OSX.

It would be great if you could create a patch and extend our [user guide](https://github.com/Ericsson/codechecker/blob/master/docs/README.md#mac-os-x) with your solution :blush:.

**Comment by themightyoarfish** [comment]
Also, the `thrift` command wont be available after following the macos instructions (since its not linked by brew).
