### ISSUE TITLE
analyze store complains about changed header files

### ISSUE THREAD

**Issue by NextDesign1** [Ericsson/codechecker#2563]
**Describe the bug**
I have an svn repository that is checked out, and a parallel build directory that is populated by CMake. I have CMAKE_EXPORT_COMPILE_COMMANDS on, which generates the json compilation commands file. After svn updating my project directory, running cmake in the build directory to regenerate the compilation commands, and adding the changed files to the skip list, I run analyze. This analyzes the .cpp files just fine. The issue is when I try to store the results in the database, I get a `"The following source file contents changed since the latest analysis"` error with the .h files.

My skip list looks like this:
```
+/home/dev/src/file.C
+/home/dev/src/file.h
-*
```

My analyze and store commands are the following:
```
CodeChecker analyze compile_commands.json -o ./reports --verbose info -j 22 -i skip.list --analyzers clang-tidy clangsa
CodeChecker store ./reports --url http://localhost:80/Default --name dev-10 -f
```

**CodeChecker version**

```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.12.0                                  
Package build date   | 2020-02-10T20:50                        
Git commit ID (hash) | 4f24671fbbbdd2818daf9f84d2d3e5b313683c0c
Git tag information  | 6.12                                    
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.12.0                                  
Package build date            | 2020-02-10T20:50                        
Git commit ID (hash)          | 4f24671fbbbdd2818daf9f84d2d3e5b313683c0c
Git tag information           | 6.12                                    
Server supported API (Thrift) | 6.24                                    
Client API (Thrift)           | 6.24                                    
------------------------------------------------------------------------
```

**To Reproduce**
Steps to reproduce the behaviour:

1. `cd project`
2. `svn update`
3. `cd ../build`
4. `cmake .`
5. `vi skip.list`
6. `CodeChecker analyze compile_commands.json -o ./reports --verbose info -j 22 -i skip.list --analyzers clang-tidy clangsa`
7. `CodeChecker store ./reports --url http://localhost:80/Default --name dev-10 -f`

**Expected behaviour**
Either the .h files should be analyzed, or an option should be given to ignore these files on `store`.

**Desktop (please complete the following information)**
 - OS: Ubuntu 16.04
 - Browser: Firefox
 - Version: 68.2.0

**Additional context**
The project is very large, and we don't want to have to build it just so that we can get the compilation json file, so we use CMake to create the file instead. Likewise we need to use incremental analysis, as a full clangsa analysis takes over 9 hours on a 24 thread machine.

**Comment by csordasmarton** [comment]
@NextDesign1 I created a patch which I think will solve your problem: #2566.

**Comment by NextDesign1** [comment]
Thinking about this a bit more, is it perhaps erroring because the other files that depend on this header file haven't be reanalyzed?

**Comment by csordasmarton** [comment]
If a header file changed then every target which depends on this header file should be reanalyzed. Please check the entries in your compilation database before and after the svn update/cmake commands.

**Comment by NextDesign1** [comment]
Do you mean manually, or with `CodeChecker check`?

If we do compile the project in order to figure out the what has changed between builds, what happens if the build fails? If we svn update again, and run log again, won't we lose the contents of the compilation commands file from the previous failure?

**Comment by csordasmarton** [comment]
For now CodeChecker supports 2 ways for incremental analysis:

1.) **Using incremental build**
The `make` command only re-compiles the changed source files. You can generate a compilation database which will contain targets that changed by using the following command:
```sh
CodeChecker log -b "make" -o compilation.json
```
Note: you can also use the CodeChecker check command to log/analyze and print the reports in one command.

You said your project is very large but this way you don't have to build your whole project only the changed targets will be built.

2.) **Using skip file**
This is what you tried. You need to create a skip file which will tells CodeChecker to analyze only the given source files and skip others. But what if a header file is changed. How do you know which source files depends on this header file?

For more information see our [docs](https://github.com/Ericsson/codechecker/blob/master/docs/usage.md#incremental-analysis).
