### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#2599]
Currently, the version of lxml fixed in the requirement files is too old, it does not support Python 3.8

Bumping the library to its newest release fixes the problem.

**Comment by Krakonos** [comment]
I second this. Python 3.8 is default on Arch linux, so I cannot install codechecker easily. lxml==4.3.5 seems to be enough to install.

**Comment by gyorb** [comment]
yes [4.3.5](https://pypi.org/project/lxml/4.3.5/) was `Rebuilt with Cython 0.29.13 to support Python 3.8.`
I've changed the version to the latest.
