### ISSUE TITLE
clean source from pyflakes errors

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#260]
fix errors fund by pyflakes

**Comment by bruntib** [comment]
In the source code I saw "# NOQA" marks which is the suppression flag of flake8. This is a wrapper of pep8, pyflakes and maybe some other. This tool gives many results for too long lines (over 79 characters), too many blank lines (2), and whitespace problems, such as space before ':', space after '[':
```python
map = {
  'a'   : [ 1, 2, 3 ]
  'abc' : [ 3, 2, 1 ]
}
```
How strict would we like to be?
