### ISSUE TITLE
option to configure the logger for exact binary name match

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2635]
Right now if the logger is configured like this:
```export CC_LOGGER_GCC_LIKE="gcc:g++:clang:cc"```
The logger will match any compilers with gcc,g++ or clang in their filenames.

In some cases this can cause problems because if clang-tidy is executed during the build process
it will be logged too.

We should think about a backward compatible solution to allow the users to log only the binary names with an exact match.
- [ ] introduce a new environment variable `CC_LOGGER_GCC_EXACT_MATCH=True`
  - in this case the current behavior is changed to log only the executed binary if there is an exact 
    match in the name
- [ ] introduce some simple regex or file glob like syntax
  in codechecker the current values can be changed to be backward compatible
  but if there are build systems where the users manually set the CC_LOGGER_GCC_LIKE to 
  some non default values this change in the behavior could cause problems, because the current 
  values will be processed as exact match
  - partial match: `clang*,gcc-*`
  - exact match: `clang,gcc`

**Comment by csordasmarton** [comment]
I think this problem is related to #1687.

**Comment by dkrupp** [comment]
You can achieve exact binary match if you use "/" character before the compiler name, because then codechecker does postfix match.


See
https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/user_guide.md#log-

**Comment by gyorb** [comment]
There is already a solution but the documentation should be updated with these examples.
