### ISSUE TITLE
introduce environment variable to set clang static analyzer plugin directory

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#2643]
Introduce a new environment variable to be able to overwrite the internal config value from where the clang static analyzer plugins are loaded:
`CLANGSA_PLUGIN_DIR`

It should be used only together with the `CC_ANALYZERS_FROM_PATH` environment variable in environments where the config file can not be modified.

This is connected to this change where only the usage was disabled in case of a possible clang static analyzer and plugin mismatch: #2483

**Comment by Xazax-hun** [comment]
What is the main use case for all these environment variables? Why not modify the configs instead?

**Comment by gyorb** [comment]
Hi,

There are build environments where the pre built package is distributed in a read only environment and the user can not modify the config file. Right now the plugin is automatically detected from the package plugin directory and there was no config option to modify that.

**Comment by Xazax-hun** [comment]
I see. In this case wouldn't it be better to be able to have a user specific config in the user's home directory?

**Comment by Xazax-hun** [comment]
I mean config options specific to the package that the user should not change should remain read-only in those cases. But config options interesting to the user should be in the home directory. If someone would make a debian package, the user would have no way to configure CodeChecker, only with environment variables that is suboptimal for the most use cases.

**Comment by dkrupp** [comment]
> I mean config options specific to the package that the user should not change should remain read-only in those cases. But config options interesting to the user should be in the home directory. If someone would make a debian package, the user would have no way to configure CodeChecker, only with environment variables that is suboptimal for the most use cases.

The main use case is the following:

The user does not have root access on the machine where codechecker package is deployed so he cannot change the config file in the package. Imagine that a team of ~100 users would like to use the same settings. Then the configuration would not be different per user, but rather by development team (same config for 100 users). They would set up these config variables by sourcing in team specific environment variables. 

Of course another option would make the location of the (team specific) config file configurable from environment variables. Then we would be left with 1 Env var only

**Comment by dkrupp** [comment]
@csordasmarton I think at least we should describe all environment variable in the in the analyzer and web user guides in a separate section in a list (CC_LOGGER_GCC_LIKE, CC_ANALYZERS_FROM_PATH  etc.).  It is a bit difficult to find now what can be configured from en var exactly.
https://codechecker.readthedocs.io/en/latest/analyzer/user_guide/

**Comment by csordasmarton** [comment]
@dkrupp I already created a patch which will describe the environment variables in the command line helps: #2679.

**Comment by gyorb** [comment]
>@Xazax-hun I mean config options specific to the package that the user should not change should remain read-only in those cases. But config options interesting to the user should be in the home directory. If someone would make a debian package, the user would have no way to configure CodeChecker, only with environment variables that is suboptimal for the most use cases.

I've created a separate issue to further discuss the configuration files #2718
