### ISSUE TITLE
"API call error: massStoreRun RequestFailed(errorCode=2" on storing the data

### ISSUE THREAD

**Issue by irishrover** [Ericsson/codechecker#2659]
**Describe the bug**

Storing fails with 

```
[DEBUG][2020-03-30 20:08:30] {system} [104994] <140698457040704> - webserver_context.py:198 get_context() - Loading layout config.
[DEBUG][2020-03-30 20:08:30] {system} [104994] <140698457040704> - webserver_context.py:202 get_context() - /home/zzz/codechecker/build/CodeChecker/config/package_layout.json
[ERROR][2020-03-30 20:09:08] {system} [104994] <140698457040704> - thrift_call.py:54 wrapper() - API call error: massStoreRun
RequestFailed(errorCode=2, message="'/home/zzz/Documents/chromium/src/chrome/services/sharing/webrtc/p2p_socket_client_delegate.h'", extraInfo=None)
```

on 

`CodeChecker store ./ALL_REPORTS/ --name chrome --trim-path-prefix $(readlink -f $PWD/../../)  --verbose=debug  --url http://localhost:8000/Default
`

And no actual store is done.

**CodeChecker version**
```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.12.0                                  
Package build date   | 2020-03-29T16:30                        
Git commit ID (hash) | 9e33f21258f67f6426dcd30cf426e9bdeb6187b1
Git tag information  | 6.12                                    
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.12.0                                  
Package build date            | 2020-03-29T16:30                        
Git commit ID (hash)          | 9e33f21258f67f6426dcd30cf426e9bdeb6187b1
Git tag information           | 6.12                                    
Server supported API (Thrift) | 6.26                                    
Client API (Thrift)           | 6.26                                    
------------------------------------------------------------------------

```

**To Reproduce**

Run on Chromium sources:

`CodeChecker analyze ./chrome_compile_commands.json -j$(nproc) -i SKIP_FILE --timeout 600 -o $REPORT_DIR `

Well, $REPORT_DIR is 2Gb+ and there're about 20K files in it. But few month ago it was working fine.

**Expected behaviour**
Successful store.

**Desktop (please complete the following information)**
 - OS: Linux Ubuntu 19
 - Browser: any
 - Version: Linux ubuntu 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
I tried to run the web-server both via docker and as a regular script in a console with the same result.

**Comment by irishrover** [comment]
It works for smaller REPORT_DIR, but fails for the large.

**Comment by csordasmarton** [comment]
@irishrover Is there any error log on the server side?

By the way I think you can not upload such a big report directory. The limit is set to 1GB:
https://github.com/Ericsson/codechecker/blob/2b19e65cf354e0d743f9482c242d7c5549f8fe80/web/client/codechecker_client/cmd/store.py#L41

**Comment by irishrover** [comment]
Thanks for your fast reply.

I tried to increase this limit by 5 times - it did not help.

The last lines in the server log:

```
[DEBUG][2020-03-31 09:18:26] {server} [109341] <139752832780032> - report_server.py:2516 __store_reports() - Parsing input file 'distiller_url_fetcher.cc_clangsa_26f258a697699ccd63af8a209b80863d.plist'
[DEBUG][2020-03-31 09:18:26] {report} [109341] <139752832780032> - plist_parser.py:131 parse_plist_file() - Parsing plist: /tmp/tmpzxi3sfck/reports/distiller_url_fetcher.cc_clangsa_26f258a697699ccd63af8a209b80863d.plist
[DEBUG][2020-03-31 09:18:26] {server} [109341] <139752832780032> - report_server.py:2516 __store_reports() - Parsing input file 'ipc_packet_socket_factory.cc_clangsa_aa7289cfd7848528dfc273567a117d25.plist'
[DEBUG][2020-03-31 09:18:26] {report} [109341] <139752832780032> - plist_parser.py:131 parse_plist_file() - Parsing plist: /tmp/tmpzxi3sfck/reports/ipc_packet_socket_factory.cc_clangsa_aa7289cfd7848528dfc273567a117d25.plist
[WARNING][2020-03-31 09:18:27] {server} [109341] <139752832780032> - report_server.py:141 wrapper() - '/home/zzz/Documents/chromium/src/chrome/services/sharing/webrtc/p2p_socket_client_delegate.h'

```

**Comment by gyorb** [comment]
Are there any reports stored or nothing can be seen on the server?

If you run a local parse on the report directory is that successful? `CodeChecker parse`
It will take some time for a report directory this large.
It could produce some file errors (missing, wrong encoding..) maybe with some more information.

It can be worth to check the content and the encoding of this file `../webrtc/p2p_socket_client_delegate.h`

**Comment by csordasmarton** [comment]
I tried it and I was able to store a report directory which size is `2,9G`and it contains 553 files. I am using Ubuntu 18.04.2 LTS and I used SQLite database.

If you are using PostgreSQL please check the database logs. Maybe it contains some errors.

As I see from your logs the error came after parsing `ipc_packet_socket_factory.cc_clangsa_aa7289cfd7848528dfc273567a117d25.plist` file. Could you please share this file with us?

Is this file exists on your machine: `/home/zzz/Documents/chromium/src/chrome/services/sharing/webrtc/p2p_socket_client_delegate.h`

What is the content of your skip file? Could you please share it with us? Is it contains `p2p_socket_client_delegate.h` file?

Is it also possible for example if you are using nginx above the servers that the client will send the zip file to the server but it will take too much time for the server to process the zip file and nginx will timeout your request.

**Comment by byterazor** [comment]
Hi there,
i have the same problem running the current master branch of codechecker. Same error message. Looking at the code at report_server.py line 141, it is obvious that there was an exception thrown but wihtout any helpful exception message.
Running CodeChecker parse locally works fine, but storing is not working.
The error is happening in my jenkins build as well as on my local machine.

My codechecker results directory is 180kb and contains 17 files.

hope this can be fixed :) 

thank you and best regards
 Dominik

**Comment by csordasmarton** [comment]
@byterazor Could you please share with us your plist file on which this failure occured: reports/Track.cpp_clangsa_05cd95ecad569a50d2b9f23beaaefaf8.plist.

Also we moved to Python3. Python2 is no more supported. The minimal required Python3 version is 3.6. Old virtual environments needs to be removed! See my other comment: https://github.com/Ericsson/codechecker/issues/2656#issuecomment-605886695

**Comment by byterazor** [comment]
> reports/Track.cpp_clangsa_05cd95ecad569a50d2b9f23beaaefaf8.plist.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>clang_version</key>
        <string>clang version 9.0.1-10 </string>
        <key>diagnostics</key>
        <array/>
        <key>files</key>
        <array>
                <string>/home/dmeyer/Programmieren/FTEWA/libcms/src/Track.cpp</string>
                <string>/home/dmeyer/Programmieren/FTEWA/libcms/include/CMS/Track.hpp</string>
        </array>
</dict>
</plist>

I am using the latest python available on debian bullseye

**Comment by byterazor** [comment]
> @byterazor Could you please share with us your plist file on which this failure occured: reports/Track.cpp_clangsa_05cd95ecad569a50d2b9f23beaaefaf8.plist.
> 
> Also we moved to Python3. Python2 is no more supported. The minimal required Python3 version is 3.6. Old virtual environments needs to be removed! See my other comment: [#2656 (comment)](https://github.com/Ericsson/codechecker/issues/2656#issuecomment-605886695)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>clang_version</key>
        <string>clang version 9.0.1-10 </string>
        <key>diagnostics</key>
        <array/>
        <key>files</key>
        <array>
                <string>/home/dmeyer/Programmieren/FTEWA/libcms/src/Track.cpp</string>
                <string>/home/dmeyer/Programmieren/FTEWA/libcms/include/CMS/Track.hpp</string>
        </array>
</dict>
</plist>
```
i am using the latest python available in Debian bullseye

**Comment by csordasmarton** [comment]
@byterazor @irishrover I think I found the problem. I created a patch for it. It would be great if you could try it out: #2666.

**Comment by irishrover** [comment]
> @byterazor @irishrover I think I found the problem. I created a patch for it. It would be great if you could try it out: #2666.

Yes, it helps! Thanks a lot!

PS
Sorry for the long delay with the answer. Do you still need any files from me?

**Comment by csordasmarton** [comment]
@irishrover No problem. I think your plist file looked the same as posted above, so I don't need any files from you because my patch solved your problem too.
