### ISSUE TITLE
Documentation error: Integrate CodeChecker with Gerrit review

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#2667]
The template scripts links are broken
https://github.com/Ericsson/codechecker/blob/master/docs/jenkins_gerrit_integration.md#template-scripts-

there are no such scripts anymore.

In this section we describe
https://github.com/Ericsson/codechecker/blob/master/docs/jenkins_gerrit_integration.md#execute-shell-

CodeChecker cmd diff \
  -b clangsa_checkers-merge \
  --url your_baseline_url \
  -n cc_reports \
  --new \
  -o html gerrit \
  -e $JENKINS_HOME/userContent/$JOB_NAME/$BUILD_NUMBER

But the -o does not have "html gerrit" parameter??

**Comment by csordasmarton** [comment]
@dkrup This feature was implemented in #2427. It will be available on the next CodeChecker release or in the master branch of the CodeChecker repository.
