### ISSUE TITLE
Deleting many runs based on timestamp no useful entry about the deletes in log

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#2683]
**Describe the bug**
When deleting multiple runs, the normal verbosity logs contain no information about which runs disappeared.

**CodeChecker version**
~~~~
------------------------------------------------------------------------
Kind                          | Version
------------------------------------------------------------------------
Base package version          | 6.11.0
Package build date            | 2019-12-17T02:12
Git commit ID (hash)          | 65a042f1ad0dec5581d54cb13396d201a573c0b2
Git tag information           | 6.11
Server supported API (Thrift) | 6.24
Client API (Thrift)           | 6.24
------------------------------------------------------------------------
~~~~

**To Reproduce**
Steps to reproduce the behaviour:

1. Have some runs stored on a server
2. Execute `CodeChecker cmd del --all-before-time "2020:04:15"` (this was in my case, I wanted all stores from yesterday gone. I had around 190-ish runs.)
3. The client only gets a "Done" message. Not even a count of runs, or the list of what disappeared.
~~~~
whisperity@whispylinux:~$ CodeChecker cmd del --all-before-time "2020:04:15" --url http://localhost:8081/AdjacentArgs
[INFO 2020-04-15 16:44] - Done.
~~~~
4. Check server log and observe:
~~~~
[INFO 2020-04-15 16:44] - 127.0.0.1:53406 -- [Anonymous] POST /v6.24/Authentication
[INFO 2020-04-15 16:44] - 127.0.0.1:53410 -- [Anonymous] POST /AdjacentArgs/v6.24/CodeCheckerService
[INFO 2020-04-15 16:44] - Run 'None' was removed by 'Anonymous'.
~~~~

Run **'None'** was removed.

**Expected behaviour**
Show the names of the runs deleted. On server-side, definitely for traceability and auditing purposes. (This `None` indicates some sort of a conversion or return-value issue serverside.)

In addition, maybe it would be nice to have on the client's side too, but this isn't that severe.

**Comment by csordasmarton** [comment]
This problem was fixed in #2794 which was released in CodeChecker 6.13.0. For this reason I will close this ticket.
