### ISSUE TITLE
Production deployment documentation and server

### ISSUE THREAD

**Issue by killswitch-GUI** [Ericsson/codechecker#2701]
**Is your feature request related to a problem? Please describe.**
When using this project we discovered very limited deployment documentation for production. This includes that the server runs on pythons debugging server. 

**Describe the solution you would like**
We would really like to see a production-grade WSGI setup such as uWSGI or guinicorn so we could deploy behind a NGINX or any other production-grade web server. 

**Describe alternatives you have considered**
After a deeper look, it seems that the web server used is SimpleHTTP which has a slew of issues. We considered trying to set this up our self.

**Additional context**
If we are missing the docs or missing the right way please let me know and I'm sorry for opening this up.

**Comment by csordasmarton** [comment]
@killswitch-GUI We have a [short documentation](https://github.com/Ericsson/codechecker/blob/master/docs/web/docker.md) how you can run a CodeChecker web server in docker. You can also find a couple of docker compose yaml example file [here](https://github.com/Ericsson/codechecker/tree/master/web/docker/services).

I have also updated, refactored and extended this documentation a little bit: #2713. This patch also contains an example how you can deploy our server in a docker swarm and by using nginx.
