### ISSUE TITLE
CodeChecker crashes when not providing PATH to clang

### ISSUE THREAD

**Issue by Lw-Cui** [Ericsson/codechecker#2775]
**Describe the bug**
I find CodeChecker has an awesome feature that when user doesn't give clang PATH, it will try to parse something like clang-9 to obtain the path itself. However, in some case it will crash.

**CodeChecker version**
```
---------------------------------------------------------------
Kind                 | Version
---------------------------------------------------------------
Base package version | 6.13.0
Package build date   | 2020-06-05T17:46
Git commit ID (hash) | 913834de189d91d9f2eee5c9c9ba8f3d5394129c
Git tag information  | 6.13
---------------------------------------------------------------
```

**To Reproduce**
Steps to reproduce the behaviour:

Don't provide the PATH.

**Expected behaviour**
Run as normal.

**Desktop (please complete the following information)**
Linux

**Additional context**
This function
https://github.com/Ericsson/codechecker/blob/420f115aca59800324e06f889d1388bd8b8b009b/analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py#L295

may return false, and this value is used in 
https://github.com/Ericsson/codechecker/blob/913834de189d91d9f2eee5c9c9ba8f3d5394129c/analyzer/codechecker_analyzer/host_check.py#L111

then CodeChecker crashes because boolean can't be joined with string.

**Comment by gyorb** [comment]
If I understand it right if there is no clang binary in the PATH (no clang or clang-9) so nothing is found it will thrown an exception?

**Comment by whisperity** [comment]
Does not happen with 6.23 in PyPI, likely was fixed sometime since the issue was posted.
