### ISSUE TITLE
ldlogger always built 32 bit

### ISSUE THREAD

**Issue by crockeea** [Ericsson/codechecker#2790]
**Describe the bug**
This was reported in #2095, but is still not fixed.

At line ~86 of the ld-logger Makefile, the executable is always built for 32 bit. This causes problems on 64 bit build hosts that do not have 32 bit dev environments installed.

**CodeChecker version**
Current master

**To Reproduce**
obtain current master
ensure build host does not have 32 bit dev environment
make package
observe quiet build failure in ldlogger

**Expected behaviour**
Build.

**Desktop (please complete the following information)**
Originally reported on OS: CentOS Linux release 7.3.1611 (Core)
I'm also experiencing the problem in Ubuntu 18.04

**Additional context**
Removing -m32 seems to solve the problem for me.

**Comment by gyorb** [comment]
@crockeea thanks, for re-opening the ticket.
 #2796 should fix the problem, I've tested it on my machine, could you check if it fixes the problem on your build environment too?

**Comment by crockeea** [comment]
Looks like this fixes the bug for me. I appreciate the quick fix.

One thing that can still be improved, however: if I don't have 32-bit libraries and follow the build instructions in the README, (just `make package`), the build fails without a clear reason. Even though I figured this out when I first installed a week ago, I made the same mistake when checking your PR. It's easy to miss, and hard to debug.

**Comment by gyorb** [comment]
@crockeea I've added some extra error messages, could you check if it works on your machine too and if they are clear enough?

**Comment by crockeea** [comment]
Looks much nicer @gyorb. I got the error
"Failed to compile logger for 32bit and 64bit targets please check if
gcc-multilib is installed if both targets are needed or set the
BUILD_LOGGER_64_BIT_ONLY=YES environment variable for a 64bit only build.", which I think is adequately clear. I'd be happy to see this PR merged as-is.

I suppose for another ticket, you might consider whether the *default* should be BUILD_LOGGER_64_BIT_ONLY=YES, and make the user specify if they also want a 32-bit build. Do many people build this tool for 32-bit machines?

**Comment by gyorb** [comment]
I would not change the default value yet, with the 32bit and 64bit mode more build environments can be logged (even mixed build environments).
But yes maybe later it can be changed to 64bit only by default.
