### ISSUE TITLE
Android A10 build with codechecker is failing

### ISSUE THREAD

**Issue by wizwin** [Ericsson/codechecker#2916]
**Describe the bug**
Android A10 build with codechecker is failing

**CodeChecker version**
```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version
---------------------------------------------------------------
Base package version | 6.14.0
Package build date   | 2020-09-03T13:35
Git commit ID (hash) | e1bcd909b7885fd02498fd6bad96eb200882ed8c
Git tag information  | 6.14
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version
------------------------------------------------------------------------
Base package version          | 6.14.0
Package build date            | 2020-09-03T13:35
Git commit ID (hash)          | e1bcd909b7885fd02498fd6bad96eb200882ed8c
Git tag information           | 6.14
Server supported API (Thrift) | 6.30
Client API (Thrift)           | 6.30
------------------------------------------------------------------------

```

**To Reproduce**
**1.** Configure clang from the following path:
```
LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1​

"analyzers": {​
    "clangsa": "/build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang",​
    "clang-tidy": "/build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang-tidy"​
},
```
**2.** Perform build from LA.UM.8.2/LINUX/android/ using a script file with the following commands (so env is setup correctly):
```
Contents of ./cbuild.sh
------------------------------------------------------------------------
export _JAVA_OPTIONS="-Xmx4g"
export CC_LOGGER_DEBUG_FILE="/home/directory/CodeChecker/codechecker.debug.log"

cd LA.UM.8.2/LINUX/android/

source ./build/envsetup.sh
choosecombo 1 <product name> 2 1
make -j10
------------------------------------------------------------------------

$ CodeChecker check -b "./cbuild.sh" -o /build/Projects/results​ --verbose debug
```
**3.** See error
```
error: unknown target triple 'unknown-Bprebuilts/gcc/linux-linux-android-x86/aarch64/aarch64-4.9/aarch64-linux-android/bin', please use -triple or -arch
```

**Expected behaviour**
Clang SA should not fail with the error above.

**Desktop (please complete the following information)**
 - OS: Linux - Ubuntu
 - Browser: Chrome
 - Version: 18.04

**Additional context**
1. Can we use CodeChecker to perform mm or mma and only build modules?
2. Need to understand if CodeChecker is compatible with Android environment. I did not find any documentation that says it is not. 
3. Need a workaround or possible way to fix this issue using a config file or extra arguments if that is already known.

**Comment by wizwin** [comment]
I took this from a clang-tidy run but I assume same applies for clang (SA) as well.

Orignal command (compilation_database.json) :
`-march=armv8-a -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -Wsign-promo`

CodeChecker command (analyzer-command):
`-march=armv8-a -target -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -Wsign-promo`

Are we missing some options or configuration?

**Comment by csordasmarton** [comment]
As I see we get compiler target from the compiler:
https://github.com/Ericsson/codechecker/blob/8809d707acd44e5370e1532610d9f494735df800/analyzer/codechecker_analyzer/buildlog/log_parser.py#L397

@wizwin What is the output of the following command: `clang -v`. Is it contains `Target: <value>` line?

> @bruntib, @gyorb You know more about the log parser then me, could you helps us what can be the problem?

**Comment by wizwin** [comment]
(Clang configured to run from Android prebuilts, We are cross compiling for aarch64)

`/build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang-9 -v`

```
(venv) user@server:~$ /build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang-9 -v
Android (6052599 based on r353983c1) clang version 9.0.3 (https://android.googlesource.com/toolchain/clang 745b335211bb9eadfa6aa6301f84715cee4b37c5) (https://android.googlesource.com/toolchain/llvm 31c3f8c4ae6cc980405a3b90e7e88db00249eba5) (based on LLVM 9.0.3svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

**Comment by wizwin** [comment]
Looks like #2467 addresses a similar issue but here -target is completely missing.

**Comment by wizwin** [comment]
@csordasmarton, @bruntib, @gyorb

Toolchains used in Android A10 build:

**`-target armv7a-linux-androideabi`​**
vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin/clang++​
vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin/clang​

**`-target aarch64-linux-android`​**
LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang-9​

Added some logs and saw sometimes target is blank (not really sure where to put them, since I am not familiar with this code):
```
156262:[DEBUG][2020-09-17 17:51:15] {buildlogger} [30187] <140637137602368> - log_parser.py:1058 parse_options() - wizwin: target -
156263:[DEBUG][2020-09-17 17:51:15] {buildlogger} [30187] <140637137602368> - log_parser.py:965 parse_options() - wizwin: target   - defaultdict(<class 'dict'>, {})
156264:[DEBUG][2020-09-17 17:51:15] {buildlogger} [30187] <140637137602368> - log_parser.py:966 parse_options() - wizwin: arch     -
156265:[DEBUG][2020-09-17 17:51:15] {buildlogger} [30187] <140637137602368> - log_parser.py:967 parse_options() - wizwin: compiler - vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin/clang

```
```
304676:[DEBUG][2020-09-17 18:58:29] {analyzer} [29335] <140637137602368> - analyzer.py:225 construct_analyzer_cmd() - wizwin 5: target ''
304698:[DEBUG][2020-09-17 18:58:30] {analyzer} [29335] <140637137602368> - analyzer.py:225 construct_analyzer_cmd() - wizwin 5: target 'arm-unknown-linux-android'
3
```
These set of logs are present for almost all the files which were analysed by clangsa.

Any ideas or pointers to debug this further?

**Comment by gyorb** [comment]
Hi,

Are multiple clang compiler versions mixed in one build? In the compile command json, some files are compiled with clang8 and some files with clang9 to different targets?

Do you try to use the same clang version for analysis and for compilation?
Which clang is detected and used by CodeChecker in your build environment? You can check it with this command: `CodeChecker analyzers --details`

**Comment by wizwin** [comment]
@gyorb - There are multiple clang compilers involved in Android build (to the best of my knowledge, For building Qualcomm binaries and for Android binaries) however we have setup CodeChecker analyzer to use the one from Android prebuilts directory as mentioned in steps to reproduce. 

```
$ CodeChecker analyzers --details
error: unknown argument: '-analyzer-checker-help-alpha'
error: unknown argument: '-analyzer-checker-help-developer'
 clang-tidy /build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang-tidy LLVM (http://llvm.org/):
  LLVM version 9.0.3svn
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: ivybridge

 clangsa /build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang      Android (6052599 based on r353983c1) clang version 9.0.3 (https://android.googlesource.com/toolchain/clang 745b335211bb9eadfa6aa6301f84715cee4b37c5) (https://android.googlesource.com/toolchain/llvm 31c3f8c4ae6cc980405a3b90e7e88db00249eba5) (based on LLVM 9.0.3svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /build/Projects/A10/LA.UM.8.2/LINUX/android/prebuilts/clang/host/linux-x86/clang-r353983c1/bin
```

With this we are seeing that `-target` is blank and `-B` option next to this argument it is taken as the target, which is not correct.

**Comment by gyorb** [comment]
If you check the debug output `CodeChecker analyze -o reports --verbose debug compile_command.json`, do you see a message like this `Same clang is used for compilation and analysis.`?

**Comment by wizwin** [comment]
I could see the above message (`Same clang is used for compilation and analysis.`) when I changed the clang version to vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin/clang - Pasted in the above comment.

There is no file `compile_command.json` so could not run the command you mentioned. Tried the following:
`$ CodeChecker analyze -o reports --verbose debug /build/results​/unique_compile_commands.json`

```
[DEBUG][2020-09-18 16:11:19] {buildlogger} [32256] <140331504486208> - log_parser.py:1027 parse_options() - Same clang is used for compilation and analysis.
[DEBUG][2020-09-18 16:11:19] {buildlogger} [32256] <140331504486208> - log_parser.py:1058 parse_options() - wizwin: target -
[DEBUG][2020-09-18 16:11:20] {buildlogger} [32256] <140331504486208> - log_parser.py:965 parse_options() - wizwin: target   - defaultdict(<class 'dict'>, {})
[DEBUG][2020-09-18 16:11:20] {buildlogger} [32256] <140331504486208> - log_parser.py:966 parse_options() - wizwin: arch     -
[DEBUG][2020-09-18 16:11:20] {buildlogger} [32256] <140331504486208> - log_parser.py:967 parse_options() - wizwin: compiler - vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/bin/clang++
```

**Comment by gyorb** [comment]
I've made some changes in #2944 about the target handling but I think we will probably need further testing (analyzing some opensource projects) to see if the changes does not cause any other problems.

**Comment by wizwin** [comment]
Sure @gyorb, will test and update the results.

**Comment by wizwin** [comment]
The build was going on without errors for a while with same steps mentioned in the bug. Looks like it just stopped before completion.

` -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -nostdlibinc -march=armv8-a -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin -Wsign-promo `

`-target` is now removed from the analyzer command.

We had tried full android build using CodeChecker and it was successful (analysis was not). Will try again and update.

**Comment by wizwin** [comment]
@gyorb Thank you.

Looks like this issue is fixed. Android A10 incremental build completed successfully.

Still need to investigate:
- Full build
- Impact of using a pre-configured tool chain
- Will it work on build with Android blueprint files
