### ISSUE TITLE
Misleading bug levels

### ISSUE THREAD

**Issue by martong** [Ericsson/codechecker#2922]
We display in our help output that the debug levels are:
```
[--verbose {info,debug,debug_analyzer}]
```
This suggests the following relation between the levels:
```
info > debug > debug_analyzer
```
But the above relation does not hold because we define `debug_analyzer` to be 15, however, info is 20 and debug is 10 (https://docs.python.org/3/library/logging.html)
```
info:20 debug:10 debug_analyzer:15
```

So, users tend to send the most verbose debug output by setting `--verbose=debug_analyzer`, but that simply skips all `debug` logs.

Proposed solution: set debug_analyzer to 5.

**CodeChecker version**
v6.13.0

**Comment by gyorb** [comment]
The levels were created to go from info -> debug_analyzer (only the analysis related log messages) -> debug (everything, analysis and other parts).

The most verbose output should be the debug level. What if we change the order in the help messages?
