### ISSUE TITLE
Server removes reports with the same report hash

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#2952]
Steps to reproduce:
1. step: analyze and store the results to a run:
```cpp
// main.cpp
int main()
{
  sizeof(42);
  sizeof(42);
  sizeof(42);
}
```
2. step: update the file, reanalyze and store the results to the same run:
```cpp
// main.cpp
int main()
{
  sizeof(42);
}
```
In the second case the server will remove reports from the database which have the same report id. So in the database there will be actually one report.

**Comment by gyorb** [comment]
Does the calculated bug path hash influence this, I mean there is no bug path in this case probably so the same bug path hash is calculated for that one report event and it will be the same because the source line is the same in both cases.

**Comment by csordasmarton** [comment]
We handled this problem in #3102.
