### ISSUE TITLE
Comments are not displayed in the Cmd results

### ISSUE THREAD

**Issue by jay24rajput** [Ericsson/codechecker#3005]
**Describe the bug**
I want to export the results from Codechecker Server into JSON format. For doing that, I am using  `cmd results` command as:
```
CodeChecker cmd results smatch -o json 2>/dev/null | python -m json.tool > smatch_out.json
```

The output file( `smatch_out.json`) does not properly export the comment on bugs in Reports stored in `Codechecker server`. Instead of displaying the comment, only an empty string(`""`) is displayed.

Kindly provide pointers to solve this issue

**Comment by gyorb** [comment]
Which type of comments are missing? The user comments added on the web UI, or some other report related comments?

**Comment by jay24rajput** [comment]
The user added comments in the WebUI.

**Comment by jay24rajput** [comment]
Hello @gyorb @csordasmarton 

Here is a detailed explanation of the problem being faced. Kindly have a look and let us know how to proceed with the fix
https://gist.github.com/jay24rajput/c1a55e80b88e0aa6d343823cf102268c

**Comment by csordasmarton** [comment]
Now we have an API function to get comments:
https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/server/codechecker_server/api/report_server.py#L1594
But I don't really recommend us to use this function in the client code to get comments for every reports because it will generate a huge amount of queries towards the server.

A better approach would be I think to handle this problem in the following API function:
https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/server/codechecker_server/api/report_server.py#L1265-L1266
This api function already has a `get_details` parameter and if it's true we can return with the comments too.
This API function calls the following function to get details:
https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/server/codechecker_server/api/report_server.py#L579
We can use this function to return the comments. For this we need to extend the Thrift API stub with a new field:
https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/api/report_server.thrift#L150-L154
```thrift
4: optional CommentDataList comments,
```
And inside the `get_report_details` we will query the data from the database for the given report ids and then set this new field. As far as I see we don't have to modify the client code but only the server side code.

@gyorb  What do you think about this solution?

**Comment by jay24rajput** [comment]
I was trying to debug the codebase of report_server. So just to check if the control is being reached I added: `LOG.info('I came here')` before the following line: https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/server/codechecker_server/api/report_server.py#L632

After which I can the following commands:
```sh
make package
CodeChecker cmd results smatch -o json
```

But I could not see the above mentioned **Info** line in the cmd output. Am I missing out on something or doing anything wrong here? 
@csordasmarton

**Comment by jay24rajput** [comment]
I was just trying to debug the codebase. I added the logging line `LOG.info("I came here")`  before the following line:
https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/server/codechecker_server/api/report_server.py#L632

After this I executed the following commands

### For server
```sh
make package
CodeChecker server
```

### For Command Line
```sh
make package
CodeChecker cmd results smatch -o json
```

I was not able to see the the following line in either of the terminal output. Am I missing something here or doing something wrong? @csordasmarton

**Comment by csordasmarton** [comment]
@jay24rajput You have to use the `--details` options: `CodeChecker cmd results smatch -o json --details`

**Comment by jay24rajput** [comment]
@csordasmarton @gyorb  I have created the code for fetching the comments and as per my testing, the code is fetching the comments properly. I have a print statement just above ReportDetails where you can verify it:
https://github.com/jay24rajput/codechecker/blob/942a51e0b6c936e814f464b05a776c9164650149/web/server/codechecker_server/api/report_server.py#L641

The next task is modifying the ReportDetails class which is actually in the root directory `/home/jay/.local/lib/python3.8/site-packages/codechecker_api/codeCheckerDBAccess_v6/ttypes.py` and not in the `codechecker` directory. Any insights on how to modify this?

Github branch: https://github.com/jay24rajput/codechecker/tree/exporter

Apologies for commits being unformatted, this is still WIP

**Comment by csordasmarton** [comment]
You have to extend the thrift file first: https://github.com/Ericsson/codechecker/blob/master/web/api/report_server.thrift.

In my above comment I mentioned it:
https://github.com/Ericsson/codechecker/blob/525c40af7fdc6e424003bfb791c629d60a70b3b6/web/api/report_server.thrift#L150-L154
You can extend this type with a new field:
```thrift
4: optional CommentDataList comments,
```
We are using these thrift files to generate stubs from it and we upload these stubs to pypi and npm. Now only @gyorb and me have permissions to publish new packages.

If you modified the thrift file, and you think you are done we can create a new pypi/npm packages from your thrift file and you can use it in your repo.

Just let us know if you extended the this thrift file. Unfortunately I don't see any better method for this now.

**Comment by jay24rajput** [comment]
> You can extend this type with a new field:
> ```thrift
> 4: optional CommentDataList comments,
> ```
> 
Yes, I have already done that in my GitHub branch, in `report_server.thrift`. The line where `ReportDetails` is called:
https://github.com/Ericsson/codechecker/blob/986ecf325ec7c88449a0c7019645c45b8579e13b/web/server/codechecker_server/api/report_server.py#L628
 has also been modified to:
```python
ReportDetails(pathEvents=bug_events_list[report_id],
                          executionPath=bug_point_list[report_id],
                          extendedData=extended_data_list[report_id],
                          commentData=comment_data_list[report_id])
```


> We are using these thrift files to generate stubs from it and we upload these stubs to pypi and npm. Now only @gyorb and me have permissions to publish new packages.
> 
> If you modified the thrift file, and you think you are done we can create a new pypi/npm packages from your thrift file and you can use it in your repo.
> 
> Just let us know if you extended the this thrift file. Unfortunately I don't see any better method for this now.

Yes, I think I am done with the logic part. Should I clean up the code/commits and issue a pull request for you to create new pypi/npm packages??

**Comment by csordasmarton** [comment]
@jay24rajput Okay, I have created new pypi and npm packages from your repo. You have to run the following commands to update the versions in your repo:
```sh
# Step into the API directory
cd web/api

# Use the new package.
./change-api-version.sh 6.36.0-dev1

# Build a new CodeChecker package. It will automatically download the new packages.
make clean_package && make package
```

**Comment by jay24rajput** [comment]
That did not seem to work, the file `ttypes.py` located in the root directory(`/home/jay/.local/lib/python3.8/site-packages/codechecker_api/codeCheckerDBAccess_v6/ttypes.py`) still remains unchanged. I also tried the following commands after the commands given by you

```sh
cd web/api

make clean
make 
```

But still, the error persists!

**Comment by csordasmarton** [comment]
Make sure that the versions are updated in the following file to `6.36.0-dev1`:
https://github.com/Ericsson/codechecker/blob/986ecf325ec7c88449a0c7019645c45b8579e13b/web/requirements.txt#L7-L8

After it try to run the following command manually: `pip3 install -r ./web/requirements.txt`

And check that it installed the new packages by using the following command: `pip list  | grep codechecker`

**Comment by jay24rajput** [comment]
Thanks a ton, @csordasmarton! We have resolved the issue!
