### ISSUE TITLE
invalid json produced from command: CodeChecker cmd diff -e tmpdir -o json,html,gerrit

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3022]
The output is a mix of JSON together with the HTML summary.

I see two possible resolutions:
* Either suppress all helper output from stdout (like the html summary) so that the JSON output is clean
* Or store the json output to a default filename when `-e` is provided.

**Comment by gyorb** [comment]
Hi,

The html and gerrit output files are generated into the tmpdir but if you select the json output format too and pipe it into a file
a valid json will be there, the log messages are printed to stderr but the json output to the stdout so they are not mixed together. 
```
CodeChecker cmd diff -e tmpdir -o gerrit -o json --unresolved -b run1 -n run2 > results.json
```

**Comment by jimis** [comment]
I am using 
```--new -e /tmp/tmp.RPIokwom3a -o html gerrit json >blah.json```
and this is outputting the HTML summary text into `blah.json`.

```
----==== Summary ====----
------------------------------
Filename        | Report count
------------------------------
qarraydataops.h |            3
------------------------------
-----------------------
Severity | Report count
-----------------------
HIGH     |            3
-----------------------
----=================----
Total number of reports: 3
----=================----


To view the results in a browser run:
  $ firefox /tmp/tmp.RPIokwom3a/index.html
```

**Comment by gyorb** [comment]
ok, I see now

**Comment by jimis** [comment]
Thanks!
