### ISSUE TITLE
--ctu-collect should not consider --skip

### ISSUE THREAD

**Issue by martong** [Ericsson/codechecker#3065]
**Describe the bug**
`--ctu-collect` should not take `--skip` into consideration, because that can create a misleading/faulty CTU definition map.

**CodeChecker version**
6.15

**To Reproduce**
```
± CodeChecker analyze ./compile_commands.json --analyzers clangsa --ctu-collect --ctu-ast-mode parse-on-demand -o ./reports --skip=./skipfile -j4

[INFO 2020-11-30 14:49] - Enabled checkers:
clangsa: apiModeling.StdCLibraryFunctions, apiModeling.TrustNonnull, apiModeling.google.GTest, apiModeling.llvm.CastValue, apiModeling.llvm.ReturnValue, core.CallAndMessage, core.CallAndMessageModeling, core.DivideZero, core.DynamicTypePropagation, core.NonNullParamChecker, core.NonnilStringConstants, core.NullDereference, core.StackAddrEscapeBase, core.StackAddressEscape, core.UndefinedBinaryOperatorResult, core.VLASize, core.builtin.BuiltinFunctions, core.builtin.NoReturnFunctions, core.uninitialized.ArraySubscript, core.uninitialized.Assign, core.uninitialized.Branch, core.uninitialized.CapturedBlockVariable, core.uninitialized.UndefReturn, cplusplus.InnerPointer, cplusplus.Move, cplusplus.NewDelete, cplusplus.NewDeleteLeaks, cplusplus.PlacementNew, cplusplus.PureVirtualCall, cplusplus.SelfAssignment, cplusplus.SmartPtrModeling, cplusplus.VirtualCallModeling, deadcode.DeadStores, nullability.NullPassedToNonnull, nullability.NullReturnedFromNonnull, optin.cplusplus.UninitializedObject, optin.cplusplus.VirtualCall, optin.portability.UnixAPI, security.FloatLoopCounter, security.insecureAPI.UncheckedReturn, security.insecureAPI.getpw, security.insecureAPI.gets, security.insecureAPI.mkstemp, security.insecureAPI.mktemp, security.insecureAPI.rand, security.insecureAPI.vfork, unix.API, unix.DynamicMemoryModeling, unix.Malloc, unix.MallocSizeof, unix.MismatchedDeallocator, unix.Vfork, unix.cstring.BadSizeArg, unix.cstring.CStringModeling, unix.cstring.NullArg, valist.CopyToSelf, valist.Uninitialized, valist.Unterminated, valist.ValistBase
[INFO 2020-11-30 14:49] - Pre-analysis started.
[INFO 2020-11-30 14:49] - Collecting data for ctu analysis.
[INFO 2020-11-30 14:49] - [1/1] interpreter.cpp
[INFO 2020-11-30 14:49] - Pre-analysis finished.
[INFO 2020-11-30 14:49] - Analysis length: 0.9699645042419434 sec.
```

**Expected behaviour**
Drive through the pre-analysis phase on all TUs.

**Desktop (please complete the following information)**
-all

**Comment by gamesh411** [comment]
I have started to write a test for this.

**Comment by gamesh411** [comment]
Correction.
After consulting with CodeChecker dev team I have the following information:
This behaviour is intentional. If only `--ctu` flag is given (which entails both phases which are enabled by `--ctu-collect` and `--ctu-analyze` respectively) the --skip does not skip file in the pre-analysis phase. However, if only `--ctu-collect` is given, then the --skip is used to signal which TUs collection should be skipped.

**Comment by dkrupp** [comment]
I think this issue can be closed.

**Comment by martong** [comment]
> Correction.
> After consulting with CodeChecker dev team I have the following information:
> This behaviour is intentional. If only `--ctu` flag is given (which entails both phases which are enabled by `--ctu-collect` and `--ctu-analyze` respectively) the --skip does not skip files in the pre-analysis phase. However, if only `--ctu-collect` is given, then the --skip is used to signal which TUs collection should be skipped.

Ok, thanks, makes sense.
