### ISSUE TITLE
--enable/--disable all option

### ISSUE THREAD

**Issue by AlexTelon** [Ericsson/codechecker#307]
To be able to quickly run the tests that you want this would be nice. Right now there is no way to see a nice list of which checkers you have enabled. You have to count them yourself.

**Comment by gyorb** [comment]
Pull requests are welcome!

**Comment by Xazax-hun** [comment]
Clang tidy can list the enabled checkers already. Clang Static Analyzer got this feature however only recently: https://github.com/llvm-mirror/clang/commit/f12ee3b7751a95a6796e65eee39cb8e9ae4b3480

It will be available in Clang 4.0, so strating from clang 4.0 it would be possible to list all of the enabled checkers.
