### ISSUE TITLE
LDAP authenticated users default permissions

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3072]
I have setup LDAP authentication in CodeChecker for our organisation. I want to **give PRODUCT_ACCESS permission to all users for all projects**, so that everybody in the organisation can view and comment on issues.

I see different alternative solutions to this:
- set global or per-project default permission level, or
- enable wildcards in the user permission settings
- create a custom group that includes usernames based on wildcards, for example group "all" that contains `.*`

Please note that there are no useful groups that all users belong to.

**Comment by jimis** [comment]
The only alternative I see now, is to manually give PRODUCT_ACCESS permissions to every user for every project, which will result to thousands of settings. Is there a better alternative that I might be missing?

**Comment by csordasmarton** [comment]
@jimis If there is a global LDAP group (e.g.: your_compary_user), it can be used to add access permission for everybody who are in this group. You have to configure it per product:
![image](https://user-images.githubusercontent.com/6695818/101463090-434f7080-393d-11eb-9fc3-631be3dad1ce.png)

**Comment by jimis** [comment]
@csordasmarton AFAIK there is no such group.

**Comment by jimis** [comment]
Any ideas the suggested solutions to the problem? I could try and implement something, but I would need some guidance, I've looked into how permissions are queried and it goes through many levels of abstraction...

**Comment by jimis** [comment]
I went on and implemented a way to create custom groups, that might contain any user we like, base on regular expressions. Let me know what you think.
