### ISSUE TITLE
Commenting on an issue using quotes results to the error "No closing quotation"

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3092]
I select any issue and mark it as "confirmed", entering a message in the comment box that includes at least a single quote. For example:
```
test
quotes'blah
```

Then I refresh the page and try to expand the comment section on the right hand side. I get a red error box, while on the server console I get:

```
[WARNING][2020-12-10 17:27:21] {server} [1468928] <140291968911104> - report_server.py:145 wrapper() - getComments:
No closing quotation
```

**Comment by jimis** [comment]
My understanding is that this message comes from the `shlex` module as used at:
https://github.com/Ericsson/codechecker/blob/e010bb904cd0469034483df215d5890ea47fc500/web/server/codechecker_server/api/report_server.py#L1616

It seems that the status change of an issue is considered a SYSTEM event, and is expected to have specific form. But the way I'm so far using CodeChecker is to write an arbitrarily long message when I evaluate an issue, which makes it quite possible to include quotes.

Should these long messages be separate comments, and arbitrary comments in status changes be disallowed?

**Comment by csordasmarton** [comment]
@jimis I created a simple patch (#3094) which will solve this problem. Could you please check it?

**Comment by jimis** [comment]
@csordasmarton I don't think it's enough, commented on the pull request. I wonder if it makes sense to avoid using `shlex` module completely, since we are not spawning any sub-shell here.

**Comment by jimis** [comment]
Thanks for fixing the issue!
