### ISSUE TITLE
clangsa false positive: contradictory assumptions about variable

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3093]
As reported at: https://bugs.llvm.org/show_bug.cgi?id=48474

![clangsa_false_positive_spec_is_not_TimeZone - Screenshot_2020-12-10 CodeChecker viewer](https://user-images.githubusercontent.com/3584514/101814108-f8d91a00-3b1d-11eb-8110-b39c7a4d180a.png)

I attach a screenshot from CodeChecker. You can also find the static HTML report at: https://testresults.qt.io/codechecker/daily_analyses/qtbase/dev/qtbase-dev-20201210-238f466d49/qdatetime.cpp_clangsa_fbaaa3c8986c74ae8f6ae431391de560.plist.html#reportHash=62a0d374a5d8f3a09605154ad72cab0d

In this report we see the following assumptions the analyzer makes:

.6) Assuming 'spec' is not equal to TimeZone
[...]
.9) Assuming 'spec' is equal to Timezone (since it follows that branch of the switch statement)

This issue stands out the most, because of the closeness of the contradictory assumptions.

But this report is invalid for other reasons too, for example clangsa fails to track into the Data constructor in line 3048, which would make it evident it can't happen.

**Comment by csordasmarton** [comment]
@jimis This problem is related to the static analyzers (Clang Tidy, Clang Static Analyzer) and not to the CodeChecker. So I will close this ticket.

**Comment by jimis** [comment]
I've opened a ticket both here and in the [LLVM bugzilla](https://bugs.llvm.org/show_bug.cgi?id=48474), since the responsiveness here is much better (people like @martong have helped a lot previously) and I was not sure whether the two projects overlap. Feel free to close though, thanks!

**Comment by martong** [comment]
Thanks for the report. I'd rather track this issue in bugzilla now, because this seems to be unrelated to CTU, so Apple's CSA developers might be more interested. CTU is tightly connected to CodeChecker.
