### ISSUE TITLE
problematic issue report for missing destructor

### ISSUE THREAD

**Issue by KristofSzabados** [Ericsson/codechecker#3095]
**Describe the bug**
We get an issue reported on one of our classes.
Issue: "class 'ASN_NULL' defines a copy constructor and a copy assignment operator but does not define a destructor"
file reported on:  https://github.com/eclipse/titan.core/blob/master/core/ASN_Null.hh

While the report is correct in the sense that there is no explicitly written out destructor in this class, why would that be needed in the first place?
Please note that in C++ if there is no destructor written for a class by the user, the compilers always have to create an implicitly declared destructor.
As this class contains only a single member ("boolean bound_flag;") and that is also nothing complicated, the implicitly declared destructor should be able to handle it properly

**CodeChecker version**
6.15

**To Reproduce**
Steps to reproduce the behaviour:

run codechecker on our project.

**Expected behaviour**
I would expect codechecker to know about implicitly declared destructors and realize, that as this class is very simple, the implicitly declared destructor will work fine.

**Desktop (please complete the following information)**
 - OS: Win10
 - Browser: Firefox
 - Version: 83.0

**Comment by csordasmarton** [comment]
@KristofSzabados This problem is related to the static analyzers (Clang Tidy, Clang Static Analyzer) and not to the CodeChecker. Please create a ticket to the https://bugs.llvm.org/.
