### ISSUE TITLE
problematic issue report for non null-termination

### ISSUE THREAD

**Issue by KristofSzabados** [Ericsson/codechecker#3096]
**Describe the bug**
We get this issue reported for our code:
"
[MEDIUM] /local/home/titanrt/jenkins/workspace/Titan_StaticAnalysis/label/titanrt_titan3/TTCNv3/common/memory.c:809:2: the result from calling 'memcpy' is not null-terminated [bugprone-not-null-terminated-result]
  memcpy(ptr, str, len);
  ^
  Report hash: 4a3329b7bd92ee7a690e2e50b010ea6b
  Steps:
    1, memory.c:809:9: strcpy (char *) (fixit)
    2, memory.c:809:2: the result from calling 'memcpy' is not null-terminated
"
The file in question is: https://github.com/eclipse/titan.core/blob/master/common/memory.c
And the code to which the issue is reported to:
"
      expstring_t ptr = (expstring_t)MALLOC_INTERNAL(filename, line, size);
      memcpy(ptr, str, len);
      memset(ptr + len, '\0', size - len);
"

The problem here is, that while the issue report in itself is correct in that after memcpy ptr is not null terminated ... it is made to be null-terminated literally in the next line.
So I do not believe this should be reported as an issue, but instead the checker should just check the next line too.

Or if the problem is that the return value of memcpy is not null-terminated (which would be "ptr" as well), that is also not an issue, since it is not assigned to a variable, and so can not lead to any issues.

**CodeChecker version**
6.15

**To Reproduce**
Run codechecker on our project.

**Expected behaviour**
I would expect codechecker to also analyze the next line of code to see if the variable it is referring to, does really not get a terminating null before its first actual use.

**Desktop (please complete the following information)**
 - OS: Win10
 - Browser: Firefox
 - Version: 83.0

**Comment by csordasmarton** [comment]
@KristofSzabados This problem is related to the static analyzers (Clang Tidy, Clang Static Analyzer) and not to the CodeChecker. Please create a ticket to the https://bugs.llvm.org/.
