### ISSUE TITLE
issue with " 'signed char' to 'int' conversion; consider casting to 'unsigned char' first."

### ISSUE THREAD

**Issue by KristofSzabados** [Ericsson/codechecker#3097]
**Describe the bug**
We get the " 'signed char' to 'int' conversion; consider casting to 'unsigned char' first." issue for our code.
https://github.com/eclipse/titan.core/blob/master/core/Charstring.cc in line 1463.

The line in question is "int val = base64_decoder_table[c];"
Where base64_decoder_table is declared as "signed char  base64_decoder_table[256]"
and intentionally holds signed 8 bit numbers.

All information I could find describes this to be potentially problematic if the input of the conversion contains characters with a code greater then 127.
But in our case we wish to convert from an 8 bit signed number to a signed int, where this should not apply.

I believe the checker in question could be more robust, to detect such situations and not report this issue for them.

**CodeChecker version**
6.15

**To Reproduce**
run codechecker on our project.

**Expected behaviour**
This situation should not be reported as a potential issue.

**Desktop (please complete the following information)**
 - OS: Win10
 - Browser: Firefox
 - Version: 83.0

**Comment by csordasmarton** [comment]
@KristofSzabados This problem is related to the static analyzers (Clang Tidy, Clang Static Analyzer) and not to the CodeChecker. Please create a ticket to the https://bugs.llvm.org/.
