### ISSUE TITLE
problematic issue report for freed memory

### ISSUE THREAD

**Issue by KristofSzabados** [Ericsson/codechecker#3099]
Found by Adam Knapp.

We get this issue reported for our code:
"
[HIGH] .../TTCNv3/core/RT1/PreGenRecordOf.cc:13343:25: Use of memory after it is freed [cplusplus.NewDelete]
check_replace_arguments(val_ptr->n_elements, index, len, "@PreGenRecordOf.PREGEN_RECORD_OF_UNIVERSAL_CHARSTRING","element");
^
Report hash: 0b3e836e10bf7a974d4cb571218f8338
Steps:
1, PreGenRecordOf.cc:14758:5: Assuming the condition is false
2, PreGenRecordOf.cc:14759:8: Calling 'PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING_template::valueof'
3, PreGenRecordOf.cc:14731:1: Entered call from 'PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING_template::replace'
4, PreGenRecordOf.cc:14733:5: Assuming field 'template_selection' is equal to SPECIFIC_VALUE
5, PreGenRecordOf.cc:14733:45: Assuming field 'is_ifpresent' is false
6, PreGenRecordOf.cc:14736:26: Assuming 'elem_count' is >= field 'n_elements'
7, PreGenRecordOf.cc:14736:26: Loop body executed 0 times
8, PreGenRecordOf.cc:14740:8: Calling '~PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING'
9, PreGenRecordOf.cc:13146:1: Entered call from 'PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING_template::valueof'
10, PreGenRecordOf.cc:13148:1: Calling 'PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING::clean_up'
11, PreGenRecordOf.cc:13152:1: Entered call from '~PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING'
12, PreGenRecordOf.cc:13155:5: Assuming field 'ref_count' is <= 1
13, PreGenRecordOf.cc:13159:10: Assuming field 'ref_count' is equal to 1
14, PreGenRecordOf.cc:13160:26: Assuming 'elem_count' is >= field 'n_elements'
15, PreGenRecordOf.cc:13160:26: Loop body executed 0 times
16, PreGenRecordOf.cc:13165:1: Memory is released
17, PreGenRecordOf.cc:13148:1: Returning; memory was released
18, PreGenRecordOf.cc:14740:8: Returning from '~PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING'
19, PreGenRecordOf.cc:14759:8: Returning; memory was released
20, PreGenRecordOf.cc:14759:8: Calling 'PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING::replace'
21, PreGenRecordOf.cc:13339:1: Entered call from 'PREGEN__RECORD__OF__UNIVERSAL__CHARSTRING_template::replace'
22, PreGenRecordOf.cc:13342:5: Assuming field 'val_ptr' is not equal to NULL
23, PreGenRecordOf.cc:13343:25: Use of memory after it is freed
"

The problem is that it is assumed that the memory is released (Step 16). The code around this step sets the variable 'val_ptr' to NULL. Then around Step 22, the value of this variable is checked thus the later code is not reached (Step 23). In contrast, if it is not NULL then the memory is not released.

CodeChecker version
6.15

To Reproduce
Run codechecker on our project.

Expected behaviour
If there is assumption (a variable equals to something), then this assumption should not be changed during later steps of the analysis.

OS: Ubuntu 18
Browser: Firefox
Version: 82.0

**Comment by csordasmarton** [comment]
@KristofSzabados This problem is related to the static analyzers (Clang Tidy, Clang Static Analyzer) and not to the CodeChecker. Please create a ticket to the https://bugs.llvm.org/.
