### ISSUE TITLE
Running parse with either json or codeclimate fails

### ISSUE THREAD

**Issue by nolange** [Ericsson/codechecker#3107]
**Describe the bug**

Running parse with either `json` or `codeclimate` fails.

The command `CodeChecker parse  -e json   /tmp/an` will just result in errors.
(meanwhile exporting to `html` works)

```
[WARNING 2020-12-17 17:45] - Invalid plist file
[WARNING 2020-12-17 17:45] - __init__() takes 2 positional arguments but 3 were given
[ERROR 2020-12-17 17:45] - Failed to parse plist /tmp/an/sys_pheaders_ld.c_clang-tidy_7dedc48963f2ced141340475c105ce4e.plist
```

**CodeChecker version**

I used the master branch on December 9 2020, version results in incredible helpful output:
```
CodeChecker analyzer version:

CodeChecker web version:
```

**Desktop (please complete the following information)**
 - OS: Linux 5.9.0-4-amd64 #1 SMP Debian 5.9.11-1 (2020-11-27) x86_64 GNU/Linux
 - Python: 3.9.1

**Comment by csordasmarton** [comment]
I think this problem is related to #3074 patch.

**Comment by nolange** [comment]
Applying the mentioned patch works, so this one is a duplicate.
