### ISSUE TITLE
CodeChecker does not handle certain clang-binaries

### ISSUE THREAD

**Issue by ghost** [Ericsson/codechecker#3113]
While installing CodeChecker on a centos 7.8 system, I noticed that after a successful 'make package' the CodeChecker would fail with:

```
    if cfg_handler.version_info.vendor != "clang":
AttributeError: 'bool' object has no attribute 'vendor'
```

After quite a bit of debugging I found that ClangVersionInfoParser does not handle the case where "/usr/bin/clang --version" is not emitting something like "InstalledDir: /usr/bin".

E.g.:
```
$ clang --version
clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
$ 
```

Maybe CodeChecker can, in this case, use the basepath of the clang-binary it invoked (the one which it invoked with --version).
Or maybe this:

```
$ python3
...
>>> import shutil
>>> shutil.which('ls')
'/usr/bin/ls'
>>> 
```

**Comment by csordasmarton** [comment]
@flok99 I created a patch which I think will solve your problem. Could you please try it out whether it works for you: #3186?
