### ISSUE TITLE
--tidy-config and --analyzer-config clang-tidy:take-config-from-directory=true does not work

### ISSUE THREAD

**Issue by VladAdGad** [Ericsson/codechecker#3119]
Still not fixed and can be reproduced in the same way. https://github.com/Ericsson/codechecker/issues/1798
Another way to reproduce is a using `--analyzer-config clang-tidy:take-config-from-directory=true`. Still the same bug

It is a very serious issue. In clang-tidy it is very canonical to use .clang-tidy file. A lot of teams can't migrate to your solution because this is a really frustrating problem.

Could you give me some workaround or put fix in the 6.16.0? Thank you 

Version: 6.15.0

**Comment by VladAdGad** [comment]
I tried to fix it by myself but I can't find --tidy-config inside **analyzers** folder

**Comment by csordasmarton** [comment]
This is the place where this option is registered:
https://github.com/Ericsson/codechecker/blob/75ef0ec24f9ef0f3ae6cd0e3fc57d04ab1114c21/analyzer/codechecker_analyzer/cmd/analyze.py#L373-L381

And this is the place where we use it:
https://github.com/Ericsson/codechecker/blob/75ef0ec24f9ef0f3ae6cd0e3fc57d04ab1114c21/analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py#L348-L362

**Comment by csordasmarton** [comment]
I think this issue is fixed in #3203.
