### ISSUE TITLE
CodeChecker store and parse don't work with Python 3.9

### ISSUE THREAD

**Issue by sandroandrade** [Ericsson/codechecker#3121]
**Describe the bug**
CodeChecker store and parse don't work with Python 3.9. Any attempt fails with a:

[WARNING][2020-12-31 20:09:07] {report} [49582] <139647424214848> - plist_parser.py:114 parse_plist() - Invalid plist file
[WARNING][2020-12-31 20:09:07] {report} [49582] <139647424214848> - plist_parser.py:115 parse_plist() - __init__() takes 2 positional arguments but 3 were given

error. CodeChecker conversion to HTML works fine.

**CodeChecker version**
6.16 (master)

**To Reproduce**
Steps to reproduce the behaviour:

1. Install python 3.9
2. Go over CodeChecker installation
3. Analyze a simple project
4. Try to parse or store results

**Expected behaviour**
CodeChecker store and parse should successfully store and parse analysis results.

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox
 - Version: 84.0.1

**Additional context**
Downgrading to Python 3.8 make things work fine.

**Comment by csordasmarton** [comment]
I think this problem is related to #3074 PR. Could you please try it out whether it solves your problem?

**Comment by csordasmarton** [comment]
Could you please try it again, the patch is merged.

**Comment by sandroandrade** [comment]
Hi @csordasmarton ,

Yes, I confirm it's running fine now. Thanks for handling that.
