### ISSUE TITLE
[Jenkins Gerrit Integration]: Faulty result on the Gerrit review page via HTTP post request

### ISSUE THREAD

**Issue by Varma-Amit** [Ericsson/codechecker#3122]
**Describe the bug**
As mentioned in the article(https://github.com/Ericsson/codechecker/blob/master/docs/jenkins_gerrit_integration.md), the HTTP post request should send back the proper result contained in the variable $DATA_TO_POST to Gerrit review page but instead it is just sending the string "$DATA_TO_POST" on the review page as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/77059048/103773460-5c763a80-502b-11eb-9df7-dc96e7348ef7.png)

**CodeChecker version**
Version 6.15.0

**To Reproduce**
Steps to reproduce the behaviour:

Issue is seen at the last section "Results in Gerrit" from below article:
https://github.com/Ericsson/codechecker/blob/master/docs/jenkins_gerrit_integration.md

**Expected behaviour**
Proper results on the Gerrit review page are expected as shown in below image(taken from the article)
![image](https://user-images.githubusercontent.com/77059048/103773896-0b1a7b00-502c-11eb-96d5-4ecf28d0b415.png)

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser: Chrome
 - Version: Codechecker version 6.15.0

**Additional context**
Add any other context about the problem.

**Comment by dkrupp** [comment]
To debug this, please check if the parse command returns with proper results
in the following step:
echo DATA_TO_POST=\\ > review
CodeChecker parse --ignore $CC_SKIPFILE cc_reports -e gerrit >> review

**Comment by Varma-Amit** [comment]
Seems like the parse command results are Okay:

![image](https://user-images.githubusercontent.com/77059048/103989169-96f8e800-518f-11eb-8a9d-096b285acd38.png)

**Comment by csordasmarton** [comment]
Did you set the request `body` field: https://github.com/Ericsson/codechecker/blob/master/docs/jenkins_gerrit_integration.md#http-request-send-the-review
![image](https://user-images.githubusercontent.com/6695818/103989711-682f4180-5190-11eb-8400-3973d3268caa.png)

**Comment by Varma-Amit** [comment]
Yes the request body is set the same way as shown in the article

**Comment by csordasmarton** [comment]
Did you inject the environment variable?
![image](https://user-images.githubusercontent.com/6695818/103991883-9e21f500-5193-11eb-8637-3a727e74b7de.png)
It is described in this [section](https://github.com/Ericsson/codechecker/blob/master/docs/jenkins_gerrit_integration.md#inject-environment-variable) but maybe it is not up-to-date.

**Comment by Varma-Amit** [comment]
Yes that worked and proper results is sent now but I am still facing a strange new issue now:
It is failing in the POST request as below:


![image](https://user-images.githubusercontent.com/77059048/103998667-813def80-519c-11eb-82d2-95010f1a6cc9.png)

**Comment by csordasmarton** [comment]
Did you set the `CC_CHANGED_FILES` environment variable?  It should point to a file which contains all the changed files. CodeChecker will read this file and skip the report if it is not in the changed files.
https://github.com/Ericsson/codechecker/blob/0be059eba2c951288bbaec2b53ca285b2d717b75/codechecker_common/output/gerrit.py#L26

**Comment by Varma-Amit** [comment]
Yes the CC_CHANGED_FILES is set in the job:
![image](https://user-images.githubusercontent.com/77059048/104005990-2d380880-51a6-11eb-9830-0109e89e9077.png)

**Comment by csordasmarton** [comment]
Is the `files-changed` file exists in your workspace? What is the content of it?

**Comment by csordasmarton** [comment]
@Varma-Amit One more comment: did you set the `CC_REPO_DIR` environment variable? It should point to the directory of the sources, i.e. the directory where the repository was cloned and CodeChecker will trim the beginning of the file path so the gerrit will find the files.

**Comment by csordasmarton** [comment]
I created a patch which will give you are error message in this case if the mandatory environment variables (`CC_REPO_DIR`, `CC_CHANGED_FILES`) are not set when using gerrit output.
