### ISSUE TITLE
CodeChecker parse -e codeclimate disconsiders --trim-path-prefix

### ISSUE THREAD

**Issue by sandroandrade** [Ericsson/codechecker#3199]
CodeChecker version: 6.15.1

Description: if there's a report for a "a/b/c/file.cpp", then exporting in codeclimate format always presents only "file.cpp" as file path. This prevents correct navigation when viewing the report in GitLab. Using --trim-path-prefix makes no effect in parse output.

**Comment by csordasmarton** [comment]
Thank you for this bug report. The problem comes from these changes: #2963. I created a patch which will solve this problem: #3202. If you have time please try out whether it solves your problem.

**Comment by sandroandrade** [comment]
Thanks for handling that. I confirm this properly fixes the bug!
