### ISSUE TITLE
introduce permalinks on the web interface

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#32]
it would be useful if the important views of the web GUI would have permalink URLs.
the following should have permalinks:-
-run-list
-bug list overview including filters
-view of a concrete defect
-a concrete page of the documentation and user guide

Then it would be possible the to send the the defect reports in email or use the browser back button.

**Comment by igalex** [comment]
An experimental implementation in 949fecc1246720043f28a38356cdca5ecf3c5907
