### ISSUE TITLE
Offer a release (venv!, not venv_dev) package builder for analyser and web "subprojects"

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#3223]
**Is your feature request related to a problem? Please describe.**
When trying to integrate CodeChecker's analysis into [Contour](http://github.com/ChristianParpart/Contour)'s CI, the "check out and build CodeChecker" takes a long time because making the VENV and the package requires having NodeJS installed to the system and downloading and packaging a lot of "web stuff" that's not required at all.

**Describe the solution you would like**
A `make venv` and `make package/standalone_package` commands in the `analyze` directory that only installs what's needed to get only the `CodeChecker analyze` command up and running.

**Describe alternatives you have considered**
There is a `make venv_dev` command offered, but it installs various Python packages that are only needed for the development of CodeChecker itself (e.g. `mkdocs` or `nosetests`), but that is additional unneeded things in this context.

**Additional context**
The `web` package similarly only offers a `make venv_dev`, so it might be a good idea to symmetrically implement this request for that project too. It should help the build time of CodeChecker-related Docker images, and various other distributions.

**Comment by csordasmarton** [comment]
@whisperity We have an option to skip building the web part during the package build. It is described here in the notes section: https://github.com/Ericsson/codechecker#linux

> By default the make package will build the UI code if it's not built yet or the UI code is changed. If you wouldn't like to build the UI code you can set the BUILD_UI_DIST environment variable to NO before the package build: BUILD_UI_DIST=NO make package.

**Comment by whisperity** [comment]
Oh, that's nice. Unfortunately, unless we manually edit the top level Makefile, creating the original V-env will still go ahead and install things like sqlalchemy and alembic which uses both time and data, even if the actual package build process won't interact with the JavaScript stuff.
