### ISSUE TITLE
venv_dev needs rustc package

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#3244]
make venv_dev needs rustc package?

**Comment by dkrupp** [comment]
Ubuntu 18.04
This 
setuptools-rust==0.12.1 package is missing from 
analyzer/requirements_py/dev/requirements.txt

And then this python package requires rustc package on linux.


make venv_dev
...
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine->-r requirements_py/dev/requirements.txt (line 19))
  Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ly4xqp5g/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ly4xqp5g/cryptography/
Makefile:52: recipe for target 'pip_dev_deps' failed
make[1]: *** [pip_dev_deps] Error 1
make[1]: Leaving directory '/mnt/ssd/ednikru/codechecker/web'
Makefile:119: recipe for target 'venv_dev' failed
make: *** [venv_dev] Error 2

**Comment by whisperity** [comment]
Is this still an issue? Ubuntu 18.04 was EOL'd in March 2023, and so far it does not look like this issue reproduces on 20.04 or 22.04 environments **with the stock Python** of those systems. Perchance you were using a broken version of Python in a more globally broken environment?

**Comment by bruntib** [comment]
As far as I remember, we could get rid of the rustc dependency even in Ubuntu18. I would say, that this ticket is not relevant anymore.
