### ISSUE TITLE
Support Clang-tidy rewrites (fixits)

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#326]
Clang tidy can rewrite the source code to fix issues in some cases. It would be awesome to support this feature.

**Comment by sylvestre** [comment]
Indeed, having the diff in the view would be great. @gyorb what do you think?

**Comment by gyorb** [comment]
Interesting idea.
For now we just planed to support the automatic rewrite by clang-tidy.
Maybe some kind of a diff could be stored. For this we should check all the source files (and all the used header files too) during analysis and decide if there was a modification (version control systems could help).
Codemirror has a [diff view](https://codemirror.net/mode/diff/) which could be used to show the users the changes.

**Comment by Xazax-hun** [comment]
I think, there should be two options:
* Store every fixit to a YAML file during analysis, and apply the fixits after the analysis is done.
* Store every fixit to a YAML file and then store the contents of this YAML file to the databes, so the fixits can show up in the clients and can be applied manually.

I think, the command line options should be reserved as part of the command line option cleanup for 6.0.

**Comment by dkrupp** [comment]
What would be the benefit of wrapping this clang-tidy feature into CodeChecker? Using clang-tidy directly isn't easy enough?

**Comment by Xazax-hun** [comment]
I think if someone do not know clang-tidy it is not apparent that it can actually rewrite the code. So I think a command line argument to fix the code might be useful so the help text makes it apparent that such feature exists. Moreover, I think the idiomatic way to use clang tidy to rewrite code is not to fix each file immediately but export all the fixes to a YAML and apply them separately. (This way we do not get inconsistent code by half of it being rewritten and half of it being the original). An finally, the users usually do not want to rewrite everything. So maybe it is beneficial to apply the skip list to the rewrites, so the headers of other projects will not be rewritten.

**Comment by Xazax-hun** [comment]
Note that, the script to run clang tidy and rewrite the source can be found at:
`tools/clang/tools/extra/clang-tidy/tool/run-clang-tidy.py`.

**Comment by bruntib** [comment]
Personally this seems to be a bit out-of-scope for me in CodeChecker.
