### ISSUE TITLE
report-converter does not maintain severity for Pylint

### ISSUE THREAD

**Issue by mduzee** [Ericsson/codechecker#3260]
When Pylint output is converted to plist the severity is being dropped. When the results are viewed in either html or the CodeCheck viewer all severities are Unspecified.

**CodeChecker version**
Base package version: 6.16.0
Package build date: 2021-04-05T10:40
Git commit ID (hash): b7619c59eddeb24015151262e1009ff796495789
Git tag information: 6.16

**CodeChecker web version**
Base package version: 6.16.0
Package build date: 2021-04-05T10:40
Git commit ID (hash): b7619c59eddeb24015151262e1009ff796495789
Git tag information: 6.16
Server supported API (Thrift): 6.39
Client API (Thrift): 6.39

**To Reproduce**
I simply followed the instructions here:
https://github.com/Ericsson/codechecker/tree/master/tools/report-converter#pylint

**Expected behaviour**
The PyLint output contains a message-id that starts with a letter. These letters are used to identify the category:
C = convention
R = Refactor
W = Warning
E = Error

It would be nice if this information could be used for the severity.

**Desktop (please complete the following information)**
 - OS: Ubuntu 20.04 (WSL)
 - Browser: Edge
 - Version: 89.0.774.57

**Comment by mduzee** [comment]
I just found the checker_severity_map.json file. Looks like this is is not an issue with the software, I just need to create a mapping.

**Comment by csordasmarton** [comment]
Severities for pylint analyzer rules will be added in #3414.
