### ISSUE TITLE
Concurrent checking with sqlite

### ISSUE THREAD

**Issue by Locutus18** [Ericsson/codechecker#328]
Concurrent checking bzip2 project if server is online with sqlite. Incorrect results coming back and I think the problem is that even the thrift and the server is trying to use the sqlite.

**Comment by gyorb** [comment]
Could you be a bit more specific about the configuration and setup you try to use for concurrent analysis with sqlite:
- check/server commands
- was the server started once and runs continously or it is stopped during the analysis

**Comment by Locutus18** [comment]
I'll explain what I was doing step by step.
Step 1 : I downloaded and unpacked with bzip2 project . The project analyzed in the codechecker.
Step 2: I started to the server.
Step 3: Fixed a bug in the bzip2.c file. 
( 462 lines changed :  //nread BZ2_bzRead = ( & bzerr , bzf , obuf , 5000 ); )
Step 4: Re-analyzed the project . With the same command. The server did not stop.

check command : Codechecker check -w something -n "workspace" -b "make"
server command : Codechecker server -w "workspace" 

The second analysis mode, go to my knowledge has updated to the analysis.
But the sqlite database is included in the results of the second analysis and the results of the first analysis , it stays in the given file.

**Comment by gyorb** [comment]
In the two example commands you use two different workspaces for the check and the server. Is that a typo?
The workspace should be the same for the check and the server.
CodeChecker check -w workspace -b make -n something
CodeChecker server -w workspace

**Comment by Locutus18** [comment]
Check command : 
CodeChecker check -n "Test" -b "make"

Server Command:
CodeChecker server -w /home/locutus/.codechecker

Yesterday misspelled the third step.
Step 3: Fixed a bug in the bzip2.c file. 
**( 580 lines changed : //nread BZ2_bzRead = ( & bzerr , bzf , obuf , 5000 ); )**

**Comment by gyorb** [comment]
This issue was resolved by #330
