### ISSUE TITLE
error: unknown argument: '-analyzer-config-help'

### ISSUE THREAD

**Issue by i-ky** [Ericsson/codechecker#3296]
**Describe the bug**
CodeChecker throws `error: unknown argument: '-analyzer-config-help'`.

**CodeChecker version**
```
$ CodeChecker version
CodeChecker analyzer version:
---------------------------------------
Kind                 | Version         
---------------------------------------
Base package version | 6.15.2          
Package build date   | 2021-04-09T12:56
Git commit ID (hash) |                 
Git tag information  |                 
---------------------------------------

CodeChecker web version:
------------------------------------------------
Kind                          | Version         
------------------------------------------------
Base package version          | 6.15.2          
Package build date            | 2021-04-09T12:56
Git commit ID (hash)          |                 
Git tag information           |                 
Server supported API (Thrift) | 6.39            
Client API (Thrift)           | 6.39            
------------------------------------------------
```

**To Reproduce**
Steps to reproduce the behaviour:

* Run command `CodeChecker --help`:
```
$ CodeChecker --help
error: unknown argument: '-analyzer-config-help'
error: unknown argument: '-analyzer-config-help'
usage: CodeChecker [-h]
                   {analyze,analyzer-version,analyzers,check,checkers,cmd,fixit,log,parse,server,store,version,web-version}
                   ...

...
```
* or `CodeChecker analyzers --analyzer-config clangsa`:
```
$ CodeChecker analyzers --analyzer-config clangsa
error: unknown argument: '-analyzer-config-help'

```

**Expected behaviour**
No `error:`.

**Desktop (please complete the following information)**
 - OS: Ubuntu 18.04

**Additional context**
I believe this can be reproduced with both Snap package and CodeChecker installed from source.

**Comment by csordasmarton** [comment]
@i-ky You clang version is too old. I created a patch which will handle this use case and prints an understandable error message in this case: #3297. By the way you have to upgrade your clang version if you want to use this command / feature.

**Comment by i-ky** [comment]
@csordasmarton, thank you again for fast response and a pointer! These errors are very minor annoyance. Good old clang 6.0 (default on Ubuntu 18.04) works fine as analyzer. I was just exploring available options.
