### ISSUE TITLE
Provide login with Guest/Anonymous access and "read-only permissions"

### ISSUE THREAD

**Issue by bulwahn** [Ericsson/codechecker#3308]
**Is your feature request related to a problem? Please describe.**
We run a public accessible CodeChecker instance for an open-source project (i.e., for the kernel development, but currently under as prototype investigation by a smaller group); but this feature is probably relevant for any open-source project that wants to employ CodeChecker.

We want to make the results from the CodeChecker instance available to the public. So anyone, even without registration with username and password shall be able to view the results and browse the findings in the source code, i.e., a login with a "guest" account should be possible. Of course, anyone using this anonymous/guest identity shall not have the permission to modify the status of findings or add comments, i.e., to avoid the system and database being badly modified by unknown people, destroying the work of the others with known accounts.

**Describe the solution you would like**

I envision:
The login screen is extended by a "Login as guest". This guest account can view everything according to its permissions, but not modify anything.

**Describe alternatives you have considered**

Open to any suggestions here.

**Additional context**

Once available, we are happy to try out and roll out that feature in our instance and provide feedback.

**Comment by csordasmarton** [comment]
@bulwahn You can create a custom user (e.g.: `demo`, `guess`) in the server configuration file by using the [dictionary based authentication](https://github.com/Ericsson/codechecker/blob/master/docs/web/authentication.md#dictionary-authentication) and you can give [PRODUCT_ACCES](https://github.com/Ericsson/codechecker/blob/master/docs/web/permissions.md#product-access) permission to this user on your product in the GUI.

You can write the username/password credentials in the [notification banner](https://github.com/Ericsson/codechecker/blob/master/web/server/vue-cli/src/assets/userguide/userguide.md#notification-banner), so anyone will see it who will visit your CodeChecker server instance and will be able to login and access the data but will not be able to manage (store, remove) the results.

We are using the same approach in our public demo server: https://codechecker-demo.eastus.cloudapp.azure.com

**Comment by bulwahn** [comment]
@csordasmarton Thanks for the pointer. I just tried out the public demo server; the guest user has the possibility to modify the assessment of findings, so the guest user could completely modify the database and all previous assessments rendering the CodeChecker instance useless. Is there a more restrictive permission for a user to only view the results, but disallow any modifications of the results database?

**Comment by csordasmarton** [comment]
Unfortunately the lowest available permission is the `PRODUCT_ACCESS` for now. I checked our API and I can see your problem, that anyone with this permission still can modify the review statuses or add/remove comments.

Maybe we can introduce a new permission type (e.g.: `PRODUCT_VIEW`). With this permission the users would be able to see the results but not to modify anything on the server. What do you think @bulwahn ?

**Comment by bulwahn** [comment]
> Unfortunately the lowest available permission is the `PRODUCT_ACCESS` for now. I checked our API and I can see your problem, that anyone with this permission still can modify the review statuses or add/remove comments.
> 
> Maybe we can introduce a new permission type (e.g.: `PRODUCT_VIEW`). With this permission the users would be able to see the results but not to modify anything on the server. What do you think @bulwahn ?

@csordasmarton I think that would work fine and probably also allows other similar use cases. I am looking forward to that feature. Can @jay24rajput take over the implementation of that feature? I think that might be a good fit for him if that's not too complicated to implement and extend the existing documentation.

**Comment by csordasmarton** [comment]
Unfortunately we are very busy in these days, so if @jay24rajput has time to implement this feature, then yes, it would be great :blush: I think it is not a very difficult task and I can help him if he is stucked.

**Comment by jay24rajput** [comment]
Hello @csordasmarton @bulwahn 

It seems like a very interesting issue to work on! I will get started by setting up authentication on my local machine for CodeChecker( I was using it without any authentication until now). 

Meanwhile @csordasmarton can you please redirect me to some of the files where the relevant code is situated?

**Comment by csordasmarton** [comment]
@jay24rajput Yes, sure. 
- The new permission name can be `PRODUCT_VIEW`.
- You have to extend the API and introduce a new permission type here:
https://github.com/Ericsson/codechecker/blob/b7619c59eddeb24015151262e1009ff796495789/web/api/codechecker_api_shared.thrift#L37. From this release the API generation is simplified and you can find more information how you can extend it here: https://github.com/Ericsson/codechecker/tree/master/web/api
- Introduce a new class for this new permission:
https://github.com/Ericsson/codechecker/blob/7e4fd7e1cd5298b296cc8f09fa238098d7b91651/web/server/codechecker_server/permissions.py#L713-L717
- Change the PRODUCT_ACCESS permission to PRODUCT_VIEW where it is need:
https://github.com/Ericsson/codechecker/blob/69f148a55030e76d1c74fd51e59c6d3eaf02698c/web/server/codechecker_server/api/report_server.py
For example for all getter functions (getRunData, getRunCount, getCheckCommand etc.) we can change the required permission to PRODUCT_VIEW.
- You will have to generate a new migration script file because we will introduce a new permission type on the database too. It is described in this page: https://github.com/Ericsson/codechecker/blob/master/docs/web/db_schema_guide.md#updating-configuration-database-schema. If you stucked with it just let me now.
- Update the documentation.
- Also please try to grep on the PRODUCT_ACCESS keyword: https://github.com/Ericsson/codechecker/search?q=PRODUCT_ACCESS&type= and check the other parts where it needs to be updated.

**Comment by jay24rajput** [comment]
@csordasmarton Thank you for giving the references!

I am trying to set up authentication locally using: https://github.com/Ericsson/codechecker/blob/master/docs/web/authentication.md

I am using Dictionary authentication and I have modified `server_config.json` for authentication as:
```json
"authentication": {
    "enabled" : true,
    "realm_name" : "CodeChecker Privileged server",
    "realm_error" : "Access requires valid credentials.",
    "session_lifetime" : 300,
    "refresh_time" : 60,
    "logins_until_cleanup" : 30,
    "method_dictionary": {
      "enabled" : true,
      "auths" : ["jay:jay@123"],
      "groups" : {
        "jay" : ["admin", "guest"]
      }
    },
```

After this, I ran the command `make package` and then `CodeChecker Server`. Now, on the web-view, I should Ideally see the login screen right? But when I visit `localhost:8001` it directly takes me to the screen and no login window. Am I missing something here, or anything else is required to be done from my end?

**Comment by csordasmarton** [comment]
@jay24rajput You can start a CodeChecker web server by using a custom workspace: `CodeChecker server -w ~/codechecker_auth_workspace -p 8001`. Enable the authentication in the `~/codechecker_auth_workspace/server_config.json` file, restart the server and the authentication should work (`localhost:8001`).

**Comment by jay24rajput** [comment]
@csordasmarton I have an issue while upgrading the API version. I ran all the steps suggested. There is no version to upgrade in `web/server/vue-cli/config/webpack.common.js` as it is taking it from `package.json`. I couldn't see the `js/codechecker-api-node/dist/codechecker-api-x.y.z.tgz` after the `make build` command but I am able to see it in my local repository

![image](https://user-images.githubusercontent.com/37550939/118701206-15961e00-b831-11eb-8fa8-79d7ff7ac600.png)

Should I add that manually from my local repository?

**Comment by csordasmarton** [comment]
@jay24rajput Yes, now the version in the `webpack.common.js` is set automatically. This behaviour is changed a couple of weeks ago, maybe the api change documentation is not updated. So in this file you don't have to do anything.

You have to go to the [web/api](https://github.com/Ericsson/codechecker/tree/master/web/api) directory and run the `make build` target which will generate the dist/codechecker-api-x.y.z.tgz file automatically (you can run this command from the root directory by using the -C option: `make -C web/api build`). After you run the `make package` target from the root directory it will call the `npm install` command automatically and install both the npm and pypi packages from your local machine.

**Comment by jay24rajput** [comment]
@csordasmarton Yes, that is correct, I did follow the same steps, the `codechecker-api-x.y.z.tgz` is not getting added to git. I tried it a couple of times, but the same result( Note: This .tgz file is getting generated in my local machine as shown in the image, it just not getting added to git)

**Comment by csordasmarton** [comment]
Oh, you have to add it manually to the git (`git add web/api/dist/codechecker-api-x.y.z.tgz`). Maybe you have to use the `-f` option too. We refactored this local package generation in this release, and this demonstrates that we need to update the documentation and also do some extra steps automatically what is possible.

**Comment by jay24rajput** [comment]
Yes some `.gitignore` is not adding it manually do the tree. Lets fix this issue in a separate PR( if not already fixed)

**Comment by jay24rajput** [comment]
@csordasmarton For this point:
>You will have to generate a new migration script file because we will introduce a new permission type on the database too. It is described in this page: https://github.com/Ericsson/codechecker/blob/master/docs/web/db_schema_guide.md#updating-configuration-database-schema. If you stucked with it just let me now.

I have updated the both occurrences of sqlalchemy.url to `sqlalchemy.url = postgres://postgres@localhost:8001/config
` in `almbuc.ini` file and added the following to `permissions.py`:
```python
PRODUCT_VIEW = _create_permission(ProductPermission, 'PRODUCT_VIEW',
                                default_enable=False,
                                managed_by=[PRODUCT_ADMIN])
```

Now when I run the following command: `alembic --name config_db revision --autogenerate -m "Added permission for Product View"` the terminal gets struck for quite a time. Am I missing something or doing something wrong? 

Also the table `permissions_product` is empty and I cannot access the default run even with superuser credentials

**Comment by jay24rajput** [comment]
@csordasmarton I also tried disabling authentication and nothing seems to work. The revision command is just stuck and gives no output at all

**Comment by csordasmarton** [comment]
@jay24rajput Could you please push all your changes to your branch and share this branch with us. So I can see what you did so far.

**Comment by csordasmarton** [comment]
Also to generate migration for enum types is a little bit hacky. When you run the `alemic --name ...` it will generate a migration file but in my case it was empty. Alembic doesn't support migration of enum type very well. So you have to modify this file by hand and insert the following lines:
```py
"""Added permission for Product View

Revision ID: 7ceea9232211
Revises: 302693c76eb8
Create Date: 2021-05-25 09:43:15.402946

"""

# revision identifiers, used by Alembic.
revision = '7ceea9232211'
down_revision = '302693c76eb8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


table_name = 'permissions_product'
name = 'permission'
tmp_name = 'tmp_' + name

old_options = ('PRODUCT_ADMIN', 'PRODUCT_STORE', 'PRODUCT_ACCESS')
new_options = old_options + ('PRODUCT_VIEW', )

new_type = sa.Enum(*new_options, name=name)
old_type = sa.Enum(*old_options, name=name)


def upgrade():
    ctx = op.get_context()
    dialect = ctx.dialect.name

    if dialect == 'postgresql':
        # Rename the enum type what we want to change.
        op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

        # Create the new enum.
        new_type.create(op.get_bind())

        # Alter detection status column.
        op.execute('ALTER TABLE ' + table_name + ' ALTER COLUMN ' + name +
                   ' TYPE ' + name + ' USING ' + name + '::text::' + name)

        # Drop the old enum.
        op.execute('DROP TYPE ' + tmp_name)
    elif dialect == 'sqlite':
        with op.batch_alter_table(table_name) as batch_op:
            batch_op.alter_column(name, existing_type=old_type, type_=new_type)


def downgrade():
    ctx = op.get_context()
    dialect = ctx.dialect.name

    if dialect == 'postgresql':
        # Rename the enum type what we want to change.
        op.execute('ALTER TYPE ' + name + ' RENAME TO ' + tmp_name)

        # Create the new enum.
        old_type.create(op.get_bind())

        # Alter detection status column.
        op.execute('ALTER TABLE ' + table_name + ' ALTER COLUMN ' + name +
                   ' TYPE ' + name + ' USING ' + name + '::text::' + name)

        # Drop the old enum.
        op.execute('DROP TYPE ' + tmp_name)
    elif dialect == 'sqlite':
        with op.batch_alter_table('table_name') as batch_op:
            batch_op.alter_column(name, existing_type=new_type, type_=old_type)

```

I hope that it will work but we should try it on both sqlite and postgresql databases if the database migration works properly when the database contains some permissions.

**Comment by jay24rajput** [comment]
@csordasmarton For me the file itself is not getting generated in the first place after running `alembic --name config_db revision --autogenerate -m "Added permission for Product View"` 

Here is the branch of the code I have so far:https://github.com/jay24rajput/codechecker/tree/login_as_guest

Please let me know if something is wrong in this one

**Comment by csordasmarton** [comment]
I don't know what can be the real problem (maybe the database connection string or the database is not initialized) but lets just create the following file manually: `web/server/codechecker_server/migrations/config/versions/126fa3f55e4b_added_permission_for_product_view.py` and use the content from my previous comment: https://github.com/Ericsson/codechecker/issues/3308#issuecomment-847642592
