### ISSUE TITLE
add a configuration option listen address

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#331]
Add a configuration option for viewer listen address:

The
CodeChecker server
sub option should be:
-l listen address

the default should be localhost.

Then the not so practical
--not-host-only
option can be removed.

**Comment by AlexTelon** [comment]
The --not-host-only should be documented as it is very useful when wanting to integrate CodeChecker to a companies CI toolchain for example. 

Though I agree that the "-l listen address" is a better interface.

**Comment by gyorb** [comment]
It will be part of the upcoming command line argument cleanup #415

**Comment by bruntib** [comment]
What would providing an address other than `localhost` mean?

**Comment by gyorb** [comment]
The new argument is implemented in #655. Removing the old argument will be in v6.0 because that is a backward incompatible change.
