### ISSUE TITLE
New codechecker-api tarball not added to git

### ISSUE THREAD

**Issue by jay24rajput** [Ericsson/codechecker#3318]
**Describe the bug**
While performing an API update using [Api Update Document](https://github.com/Ericsson/codechecker/tree/master/web/api) the `js/codechecker-api-node/dist/codechecker-api-x.y.z.tgz` file isn't getting added to git due to some `.gitignore` file. Also, remove `webpack.common.js` since the version is taken from `package.json`

**CodeChecker version**
6.39.0

**To Reproduce**
https://github.com/Ericsson/codechecker/tree/master/web/api

**Expected behaviour**
The tarball gz file should be added to `.gitignore`

**Comment by csordasmarton** [comment]
@jay24rajput I created a patch which will solve this problem and I have also refactored the documentation: #3319
