### ISSUE TITLE
Update package-lock.json by using npm v7

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#3372]
The `package-lock.json` file format is changed from `npm v7`: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json. We need to try to update this file and see if everything works fine with older version of npm.

**Comment by jay24rajput** [comment]
@csordasmarton I had done a fair amount of testing for the new node version in #3332 at least on the web UI( with DB migration), I will get to test the CLI functions as well. If everything works properly, should I issue a pull request?
