### ISSUE TITLE
sqlite3 select query limit

### ISSUE THREAD

**Issue by YaZasnyal** [Ericsson/codechecker#3380]
First of all I would like to thank you for this great product. 

**Describe the bug**
I get an error during ```store``` operation. 

**CodeChecker version**
CodeChecker analyzer version:
Kind                 | Version
-----------------|----------------------------------------------
Base package version | 6.16.0
Package build date   | 2021-05-05T13:01
Git commit ID (hash) | cc64e489d064bb4dfaec49c0cae1335e60f8ea4a
Git tag information  | 6.16

CodeChecker web version:
Kind                          | Version
-----------------------|------------------------------------------------
Base package version          | 6.16.0
Package build date            | 2021-05-05T13:01
Git commit ID (hash)          | cc64e489d064bb4dfaec49c0cae1335e60f8ea4a
Git tag information           | 6.16
Server supported API (Thrift) | 6.39
Client API (Thrift)           | 6.39

**To Reproduce**

Run store after scanning a large project.

**Expected behavior**
Maybe this operation should be made using chunks that database actually can process.

**Desktop (please complete the following information)**
 - OS: Linux (CentOS 7.6.1810)

**Additional context**
Logs:
```
[INFO 2021-07-13 08:34] - Successfully analyzed
[INFO 2021-07-13 08:34] -   clang-tidy: 1268
[INFO 2021-07-13 08:34] -   clangsa: 1224
[INFO 2021-07-13 08:34] - Failed to analyze
[INFO 2021-07-13 08:34] -   clang-tidy: 9
[INFO 2021-07-13 08:34] -   clangsa: 53
[INFO 2021-07-13 08:34] - Total analyzed compilation commands: 1277
[INFO 2021-07-13 08:34] - ----=================----
[INFO 2021-07-13 08:34] - Analysis finished.
[INFO 2021-07-13 08:34] - To view results in the terminal use the "CodeChecker parse" command.
[INFO 2021-07-13 08:34] - To store results use the "CodeChecker store" command.
[INFO 2021-07-13 08:34] - See --help and the user guide for further options about parsing and storing the reports.
[INFO 2021-07-13 08:34] - ----=================----
[INFO 2021-07-13 08:34] - Analysis length: 51026.36008620262 sec.
[a.vasiliev@localhost build-mass_ims_CodeChecker]$  CodeChecker store my_plists --name mass
[INFO 2021-07-13 10:03] - Storing analysis results for run 'mass'
[INFO 2021-07-13 10:03] - Checking local passwords or tokens in /home/a.vasiliev/.codechecker.passwords.json
[INFO 2021-07-13 10:03] - Password file not found.
[INFO 2021-07-13 10:03] - Checking for local valid sessions.
[INFO 2021-07-13 10:09] - Processing report files done.
[INFO 2021-07-13 10:09] - Collecting review comments ...
[INFO 2021-07-13 10:51] - Collecting review comments done.
[INFO 2021-07-13 10:51] - Get missing file content hashes from the server...
[ERROR 2021-07-13 10:51] - Calling API endpoint: getMissingContentHashes
[ERROR 2021-07-13 10:51] - Database error on server
(sqlite3.OperationalError) too many SQL variables
[SQL: SELECT file_contents.content_hash AS file_contents_content_hash
FROM file_contents
WHERE file_contents.content_hash IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ... total 3721)]
[parameters: ('fb9890d3c22849fde7270a2c13e3c7ef3390a6af0ce4b30267e5783582071b3d', 
'ed0437123296fadb0255ae14ab84864fec84cd9888af4879cae76fd2c37d2446', 
'f5c626f9807c79dda86aadce85072977d82801126537b15f529b447c04f05fe8', 
'dd5b90b3ab38f9f480f132771d6982f63b9ac0c46bcd59835723eac77f59cda6', ...)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

I have also found issue that is very similar to this (#1704)

**Comment by csordasmarton** [comment]
@YaZasnyal The problem is similar to this discussion: #2826. So the recommendation is to use `PostgreSQL` instead of `SQLite` or build your own SQLite described in the discussion thread.
