### ISSUE TITLE
cleanup and refactor database schema

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#343]
- [ ] Some schema cleanup is needed because of performance issues during the remove of the results.
- [ ] There are some tables which can be merged (BugPathEvent, BugReportPoint)
- [ ] BuildAction #329

**Comment by Xazax-hun** [comment]
I am not sure that merging BugPathEvent and  BugReportPoint is a good idea. They are separate concepts in the plist generated by clang, and I doubt that this would provide us with any serious performance gain.

**Comment by gyorb** [comment]
I think it is worth to try. The queries could be simplified a lot. I know they are separate concepts but the only difference between them storage wise is that the BugPathEvent contains a message not just a position. We definitely will measure if there is any performance gain.

**Comment by whisperity** [comment]
Note: We should consider #565 for this!

**Comment by dkrupp** [comment]
I guess this is solved by detection status related refactoring.
