### ISSUE TITLE
Missing results in database

### ISSUE THREAD

**Issue by sudipm-mukherjee** [Ericsson/codechecker#3436]
**Describe the bug**
We will take the build information and will convert the
findings into a 'plist' using reportconverter and then the info from plist will be stored in
the database using command "CodeChecker store". In my understading, when it creates the plist
it creates the plist filename as the "`source file name`_`checkername`".
So, in our case where we build the kernel with clang-tidy the particular file related to this bug report   "drivers/net/wireless/intel/iwlwifi/dvm/rs.c" will be
stored as "rs.c_clang-tidy.plist".
But, there is also another file
"drivers/net/wireless/intel/iwlwifi/mvm/rs.c" which also generated
clang-tidy warning for deadstore. And, so reportconverter will try to save
this one also as "rs.c_clang-tidy.plist" in the same folder. And, so I
guess whichever of these two is stored first will be overwritten by the
other one. As a result we get warning from mvm/rs.c for few days and
from dvm/rs.c for few days.

**CodeChecker version**
6.17

**To Reproduce**
Build the linux kernel with clang-analyzer, and convert the result to plist using "report-converter -t clang-tidy".
In the raw logs, there wil be deadstore warning for both:
drivers/net/wireless/intel/iwlwifi/mvm/rs.c
drivers/net/wireless/intel/iwlwifi/dvm/rs.c
But there will be only one plist for any one of them.

**Expected behaviour**
The deadstore information for both the file should be there.

**Desktop (please complete the following information)**
 - OS: linux
 - Browser: NA
 - Version: NA

**Additional context**
NA

**Comment by csordasmarton** [comment]
@sudipm-mukherjee The `report-converter` tool has an option, `--filename` to override/customize the file names of the generated plist files. For example when we generate Makefile with the CodeChecker analyze command we insert a target hash into the file name: https://github.com/Ericsson/codechecker/blob/master/analyzer/codechecker_analyzer/makefile.py#L260

**Comment by sudipm-mukherjee** [comment]
Thanks for replying @csordasmarton. But iiuc, when I use `--filename` it will append a the hash to the filename. So in our case I am using reportconverter like `report-converter -t clang-tidy -o report_out clang.log` and I can change it to `report-converter --filename {source_file}_{analyzer}_test1  -t clang-tidy -o report_out clang.log` then it will still produce the file `rs.c_clang-tidy_test1.plist` and will again overwrite it. or am I missing something ?

I am attaching the relevant part of the log file, and if you run reportconverter on this log file it will only generate one "rs.c_clang-tidy.plist" which will only have the clang-analyzer information of either "drivers/net/wireless/intel/iwlwifi/dvm/rs.c" or "drivers/net/wireless/intel/iwlwifi/mvm/rs.c" and thus leads to missing information in the database. 
[clang.log](https://github.com/Ericsson/codechecker/files/7254736/clang.log)
