### ISSUE TITLE
docker-compose fails to run CodeChecker server with permission denied

### ISSUE THREAD

**Issue by andrewg-spectra** [Ericsson/codechecker#3458]
**Describe the bug**
docker-compose files that mount a workspace volume to /workspace will create that directory when the service container is created. That directory will always have owner root. The entrypoint.sh script will see that the /workspace directory exists and not run `chown codechecker` on it. However, `CodeChecker server` when run as user codechecker needs to be the owner of /workspace to write to it.

**CodeChecker version**
v6.17.0

**To Reproduce**
Run `docker-compose up` on any of the [sample files](https://github.com/Ericsson/codechecker/tree/master/web/docker/services). You may need to change the image to `codechecker/codechecker-web:v6.17.0` 

**Expected behaviour**
codechecker service should initialize correctly.

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: N/A
 - Version: N/A

**Additional context**
None.

**Comment by aallrd** [comment]
I think I am hitting the same issue using the simple `docker run` example from the documentation:
```
$ docker run --rm -p 8001:8001 -v /home/$USER/codechecker/workspace:/workspace codechecker/codechecker-web:6.18.0
[INFO 2021-11-29 14:48] - Checking configuration database ...
[INFO 2021-11-29 14:48] - Connection failed to the database server.
[ERROR 2021-11-29 14:48] - Failed to configure default product
```

Same thing when not bind-mounting:
```
$ docker run --rm -p 8001:8001 -v codechecker_workspace:/workspace codechecker/codechecker-web:6.18.0
[INFO 2021-11-29 14:49] - Checking configuration database ...
[INFO 2021-11-29 14:49] - Connection failed to the database server.
[ERROR 2021-11-29 14:49] - Failed to configure default product
```

I reproduce this issue starting release 6.17.0.

**Comment by andreas-foreflight** [comment]
+1

It seems to me that the approach of using a volume as described in the documentation no longer works since version 6.17 where the entrypoint script was changed to allow running as different users.
