### ISSUE TITLE
files with a path that contains '@' are skipped 

### ISSUE THREAD

**Issue by ferkulat** [Ericsson/codechecker#3463]
**Describe the bug**
Given a compilation_database.json where all file paths contain a '@'.
For example:
~~~~
{
  "directory": "C:/jenkins/workspace/MS-1234-5.6-use_withCredentials@2/b",
  "command": "C://msys64//mingw64//bin//c++.exe ",
  "file": "C:/jenkins/workspace/MS-1234-5.6-use_withCredentials@2/lol_common/components/Logger/Source/Logger.cpp"
},
~~~~
The `command` is removed because of company internals. But it also had an '@' in there.

Codechecker prints:
~~~~
[INFO 2021-10-26 19:24] - No analysis is required.
There were no compilation commands in the provided compilation database or all of them were skipped.
~~~~
 
**CodeChecker version**
6.17.0

**Desktop (please complete the following information)**
 - OS: windows

**Additional context**
those paths are used on jenkins to create workspaces
Please notice: 
The original compile_commands.json has `\` in all paths. Those get replaced with `/` before passing it to Codechecker.
Otherwise the jenkins plugin 'warnings-ng' would not find and display them in the UI.
But as long as there are no `@` in there, it works.

**Comment by ferkulat** [comment]
@csordasmarton  I could debug to the part where it skips files that have  an `@` in there.
Please have a look at the screenshot.
If the filename has an `@` in there it does not add this file, but tries to add entries from `source_files`, which is empty at this moment.
This was added in commit 2cb9bc1abf82ae1df0d38fe6911d9f9fd035d54
I am tempted to remove this part, but at the moment don't know what those "response files" are. 
And how important the support if it is.



![Screenshot from 2021-10-30 13-56-17](https://user-images.githubusercontent.com/1757239/139532140-32e1d37c-f982-40b5-8da1-21c606312a6d.png)

**Comment by ferkulat** [comment]
@csordasmarton If I understand it correctly, the file name of a response file starts with an `@`.
To fix this, I would remove the path part from the file entry, before checking for `@`?

**Comment by csordasmarton** [comment]
See: https://llvm.org/docs/CommandLine.html#response-files

> Some systems, such as certain variants of Microsoft Windows and some older Unices have a relatively low limit on command-line length. It is therefore customary to use the so-called ‘response files’ to circumvent this restriction. These files are mentioned on the command-line (using the “@file”) syntax. The program reads these files and inserts the contents into argv, thereby working around the command-line length limits.

I think we can change this line to check whether a file starts with a `@` instead of containing it:
https://github.com/Ericsson/codechecker/blob/4be1ecad9249470171a623feeacf17da83858fce/analyzer/codechecker_analyzer/buildlog/log_parser.py#L1181

`if '@' in entry['file']:` vs `entry['file'].startswith('@')`
