### ISSUE TITLE
Missing static HTML files in pip installation

### ISSUE THREAD

**Issue by yalfg** [Ericsson/codechecker#3499]
**Describe the bug**
The generation of a static HTML report fails with an exception due to a missing HTML static file in the pip installation.

**CodeChecker version**
6.18.0, installed using pip3.

**To Reproduce**
Just try to generate an HTML report from a previous analysis, for example:
```
CodeChecker parse -e html -o html_report ./pfiles
```
This will fail with a python exception.

**Expected behaviour**
Successful creation of an HTML report.

**Desktop (please complete the following information)**
 - OS: Debian Linux Buster or Bullseye

**Additional context**
When installing 6.18.0 using pip3, the HTML static files directory is missing. It should be under: 
`site-packages/codechecker_report_converter/report/output/html/static`.
This cause the parsing with export to HTML to fail with an exception as it can't find `static/layout.html`.

**Comment by francois-berder** [comment]
I confirm I am also having this bug on Ubuntu 20.04
