### ISSUE TITLE
do not log compiler wrapper scripts

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#35]
introduce an env variable to the logger to log only the execution of elf binaries (gcc, g++ are binaries)

the name of the env variable should be :8ball: 
CC_LOG_BIN_ONLY
default 1

**Comment by igalex** [comment]
An experimental implementation in 949fecc

**Comment by Xazax-hun** [comment]
What is the use case of this feature? Why is it useful?

**Comment by gyorb** [comment]
Currently the build logger logs compiler wrapper scripts also if the name matches to the names defined in the CC_LOGGER_GCC_LIKE environment variable. With this improvement the wrapper scripts will not be logged.

**Comment by igalex** [comment]
Won't fix.
