### ISSUE TITLE
JSON diff output broken in 6.18.0 release

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3526]
The json diff report format has changed, I think because of  commit 90eafcd31a3e856e1306aeef1d3c143cb2e13cc8. This broke many scripts and it should be mentioned in the 6.18.0 release notes as a breaking change.

The only thing mentioned is refactoring for sarif support which I do not know what it is.

The JSON format has changed in many ways:
1. The list of issues are now in a JSON object, under a "reports" array  ```{"version":1, "reports":[ ...```
2. The `severity` changed from numeric to string (why? couldn't you give it a new name, like `severity_string`?)
3. The `bugHash` is gone.
4. More changes. I'm not sure it's trivial to adjust the scripts unless there is a detailed listing somewhere.

**Comment by csordasmarton** [comment]
I updated the release notes and I also created a PR to document the new format: #3519.

**Comment by jimis** [comment]
Thanks!

**Comment by jimis** [comment]
@csordasmarton  What about the `reportId`? We use the JSON output to construct links to CodeChecker UI. A link in the UI is like this:

```https://codechecker/product/report-detail?run=old_run&newcheck=new_run&report-id=697801&report-hash=d90e98a8e159d35e1d12773c80efc002&report-filepath=src%2Fpath2Ffile.c```

I don't see what to use for "report-id" now.

**Comment by jimis** [comment]
Filed #3628
