### ISSUE TITLE
[cmd diff] Run names with literal `:` in them understood differently than `store` and `cmd runs` commands

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#3535]
# Describe the bug
If the run name is in some way "complex", `cmd diff` constantly reports `No run names with the given pattern:`. However, the exact same format of run name is accepted by `cmd results` (and also `store`).

The complex run-name in question looks like this: **`my/complex-run: name`**. (Auto-generated from Git `user/repository: branch` format.)

# CodeChecker version

612b726a9f4ad822a6c676b2ad854f9c228752b4

# To Reproduce

1. `store --name simple-1`
2. `store --name simple-2`
3. `store --name "my/complex-run: name"`
4. `cmd results "my/complex-run: name"` works. ✔️
5. `cmd diff --new --basename "simple-1" --newname "simple-2"` works. ✔️
6. `cmd diff --new --basename "my/complex-run: name" --newname "simple-1"` doesn't work. ❌

# Expected behaviour

The run name is accepted, and before pattern-matching(?) or file system traversal, exact string match is done for the remote name. (In addition, if there are *BOTH* a local directory structure AND a remote run with the same pattern(?), a warning is emitted.)

# System

 - OS: Ubuntu 18.04

# Additional context

The issue appears both when diffing remote to local and remote to remote, and in both directions.

If I make a directory locally, and execute `diff`, it will pick the directory up as the local run. That is, if the following directory structure appears locally (even if empty) ...

```
$ tree my
my
└── complex-run: name
```

... then all the remote findings will be regarded as `--new`, and reported.

I tried escaping most of the suspicious characters in the run name, i.e. `"my\/complex-run: name"`, `"my\/complex\-run\:\ name"`, and various other combinations of escape, but had no luck.

The exact error message is a bit misleading, I had to have the hunch to try making a directory, because the following relevant lines are printed, even with `--verbose debug`.

~~~~
[INFO][2021-12-06 11:25:31] {system} [14277] <140079117096768> - cmd_line_client.py:1190 handle_diff_results() - Given remote runs (--baseline): my/complex-run: name
[DEBUG][2021-12-06 11:25:31] {system} [14277] <140079117096768> - client.py:257 setup_client() - Initializing client connecting to [...] done.
[WARNING][2021-12-06 11:25:32] {system} [14277] <140079117096768> - cmd_line_client.py:156 process_run_args() - No run names match the given pattern: my/complex-run: name
~~~~

It does not even say that it is *trying* to find local directory structures.

**Comment by csordasmarton** [comment]
@whisperity The client thinks that you gave  `complex-run` as the run name and ` name` as the history tag name:
https://github.com/Ericsson/codechecker/blob/612b726a9f4ad822a6c676b2ad854f9c228752b4/web/client/codechecker_client/cmd_line_client.py#L149

**Comment by whisperity** [comment]
> The client thinks that you gave `complex-run` as the run name and ` name` as the history tag name

@csordasmarton Ah, thank you. Then it seems local directories do indeed take priority!

Would it be possible to implement some sort of an "escape" mechanism here, e.g. first match for `\:`, then do not split, and rewrite as `:`? The issue is that other commands happily accept `:` as-is, without trying to understand it as a tag. (`store` has a dedicated `--run-tag` or somesuch CLI option, I'm not sure about `cmd results`.)

Or should I just come up with a better run name generating logic, and add something to my documentation to discourage users from putting `:` into their run names (if they configure it themselves)?

**Comment by csordasmarton** [comment]
I think we can support escaping here something like this:
```py
>>> run_name="my/comple-run\: name:tag_version"
>>> list(map(lambda x: x.replace("\:", ":"), re.split(r"(?<!\\):", run_name)))
['my/comple-run: name', 'tag_version']
```

**Comment by whisperity** [comment]
@csordasmarton Perfect! :smiley: Will you have some time to add this small feature, or should I?

**Comment by csordasmarton** [comment]
If you have time, please create a PR for it. Also don't forget to add a test case for it :blush:
