### ISSUE TITLE
Checker alpha.security.cert.pos.34c enabled in default profile

### ISSUE THREAD

**Issue by LesserBabka** [Ericsson/codechecker#3546]
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.18.0                                  
Package build date   | 2021-11-24T20:06                        
Git commit ID (hash) | 153b0e09efc715fd16eee815eecf454f9f79f7f1
Git tag information  | 6.18-tainted                            
---------------------------------------------------------------

The checker alpha.security.cert.pos.34c was added to the default profile in 9633422b88f6c96abc9faf2148894c33bfeb2c95. However, the description for that checker states "Enable only for development!".

**Comment by steakhal** [comment]
I remember the checker. It's pretty solid as far as I can tell.
It has only one weakness AFAIK, which is why it's an `alpha` checker :(
The docs did not mention this, so I'm adding it now: https://reviews.llvm.org/D124659

**Comment by steakhal** [comment]
The linked patch has been landed. I think we can close this now. @bruntib
