### ISSUE TITLE
CodeChecker cmd diff does not find source files in 6.18

### ISSUE THREAD

**Issue by jimis** [Ericsson/codechecker#3567]
The reason is most probably that the analysis runs with `--trim-path-prefix` and the paths stored are relative, not absolute. It affects many `cmd diff` formats, including HTML and text output formats.

Example output:
```
[LOW] src/corelib/global/qforeach.h:58:7: class 'QForeachContainer' defines a copy constructor, a copy assignment operator, a move constructor and a move assignment operator but does not define a destructor [cppcoreguidelines-special-member-functions]
[ERROR 2022-01-03 09:44] - Failed to open file src/corelib/global/qforeach.h
```
(EDIT: worth mentioning is that when the output is to HTML, no error is printed to stdout or stderr, and the command looks successful, while it has generated bad report output)

If I `cd` to the source directory, then the command succeeds. It is a regression, it broke when we upgraded to 6.18.

**Comment by csordasmarton** [comment]
@jimis Can you please provide us steps one-by-one how we can reproduce this problem?

**Comment by jimis** [comment]
1. The usual  `analyze` and `log` CodeChecker commands
2. `CodeChecker store /path/to/results_dir --trim-path-prefix /home/username/path/to/src//src/qt/qt5/qttools/ -n qttools-dev-20220104-18d293ab75 --url http://localhost:8002/qttools-dev

**Comment by csordasmarton** [comment]
@jimis I created a patch which I think will solve this problem. Can you please try it out: #3568?

**Comment by jimis** [comment]
Thanks! I tested your patch for the command line output, and it seems to fix the issue.

I'm having trouble reproducing the problem with the HTML output, so I didn't test that yet.
