### ISSUE TITLE
introduce env variables for common commandline parameters

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#36]
it would be useful to be possible to give command line parameters as env variables
this would make the command line shorter.

if command line is specified it should override env var and default settings:
default->env-var->command line (override sequence)

in case of enable/disable checker list: the default should be extended by either the env var or the command line param

these params should have env var equivalent:
-workspace
-dbport
-dbhost
-dbuser
-dbname
-enable/disable checker list
-viewport
-suppress file path

if the env var is speficied then the CodeChecker script should list their values when started.

**Comment by Xazax-hun** [comment]
It might be just my preference, but I do not like when an application relies on many environment variable. Wouldn't it be more user friendly to have a config file and one environment variable which is the path to the config? (or define a heuritic to find the config file)

**Comment by gyorb** [comment]
Configuring environment variables is only an option, not required. The same settings can be configured in the command line right now. The environment variables can be a flexible option for different build environments.
You can always write a simple setup script for your environment variables or command line options.

**Comment by labuwx** [comment]
Implicitly reading env vars could result frustrating debugging situations, especially when there are so many of them. Even with a switch (like '--env-var-conf' ) users may unintentionally use env vars that were set the week before (with tmux, screen it is common to have terminal sessions as old as the uptime).

I think users, whom you aim this feature for, are quite happy with their current solution:
```bash
alias mycheck='Codechecker check --dbport 5432 --dbusername jack --dbname ccdb -l myproject/log'
mycheck -n third_check_of_myproject 
```
It is flexible, simpler than setting an env var for each config option, and doesn't limit you to one config per terminal session.

**Comment by dkrupp** [comment]
We finally decided to use config files and a single environment variable CODECHECKER_CONFIG containing the location of the config file.

by default CodeChecker will take the config files from ~/.codechecker.conf
if not found it will take it from $CODECHECKER_CONFIG 

The config file will contain paramaters as key value pairs in json format

if any parameter is defined in the command line it overrides the config file.

**Comment by labuwx** [comment]
> by default CodeChecker will take the config files from ~/.codechecker.conf
> if not found it will take it from $CODECHECKER_CONFIG

Why not `$CODECHECKER_CONFIG` by default, if the variable is unset then `~/.codechecker.conf`?

**Comment by dkrupp** [comment]
makes sense. So from $CODECHECKER_CONFIG by default and if not set ~/.codechecker.conf.

**Comment by bruntib** [comment]
This issue is not relevant any more, because we don't have such a config file.
