### ISSUE TITLE
Please provide a checker view

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#361]
For big projects like Firefox (more than 180 000 warnings), it would be nice to have the list of all defects found by a checker (either in the webview or the cli).

**Comment by gyorb** [comment]
Do you want to get some summary view about the checkers?
Right now you have two options:
1. you can filter the results by checker name on the GUI
2. use the command line ```CodeChecker cmd sum --help``` to get a summary

Do you have another type of view in your mind?

**Comment by sylvestre** [comment]
Are you sure? This looks incorrect:
```
$ CodeChecker cmd sum -p 8001 -n clang-analyzer-deadcode.DeadStores 
No check name found: clang-analyzer-deadcode.DeadStores
Possible check names are:
firefox_201609010755
firefox_201609040755
firefox_201608232251
firefox_201608310756
firefox_201609030755
firefox_201608241541
firefox_201608240045
firefox_201608271710
firefox_201608241057
firefox_201608300756
firefox_201608280753
firefox_201608250753
firefox_201609050753
firefox_201608290753
firefox_201609020755
firefox_201608242327
```

**Comment by sylvestre** [comment]
> 1. you can filter the results by checker name on the GUI
In a specific run? What is I want to get all of them for all runs?

**Comment by gyorb** [comment]
Please try this command ```CodeChecker cmd sum -p 8001 -a``` or ```CodeChecker cmd sum -p 8001 -a -o json``` for json format. This will give a summary list for all the runs in the database this is not a merged summary.
Maybe we could add some ```CodeChecker sum global ...``` command to get a summary about all the checker results found in multiple runs.
Until there is no support for this I think it can be easily done by a simple script to go through the json formatted output and sum all the checkers.

**Comment by gyorb** [comment]
The new feature in #361 is related to this but will not fully resolve the new feature request. The new UI improvement will show a summary for each run based on the severity levels.
I still think a command-line summary command would be nice where the summary based on checker names or severity levels could be collected.

**Comment by dkrupp** [comment]
CodeChecker v6.0 implements this view
Checkers Summary Table: Provides a summary statistics of reports found by checkers summarized for all runs. (#826)
