### ISSUE TITLE
CodeCheker version command returns different version than installed.

### ISSUE THREAD

**Issue by AnyFlyGuy** [Ericsson/codechecker#3615]
**Describe the bug**
Installing CodeChecker from pip will install or display wrong version (relevant for VS plugin requiring version < 6.18.2

**CodeChecker version**
6.18.2

**To Reproduce**
`pip3 install CodeChecker==6.18.2`
`CodeChecker version`

**Expected behaviour**
`CodeChecker version` should return 6.18.2 instead of 6.18.1

**Desktop (please complete the following information)**
 - OS: Ubuntu

**Additional context**

![image](https://user-images.githubusercontent.com/29370664/156348758-d8edf3cb-d22c-4d35-a3de-b1fbe8abf785.png)

**Comment by csordasmarton** [comment]
Yes, this is a known issue with the 6.18.2 pip package. Unfortunatelly we forgot to increment the version in the repository before we released it and pypi doesn't support to upgrade an already uploaded version. At the end of the next week we will release the 6.19.0 CodeChecker version and it will solve this problem.

**Comment by csordasmarton** [comment]
We just released the new `6.19.0` CodeChecker version where the version information should be correct and also it contains some features/bug fixes related to VSCode. So I recommend to try it out :blush:

**Comment by csordasmarton** [comment]
The latest versions (6.19.0, 6.19.1) work properly, so I close this ticket.
