### ISSUE TITLE
`./bin/CodeChecker` doesn't work

### ISSUE THREAD

**Issue by dfarley1** [Ericsson/codechecker#3637]
Fresh install of v6.19.1
```
$ git clone https://github.com/Ericsson/codechecker.git /depot/vendor/codechecker
$ cd codechecker
$ git checkout v6.19.1
$ make standalone_package
./bin/CodeChecker --help
/usr/lib/python-exec/python3.9/python3: can't open file '/depot/vendor/codechecker/lib/python3/codechecker_common/cli.py': [Errno 2] No such file or directory
```

`./build/CodeChecker/bin/CodeChecker --help` does work, so it seems like there's something funky about the paths relative to the top of the repo?

**Comment by bruntib** [comment]
Hi,
`./build/CodeChecker` is the "portable" package that `make` builds. You shouldn't execute CodeChecker directly from `./bin`, because relative paths are really important as you mentioned, and these relative paths are correct only under `./build/CodeChecker`.
