### ISSUE TITLE
How to check the clang version?

### ISSUE THREAD

**Issue by Logyiyi** [Ericsson/codechecker#3638]
I updated Clang to the latest version after installing CodeChecker. Then I want to check the clang version which CodeChecker uses now and then decide to reinstall CodeChecker or not. Please help me.

**Comment by bruntib** [comment]
Try this command:
`CodeChecker analyzers --details`

**Comment by Logyiyi** [comment]
Thank you! It works!

**Comment by whisperity** [comment]
@Logyiyi FYI: CodeChecker uses the `clang` binary (with some version suffices like `clang-10` or so?) that is available in your `PATH` at the time of execution. It is **always** found dynamically unless you hardcoded a binary in one of the configuration files.
