### ISSUE TITLE
How to invoke the debug macro of the checker

### ISSUE THREAD

**Issue by Logyiyi** [Ericsson/codechecker#3642]
How to use the command line to invoke the debug macro of the checker?
"--verbose" seems not right, please help.

**Comment by csordasmarton** [comment]
@Logyiyi What do you mean to "invoke the debug macro of the checker"? Could you please describe this a little bit more?

**Comment by Logyiyi** [comment]
The llvm/Support/Debug.h file provides a macro named LLVM_DEBUG(). Basically, you can put arbitrary code into the argument of the LLVM_DEBUG macro, and it is only executed if ‘opt’ (or any other tool) is run with the ‘-debug’ command line argument:

LLVM_DEBUG(dbgs() << "I am here!\n");
Then you can run your pass like this:

$ opt < a.bc > /dev/null -mypass
<no output>
$ opt < a.bc > /dev/null -mypass -debug
I am here!

The above content is described in the LLVM official documents and I was wondering if this could be used in CodeChecker.

**Comment by steakhal** [comment]
First of all, you need to have a clang with debug assertions as described [here](https://stackoverflow.com/questions/15614909/enable-debug-output-for-optimization-passes-from-clang).

The following seems to work with for me:
```bash
echo "-mllvm -debug" > mysaargs.txt

CC_ANALYZERS_FROM_PATH=1 \
PATH="/home/me/git/llvm-project/build/debug/bin:$PATH" \
CodeChecker analyze --analyzers=clangsa --capture-analysis-output --saargs mysaargs.txt -o reports compile_commands.json --verbose debug

cat reports/success/*.plist.stderr.txt
```

However, note that `CodeChecker` will **only** invoke the Clang Static Analyzer frontend, thus no `opt` passes will ever run, hence **no** debug prints will be triggered embedded there.

PS: in the Clang Static Analyzer we use these `LLVM_DEBUG()` macros, [here](https://github.com/llvm/llvm-project/blob/main/clang/lib/StaticAnalyzer/Checkers/GenericTaintChecker.cpp#L797-L802) for example. And it gets triggered by the short script I proposed.
PS2: You don't need to invoke `CodeChecker` with `--verbose debug`, it will work just fine without it.

**Comment by Logyiyi** [comment]
> First of all, you need to have a clang with debug assertions as described [here](https://stackoverflow.com/questions/15614909/enable-debug-output-for-optimization-passes-from-clang).
> 
> The following seems to work with for me:
> 
> ```shell
> echo "-mllvm -debug" > mysaargs.txt
> 
> CC_ANALYZERS_FROM_PATH=1 \
> PATH="/home/me/git/llvm-project/build/debug/bin:$PATH" \
> CodeChecker analyze --analyzers=clangsa --capture-analysis-output --saargs mysaargs.txt -o reports compile_commands.json --verbose debug
> 
> cat reports/success/*.plist.stderr.txt
> ```
> 
> However, note that `CodeChecker` will **only** invoke the Clang Static Analyzer frontend, thus no `opt` passes will ever run, hence **no** debug prints will be triggered embedded there.
> 
> PS: in the Clang Static Analyzer we use these `LLVM_DEBUG()` macros, [here](https://github.com/llvm/llvm-project/blob/main/clang/lib/StaticAnalyzer/Checkers/GenericTaintChecker.cpp#L797-L802) for example. And it gets triggered by the short script I proposed. PS2: You don't need to invoke `CodeChecker` with `--verbose debug`, it will work just fine without it.

Thank you very much! It is helpful!
