### ISSUE TITLE
Merge multiple runs

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#365]
It is possible that reanalyzing a project takes to much time just to update some run results.
It would be nice if the results from multiple runs could be merged into one run.

**Comment by whisperity** [comment]
@gyorb How much of this issue is covered by #688?

**Comment by gyorb** [comment]
The idea here was different. This feature would enable to merge two runs after the storage of the reports for both separate runs is done.

For example you have run1 for submodule1 and run2 for submodule2 you do some commenting or status modification in both runs, but then you realize it is the same project and you only want one run0 with the results from both run1 and run2.
With the new db schema this feature could be easily done, because the issue history will belong to an issue and not stored separately for each run so history migration should not be done.
