### ISSUE TITLE
Add some progress report to analyzer info messages

### ISSUE THREAD

**Issue by r0mai** [Ericsson/codechecker#370]
Big projects can take hours to finish, and it would be nice to know at least approximately how much stuff there is left to analyse.

As a first step I was thinking about a simple (ninja style) indicator on how many steps are left from the analysis process.

Something like:

```
[...]
[INFO] - [34/705] clangsa analyzed A.cpp successfully.
[INFO] - [35/705] clangsa analyzed B.cpp successfully.
[INFO] - [36/705] clangsa analyzed C.cpp successfully.
[INFO] - [37/705] clangsa analyzed D.cpp successfully.
[INFO] - [38/705] clangsa analyzed E.cpp successfully.
[INFO] - [39/705] clangsa analyzed F.cpp successfully.
[...]
```

wdyt?

**Comment by Xazax-hun** [comment]
+1 :) Good idea!
