### ISSUE TITLE
Links to clang error documentation don't work

### ISSUE THREAD

**Issue by rdanter** [Ericsson/codechecker#3701]
**Describe the bug**
When looking at a bug report in a browser, there is a link called "checker documentation". Clicking this pops up a window with a Documentation URL, Profile and Severity. The URLs are out of date, at least in some cases, eg this one:

https://clang.llvm.org/extra/clang-tidy/checks/misc-definitions-in-headers.html 

and this:

https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-special-member-functions.html

**CodeChecker version**
6.19.1

**To Reproduce**
1. open browser to CodeChecker server
2. click on a "run" name
3. click on a file link of one of the bug reports
4. click on the "checker documentation" link in the bug info box
5. click on the Documentation URL

**Expected behaviour**
The clang doc should open, but instead you get a Not Found error.

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Firefox
 - Version: 102

**Additional context**
n/a

**Comment by vChavezB** [comment]
just further information. I noticed that the clang urls have changed and now have a subdir for each category

example

https://clang.llvm.org/extra/clang-tidy/checks/misc-definitions-in-headers.html

is now 

https://clang.llvm.org/extra/clang-tidy/checks/misc/definitions-in-headers.html
