### ISSUE TITLE
CodeChecker to support clang-tools like compilation database lookup (multi-root workspace)

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#3708]
CodeChecker should support an analysis mode where for each source file,
it tries to find the closest compile_commands.json file up in the directory hierarchy starting from the source file.

clangd and clang-tidy works this way: https://clangd.llvm.org/installation.html

clangd will look in the parent directories of the files you edit looking for it, and also in subdirectories named build/. For example, if editing $SRC/gui/window.cpp, we search in $SRC/gui/, $SRC/gui/build/, $SRC/, $SRC/build/, …

This feature would allow the analaysis of multi-root projects also in the vscode plugin https://github.com/Ericsson/CodecheckerVSCodePlugin/issues/113

**Comment by bruntib** [comment]
Done in #3815
