### ISSUE TITLE
how to add codechecker to windows path?

### ISSUE THREAD

**Issue by Ryyoukka** [Ericsson/codechecker#3782]
how to add codechecker to windows path?

**Comment by bruntib** [comment]
Would you think this answers your question? https://www.computerhope.com/issues/ch000549.htm
Thank you!

**Comment by bruntib** [comment]
Hi,

I would close this ticket. Please, elaborate the question if any. However, we don't really use CodeChecker in Windows. It would be a nice experience to see if it works or it needs some generalization in the code.

Thank you!
