### ISSUE TITLE
Support python 3 default systems

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#379]
Arch linux and the newest ubuntu (?) has python3 by default as python. This renders the codechecker unusable. We should use the python2 binary in case the python is referring to python3.

**Comment by Xazax-hun** [comment]
Note that, in this case pip2 should be used instead of pip to install the requirements. The documentation should be updated to reflect this.

**Comment by gyorb** [comment]
There is already an issue for python3 support #170. But yes the documentation can be updated.

**Comment by Xazax-hun** [comment]
I think this is two separate issue. One is to update the code to run with python3, the other is to choose the python2 interpreter whenever it is available. In case it takes too much effort to update to python3 rigth away, it might make sense to do a quick fix to attempt to use python2 whenever possible, until the transition is done.

**Comment by Xazax-hun** [comment]
Note that, this is only a problem if somebody is not using a virtualenv. (which will have python as a symlink to pythonel2)
