### ISSUE TITLE
Option to force debug build

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#380]
For the best results when using the static analyzer, the code should be built in debug mode. In this mode asserts are usually enabled. Asserts can provide the analyzer with many useful information.

**Comment by gyorb** [comment]
With the saargs and tidyargs config options you can forward extra compiler flags for the analysis.
Is it possible that the added extra debug compiler flag will conflict with the original build flags (if there is a -O3 flag)?
We can extend the documentation and suggest the users to build and analyze their projects in debug mode. I'm not sure CodeChecker should handle this.

**Comment by Xazax-hun** [comment]
Scan build has an option to force debug builds. But I think it is definitely a good idea to update the documentation to suggest this.

**Comment by Xazax-hun** [comment]
I think O3 does not conflict with the concept of "debug build" in this case. O3 should only change codegen/optimizations. But it is perfectly reasonable to optimize a build with debug symbols and asserts turned on. This is what CMake does when a project is build using the RelWithDebugInfo configuration.

**Comment by baloghadamsoftware** [comment]
My suggestion: do not forward -DNDEBUG (defines NDEBUG which disables asserts) from gcc to clang.
