### ISSUE TITLE
Example script on website is broken

### ISSUE THREAD

**Issue by geeksmith** [Ericsson/codechecker#3805]
**Describe the bug**
The script at https://codechecker.readthedocs.io/en/latest/script_update/ does not work. There are three bugs:
- it stores $MASTER_EXISTS and checks for $PREVIOUS_EXISTS
- using quotes around $ANALYZER_OPTIONS when calling CodeChecker results in an error
- $DIFF_CMD is escaped and indented incorrectly and does not run

And a couple of style issues:
- variables do not need to be surrounded by curly braces in most cases
- using a file to store status is overkill when a variable will do

**CodeChecker version**
N/A

**To Reproduce**
Download and run the script.

**Expected behaviour**

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: N/A
 - Version: 6.21.0

**Additional context**
N/A

**Comment by geeksmith** [comment]
Pull request #3804 submitted

**Comment by bruntib** [comment]
Fixed by #3804.
