### ISSUE TITLE
Support clang-tidy and static analyzer notes

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#381]
Clang tidy sometimes output notes. These notes are connected to a warning and provides the user with additional information e.g.: where a variable was declared. This is not part of path sensitive information. It would be great to store/display those notes.

Also note that, the clang static analyzer will also support and emit notes in the next release: https://reviews.llvm.org/D24278

**Comment by gyorb** [comment]
Notes are parsed from the clang-tidy output and a bug event is created from it in the generated plist.
I think we should still use the plist output from the clang static analyzer even if notes are supported in the next release. A plist output would be better from clang-tidy too.

**Comment by Xazax-hun** [comment]
I am not sure that an event is a good way to store a note. Sometimes i get unspecified empty name results from tidy. Maybe there is a buf lurking in the output parser.

**Comment by Xazax-hun** [comment]
This requires work at both the client and server side and the schema will change.

**Comment by Xazax-hun** [comment]
Note that, the notes are not emitted to the plist yet: https://github.com/llvm-mirror/clang/blob/master/lib/StaticAnalyzer/Core/PlistDiagnostics.cpp#L284

**Comment by gyorb** [comment]
Could you provide some cland-tidy output which we fail to parse correctly?

**Comment by Xazax-hun** [comment]
Oh, the issue I experienced might be unrelated to the title.
Here is a sqlite database of a run that has some check results without name: https://dl.dropboxusercontent.com/u/4131903/codechecker.sqlite.tar.lz

**Comment by gyorb** [comment]
I've created a new issue for the check results without the name, that problem should be discussed further there.

**Comment by csordasmarton** [comment]
I think this issue has already been solved in #1818. What do you think @gyorb?

**Comment by gyorb** [comment]
Yes, it is done we can close this.
