### ISSUE TITLE
Bug tree shows [+] for nodes without any children

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#382]
The bug overview for a file in the web client shows the [+] button for every element until they are opened. When a node without descendants is opened, the [+] goes away, otherwise, it turns into a [-].

It would be better if the icon wouldn't show at all for nodes without any children... having this plus sign can mislead the user.

-- Could be part of #353

**Comment by gyorb** [comment]
I think this should be implemented in a separate pull request not in #353. There are already many things in that refactoring.
