### ISSUE TITLE
[web] Cannot set review status of bug `B` to `X` after setting bug `A` to `X` in the same file **without** going back to the Reports list

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#3830]
**Describe the bug**
The review status drop-down does not allow selecting the same option when an option is already selected, even between separate reports. Related to #3026.

**CodeChecker version**
6.21.0 - 6.22.2

**To Reproduce**
Steps to reproduce the behaviour:

1. Have a run with two bugs in the same file, both "Unreviewed".
2. Open bug `A` from the "Reports" list.
3. Change the status to "Confirmed bug".
4. Switch to bug `B` **within** the file (the left-hand side tree view), without going back to the full report list.
5. Review status stays "Confirmed bug". I **cannot** set bug **`B`** to the same "Confirmed bug" without first setting it to "Unreviewed" (with an empty comment) and then setting it to "Confirmed bug" with a meaningful comment.
6. Alternatively, I need to go back to the run-level "Reports" list and remember which file I was in.

**Expected behaviour**
Whether the change of the review status is allowed should be checked every time the UI option is clicked? This sounds like some ViewModel caching issue.

**Comment by vodorok** [comment]
Are you clicking on the line which opens the tree element? (blue `bug` icon lines) Clicking on these not changes the report selection
Clicking on the `note tag`  row does (or any other bug path element referencing child).
![image](https://user-images.githubusercontent.com/23135800/220633208-0464419a-441a-41c6-85ed-7dd2b1b31253.png)

I agree, that changing the behaviour of the selection so that clicking the top-level `bug` items, (the rows starting with bug icons) should change the selected report.

**Comment by whisperity** [comment]
I think it's with the bug message (what's highlighted in your picture). But the problem isn't that clicking the `Lxx - checker-name` line doesn't swap the report, it's that clicking on the message **and** changing the report still doesn't update the review status dropdown.

**Comment by whisperity** [comment]
@cservakt Can you check if #4082 also fixed this issue? It falls in line with the various other similar issues so I'd guess it should also be fixed...

**Comment by cservakt** [comment]
#4082 almost completely resolved. You can set the review status of the report, and the review status dropdown menu is also updated when changing the report on the sidebar.
The only remaining problem is that the sidebar isn't updated when the review status changes. I've already started an another PR that will hopefully fix it.

**Comment by whisperity** [comment]
Okay I checked in practice and v6.23 solved this!
