### ISSUE TITLE
Possible to configure `cppcheck` to use `c++20` instead of `c++2b`?

### ISSUE THREAD

**Issue by Eshnek** [Ericsson/codechecker#3844]
Hello!

When running analysis on my project, I get this error:
```
Analyzing Section.test.cxx with cppcheck  failed!
cppcheck: error: unrecognized command line option: "--std=c++2b".
```

This is because `cppcheck` only supports up to `C++20` currently.
Is there a way to configure the standard for `cppcheck` to be `C++20`?

I am trying to use `--analyzer-config`, but I get `Analyzer option in wrong format: "cppcheck:std=c++20"`:
```
// .codechecker.json
{
    "analyzer": ["--analyzer-config=\"cppcheck:std=c++20\""] // Also tried -std=c++20, --std=c++20 
}
```

**Comment by vodorok** [comment]
Hi @Eshnek ! The language standard specified with the --std flag in the compilation command is automatically translated into the proper Cppcheck language standard parameter. There is no `std` analyzer config for it, which you tried to use.
The following compilation-commands.json file
``` json
[
    {
        "directory": "/home/ekutgab/ws/debug/pch",
        "command": "/usr/bin/clang --std=c++20 -I ./include/header.h ./source.cpp",
        "file": "./source.cpp"
    }
]
```
results in the following (simplified for this comment) cppcheck invocation:
```
cppcheck --std=c++20 -I /ws/debug/pch/include/header.h --plist-output=/ws/debug/pch/reports/cppcheck/ /ws//debug/pch/source.cpp  
```

**Comment by Eshnek** [comment]
Thanks @vodorok!

I was able to configure CMake to this effect.
