### ISSUE TITLE
Does Codechecker Supports hooking MSBuild like it does for the Makefile?

### ISSUE THREAD

**Issue by VenoVeno** [Ericsson/codechecker#3846]
Codecheckers takes all the GCC Commands and forwards to Clang Compiler. 
Can it be done for the same way for MSBuild?

**Comment by bruntib** [comment]
The command `CodeChecker log` is capturing `exec()` calls and logs the compiler invocations. The possible compiler names are listed in `CC_LOGGER_GCC_LIKE` environment variable. For further details see this documentation: https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/user_guide.md#log
However, currently Microsoft platform is not supported by CodeChecker.

**Comment by VenoVeno** [comment]
Hi [bruntib](https://github.com/bruntib). 
Thanks for your reply.

Is it possible to compile MSVC devloped Source with Clang compiler? 
As mentioned Clang supports MSVC? [link](https://clang.llvm.org/docs/MSVCCompatibility.html).

**Comment by bruntib** [comment]
Hi,

CodeChecker does some transformation of (mainly) gcc build commands: https://github.com/Ericsson/codechecker/blob/master/analyzer/codechecker_analyzer/buildlog/log_parser.py
I'm not sure how this works together with MSVC. It might work, but we don't support MSVC compatibility. It would be interesting to hear your experiences with it. And if it turns out that MSVC also works together with CodeChecker, then we can consider supporting it in the future.

Thanks!

**Comment by VenoVeno** [comment]
Hi,

Clang also doesn't provide full support for MSVC. https://github.com/llvm/llvm-project/issues/59997
Tried the experimental flags like  -fms-compatibility, -fdelayed-template-parsing, -fms-extensions

> And if it turns out that MSVC also works together with CodeChecker, then we can consider supporting it in the future.

That's good to know. :crossed_fingers:

**Comment by whisperity** [comment]
@VenoVeno If you can craft a compilation database without using our logger, either by using and emitting it from CMake or looking how MSBuild can generate a compilation database, CodeChecker *might* be capable of running the analysis, see #555. If you gather some experience here we would be happy to hear &mdash; as far as I understand, none of us in the team use Windows for development, so Windows support has not been in scope for us for quite a while.

Whether Clang itself can consume some specific Windows or 3rd-party library on Windows is not solvable from CodeChecker's side; unless there is some magic flag that we need to inject to Clang that's not present in the original compilation database &mdash; that's all we can do&hellip;

**Comment by VenoVeno** [comment]
Hi, @whisperity 

> If you can craft a compilation database without using our logger, either by using and emitting it from CMake or looking how MSBuild can generate a compilation database.

Though MSBuild emits compilation database, it will invoke the Visual Studio as it is a compiler.

> CodeChecker might be capable of running the analysis

If so, does Codechecker supports the compiler argument parsing? I don't have any idea about how the arguments are parsed. Some arguments like /GS /I /W3 /D. Codechecker won't parse these arguments right? The arguments are required for MSVC Project to build.

> If you gather some experience here we would be happy to hear

The AST is generated by the Clang Compiler, forwarding all the (GCC, G++) arguments in the format of Clang compiler understanding. Correct me if i'm wrong about it. If that's the case though i manage to get the compilation database, still the AST generation requires compilation [Ref here](https://github.com/Ericsson/codechecker/issues/3800#:~:text=So%20compilation%20is%20needed%2C%20because%20the%20AST%20is%20built%20in%20this%20step.%20This%20can%27t%20be%20done%20without%20having%20a%20declaration%20for%20every%20named%20entity%20(variables%2C%20functions%2C%20etc.)). The MSVC Code should be able to parse by the Clang Compiler, whereas Clang doesn't have full support for the MSVC Source :disappointed: 

https://github.com/llvm/llvm-project/issues/59997

> unless there is some magic flag that we need to inject to Clang that's not present in the original compilation database

If Clang have a fault tolerant parser using any flags to generate AST it would be better but it doesn't have one https://github.com/llvm/llvm-project/issues/59700.

**Comment by whisperity** [comment]
> If so, does Codechecker supports the compiler argument parsing? I don't have any idea about how the arguments are parsed. Some arguments like /GS /I /W3 /D. Codechecker won't parse these arguments right? The arguments are required for MSVC Project to build.

Okay, that's a game-breaking thing on our end. And I have no idea what those flags mean, so it would definitely require non-trivial effort to rewrite an MSVC compile command onto a GCC (or Clang) compile command.

> The MSVC Code should be able to parse by the Clang Compiler, whereas Clang doesn't have full support for the MSVC Source :disappointed:

This is unfortunately out of our hands (at least in the CodeChecker project). The best we could do (but do not do right now) is to craft the compile command necessary to at least call Clang with *some* sensible input parameters. If despite this effort Clang can't parse the input and start the analysis, then what CodeChecker will do (and actually does if the original project is working on Linux but somehow fail the analysis) is to report which source files could not be analysed. And if some parts of the project *do* analyse, we can show results from that part at least.

**Comment by whisperity** [comment]
(I close this question purely to ensure we have the meta-discussion about Windows continuously in #555 instead.)

**Comment by VenoVeno** [comment]
> It would definitely require non-trivial effort to rewrite an MSVC compile command onto a GCC (or Clang) compile command.

Yes. That needs lot of effort in implementing all possibles.

> The best we could do (but do not do right now) is to craft the compile command necessary to at least call Clang with some sensible input parameters. If despite this effort Clang can't parse the input and start the analysis.

I agree.

> And if some parts of the project do analyse, we can show results from that part at least.

As most of the files are Visual C++ implementation with windows Windows SDK and API dependency, all the source parsing failed.

**Anyways. Thanks for the awesome tool. :clap:**
