### ISSUE TITLE
reports are not clickable in diff view 

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#387]
javascript error uncaught type error cannot read property runId of undefined

**Comment by sylvestre** [comment]
Any news? This makes codechecker unusable. Thanks

**Comment by bruntib** [comment]
I've committed a pull request to solve this issue. However this solution is quite a hack and still concludes a non-intuitive result described below.

The difference type (i.e. new, resolved, unresolved) is an orthogonal query for the other filter fields. It is very unlikely that somebody wants to check the unresolved, high severity issues from path `p1` and the "division by zero" errors from path `p2` which are already resolved.

The easiest solution for now to implement was to always consider only the first "difference type" field in case of multiple filters. The final and elegant solution should be provided by #348.
