### ISSUE TITLE
Make `Analyzing <> with clangsa CTU failed!` non-fatal?

### ISSUE THREAD

**Issue by LebedevRI** [Ericsson/codechecker#3946]
I'm trying to enable CTU analysis on a project: https://github.com/darktable-org/rawspeed/actions/runs/5432405993/jobs/9879426261?pr=306

I rely on the fact that `CodeChecker` exits with non-zero exit status
if the bugs were found to fail the build (is there some nicer way to do that?)
but unfortunately if CTU analysis fails on some files,
that also results in non-zero exit status.

Additionally, `--ctu-reanalyze-on-failure` appears to be at deprecated,
even though there are clearly some CTU bugs...

Are there some recommendations on how to deal with this?

**Comment by LebedevRI** [comment]
Ok, `--ctu-reanalyze-on-failure` solves my problem:
https://github.com/darktable-org/rawspeed/actions/runs/5432566751/jobs/9879687726?pr=306

And looks like it's not actually deprecated as of https://github.com/Ericsson/codechecker/pull/3823.

Thanks!

**Comment by bruntib** [comment]
Hi,
It's good if you managed to workaround the problem with `--ctu-reanalyze-on-failure`. I just want to add that this PR might be related too: https://github.com/Ericsson/codechecker/pull/3943.
