### ISSUE TITLE
Release 6.22.2 not available in PyPI

### ISSUE THREAD

**Issue by petermbauer** [Ericsson/codechecker#3966]
**Describe the bug**
The release was done already 2 weeks ago but it is not available via https://pypi.org/project/codechecker/

It would be very helpful due to the `PyYAML==5.4.1` dependency used by previous versions being broken: https://github.com/yaml/pyyaml/issues/724

**Comment by petermbauer** [comment]
The release already appeared in the PyPI.

**Comment by bruntib** [comment]
Unfortunately the PyPI package doesn't work: it can't do the logging phase. We are aware of the issue and working on it.

**Comment by petermbauer** [comment]
The package did work for me but i was hit by #3968

**Comment by petermbauer** [comment]
:-( Unfortunately i can not go back to 6.22.1 due to the `PyYAML==5.4.1` dependency which is broken for Python >3.9

**Comment by petermbauer** [comment]
It would have been very helpful to have a `6.22.2` with the `PyYAML` dependency bump only and a `6.23.0` then instead of the `6.22.2`.

**Comment by bruntib** [comment]
A fixed version has been deployed: https://pypi.org/project/codechecker/6.22.2.post1/

**Comment by bruntib** [comment]
Unfortunately, we support only the latest CodeChecker version, and don't backport fixes or dependency upgrades to older versions. However, some Windows-specific fixes have been added to the master branch. It would be most helpful if you could provide some feedback about the master branch if there are still issues under Windows. We plan to release the next CodeChecker version at the beginning of December that is supposed to contain all these improvements. Thank you!

**Comment by petermbauer** [comment]
btw. `6.23.0-rc1` does also not show up: https://pypi.org/project/codechecker/#history

**Comment by bruntib** [comment]
Sorry, I clicked the "close" button accidentally. We can keep it opened until we release the next version, but unfortunately I can't guarantee that a fixed 6.22.1 would be deployed even in a best effort manner.

**Comment by petermbauer** [comment]
I would really like to test the master but don`t know how to install it. Also wanted to try out the 6.23.0-rc1 but its not available via PyPI.

**Comment by petermbauer** [comment]
Thanks a lot, the installation works.
