### ISSUE TITLE
ldlogger.so cannot be preloaded, wrong path

### ISSUE THREAD

**Issue by ielpo** [Ericsson/codechecker#3980]
**Describe the bug**
When executing `CodeChecker check`, the library _ldlogger.so_ cannot be found.
I checked the path: there is a _"x86_64"_ in the requested path, in the actual path there is not.

Requested path: `/root/codechecker/.venv/lib/python3.11/site-packages/codechecker_analyzer/ld_logger/lib/x86_64/ldlogger.so`

Actual path: `/root/codechecker/.venv/lib/python3.11/site-packages/codechecker_analyzer/ld_logger/lib/ldlogger.so`

**CodeChecker version**
Installed from pip, git tag info 6.22.2

**To Reproduce**

1. Source venv
2. Download and extract source for htop to `~/htop-3.2.2` [Link](https://github.com/htop-dev/htop/archive/refs/tags/3.2.2.tar.gz)
3. Execute `CodeChecker check -b "cd ~/htop-3.2.2 && ./autogen.sh && ./configure && make" -o ~/results`

**Expected behavior**
I expect the analysis to run.

**Desktop (please complete the following information)**
 - OS: Debian 12

**Comment by bruntib** [comment]
There is a solution to the problem in this PR: https://github.com/Ericsson/codechecker/pull/3976. This will be available soon.

**Comment by bruntib** [comment]
Fixed by #3976
