### ISSUE TITLE
[WARNING] - Not a valid host entry

### ISSUE THREAD

**Issue by RobertoFioravanti** [Ericsson/codechecker#4025]
**Describe the bug**
Authentication failed specifying **host** like `http://192.168.1.100/my-project` in `.codechecker.passwords.json`.
Authentication is successfull specifying **host** like` http://192.168.1.100/Default`
Credential validation does not accept '-' in the **host** field.

**CodeChecker version**
6.22.2

**To Reproduce**

1. Configure a _user_ on server side and enable authentication (I tried dictionary)
2. On server side, to products: Default  and my-project
3. Client side: provide  `.codechecker.passwords.json` :
```
{
  "client_autologin" : true,
  "credentials": {
    "http://192.168.1.100/my-project" : "user:12345"
  }
}
```

4. Login 

**Behavior**
[INFO 2023-09-28 16:13] - Checking local passwords or tokens in /home/runner/.codechecker.passwords.json
[WARNING 2023-09-28 16:13] - Not a valid host entry: ***.
[INFO 2023-09-28 16:13] - No saved tokens.
[INFO 2023-09-28 16:13] - Checking for local valid sessions.
[ERROR 2023-09-28 16:13] - Invalid pre-configured credentials.
[ERROR 2023-09-28 16:13] - Your password has been changed or personal access token has been removed which is used by your "/home/runner/.codechecker.passwords.json" file. Please remove or change invalid credentials.

**Expected behaviour**
This behavior is obtained in this case
```
{
  "client_autologin" : true,
  "credentials": {
    "http://192.168.1.100/Default" : "user:12345"
  }
}
```
[INFO 2023-09-28 16:32] - Checking local passwords or tokens in /home/runner/.codechecker.passwords.json
[INFO 2023-09-28 16:32] - Checking for local valid sessions.
[INFO 2023-09-28 16:32] - Logging in using pre-configured credentials...
[INFO 2023-09-28 16:32] - Authentication successful.

**Additional context**
none

**Comment by whisperity** [comment]
`"http://192.168.1.100/my-project"`˙is a **product** URL, not a server/host URL, as per the output of `CodeChecker cmd login --help`:

```
  --url SERVER_URL      The URL of the server to access, in the format of '[http[s]://]host:port'. (default: localhost:8001)
```

[Authentication](http://codechecker.readthedocs.io/en/latest/web/authentication/#preconfigured-credentials) is done against the entire *server* running under a specific host (and port). Access rights to individual products are decided serverside, so there is no need (and no option) to authenticate just for one specific product.

The right format in the `.codechecker.passwords.json` should be:

```
{
  "client_autologin" : true,
  "credentials": {
    "http://192.168.1.100" : "user:12345"
  }
}
```

**Comment by RobertoFioravanti** [comment]
ok.
product URL is what I'm able to find in `.codechecker.passwords.json` in [codechecker-analysis-action-test](https://github.com/whisperity/CodeChecker-Action/blob/master/src/store-pre.sh)

**Comment by whisperity** [comment]
Oh, nice catch. That was likely a mistake and it works like so by accident. We will need to fix that action script to appropriately cut the "product endpoint" from the URL.
