### ISSUE TITLE
Question: do client support ssl certificates ?

### ISSUE THREAD

**Issue by RobertoFioravanti** [Ericsson/codechecker#4026]
I would like to know if client is able to store to a ssl Codechecker server.

**Comment by whisperity** [comment]
Yes. You need to provide **`cert.pem`** (for the public key certificate, potentially including the public keys in the signature chain up to some trusted CA) and **`key.pem`** (the private key corresponding to the server's certificate) files **with these exact names** under the `config-directory` of the to-be-started server (by default the `config-directory` is `~/.codechecker/`, where the `config.sqlite` file and the `server_config.json` also lives).

If you run an SSL/TLS-enabled server, client commands (such as `CodeChecker cmd` and `CodeChecker store`) **must** use `https://` in the server and product URLs. You can still run the server on an arbitrary port, the HTTPS port `443` is just the default, but that is not enforced. So things like `https://example.com:9999` is valid.

```
  -f CONFIG_DIRECTORY, --config-directory CONFIG_DIRECTORY
                        Directory where CodeChecker server should read server-specific configuration (such as authentication settings, TLS certificate (cert.pem) and key (key.pem)) from.
                        (default: /home/whisperity/.codechecker)
```

The clients use the built-in certificate stores of the operating system, there is no custom configuration to be done on the client side of CodeChecker. As long as you have a certificate signed by a trusted authority, or you install a self-signed certificate appropriately installed in your system, the client will accept it.
