### ISSUE TITLE
...ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored

### ISSUE THREAD

**Issue by rdong8** [Ericsson/codechecker#4053]
**Describe the bug**

When trying to use CodeChecker with the VS Code extension, I'm unable to view the errors detected by CodeChecker. I cannot access the logs as there are errors about LD_PRELOAD.

**CodeChecker version**
You can get version info by running `CodeChecker version`.

6.22.2 installed through pip using system Python 3.10 installation.

**To Reproduce**
Steps to reproduce the behaviour:

1. Click "Preview CodeChecker log in terminal":

![image](https://github.com/Ericsson/codechecker/assets/66289396/a62b27f5-dd8b-4f0f-9882-5134320bc9b5)

2. Run the resulting command in the terminal:

![image](https://github.com/Ericsson/codechecker/assets/66289396/8dcd1a32-f528-4cb3-af0f-7ea8a0af2157)

This is the result:

```bash
 % ~/.local/bin/CodeChecker log --output /u4/rydong/cs246e/.codechecker/compile_commands.json --build make
[INFO 2023-10-20 18:23] - Starting build...
[INFO 2023-10-20 18:23] - Using CodeChecker ld-logger.
ERROR: ld.so: object '/u4/rydong/.local/lib/python3.10/site-packages/codechecker_analyzer/ld_logger/lib/x86_64/ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/u4/rydong/.local/lib/python3.10/site-packages/codechecker_analyzer/ld_logger/lib/x86_64/ldlogger.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
make: *** No rule to make target 'runSuite', needed by 'test'.  Stop.
[INFO 2023-10-20 18:23] - Build failed.
```

**Expected behaviour**
What you expected to happen.

The log command is run successfully.

**Desktop (please complete the following information)**
 - OS: Ubuntu 22.04.3

**Additional context**
Add any other context about the problem.

**Comment by bruntib** [comment]
The issue has been solved by #3976.
We have deployed a fixed CodeChecker version to Pypi, please install that: `pip install codechecker==6.22.2.post1`
