### ISSUE TITLE
Setting review status with file

### ISSUE THREAD

**Issue by m-luk** [Ericsson/codechecker#4087]
**Describe the bug**
_Not really a bug but possibly documentation lacking info:_
According to [setting-with-config-file](https://github.com/Ericsson/codechecker/blob/88af1ff15131644da34fff27fafcb661b485bda6/docs/analyzer/user_guide.md#setting-with-config-file), it is possible to set review status with external file, but there is no info how to do it. 

Is this feature still available and by what command can this file be imported into parse/analyze?

This feature would be very helpful to batch disable things like magic number errors etc.

**CodeChecker version**
6.22.2

**To Reproduce**
Documentation issue.

**Expected behaviour**
Documentation issue.

**Desktop (please complete the following information)**
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

**Comment by m-luk** [comment]
Ok, found it.

For other dummies like me: this is not yet released as of 6.22.2, even though it is available in the doc. https://github.com/Ericsson/codechecker/releases/tag/v6.23.0-rc1 introduces it.

**Comment by whisperity** [comment]
> This is not yet released as of 6.22.2, even though it is available in the doc

This must be a mistake, as if I check the code for `v6.22.2` (commit a3d35cfd509b995187288cd8631446415a334257), the linked part is **not** available.

The linked commit, 88af1ff15131644da34fff27fafcb661b485bda6, was first available in tag `v6.23.0-rc2`.
