### ISSUE TITLE
allow for patterns in skip file - or add whitelist strategy

### ISSUE THREAD

**Issue by torbjoernk** [Ericsson/codechecker#41]
Thanks for this tool! Looking awesome right now :+1: 

My aim is to provide a skip file for CodeChecker within my project's source tree. But I want to only parse my own code and not optional and potential 3rd-party libraries. Thus, I can not put in absolute paths such as `/usr/include`. As well it's not possible to exclude specific files in the project's source tree (e.g. `<PROJECT>/include/3rdparty`) as I can not make any assumptions on the location of the project tree.

I tried specifying patterns such as `eigen3/`, `*/eigen3`, `/boost` or `*/boost` in a skip file. But that did not work. Only absolute paths such as `/usr/include/eigen3` are working.

It would be awesome being able to exclude paths based on patterns or - even better - whitelist only specific files or paths only in the project's source tree.

**Comment by igalex** [comment]
Hi!

The skip file format is just changed. Now you can use glob patterns and allow/reject signs in skip files. You can find its documentation [here](https://github.com/Ericsson/codechecker/blob/master/docs/user_guide.md#skip-file).
