### ISSUE TITLE
CodeChecker not working with cppcheck premium by Cppcheck Solutions.

### ISSUE THREAD

**Issue by robertpaananen** [Ericsson/codechecker#4133]
**Describe the bug**
When using cppcheck premium by Cppcheck Solutions CodeChecker crashes and gives an error stating that `TypeError: '>=' not supported between instances of 'NoneType' and 'StrictVersion'`. I believe this is due to the output from `cppcheck --version` differing between the two cppcheck versions.  
Cppcheck free version: `$cppcheck --version -> Cppcheck 2.7`  
Cppcheck paid version: `$cppcheck --version -> Cppcheck Premium 23.9.0`

The whole error log looks like this:  
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/codechecker_common/cli.py", line 167, in main
    add_subcommand(subparsers, subcommand,
  File "/usr/local/lib/python3.10/dist-packages/codechecker_common/cli.py", line 57, in add_subcommand
    command_module.add_arguments_to_parser(sc_parser)
  File "/usr/local/lib/python3.10/dist-packages/codechecker_analyzer/cmd/analyzers.py", line 54, in add_arguments_to_parser
    working_analyzers, _ = analyzer_types.check_supported_analyzers(
  File "/usr/local/lib/python3.10/dist-packages/codechecker_analyzer/analyzers/analyzer_types.py", line 187, in check_supported_analyzers
    if not analyzer.version_compatible(analyzer_bin, check_env):
  File "/usr/local/lib/python3.10/dist-packages/codechecker_analyzer/analyzers/cppcheck/analyzer.py", line 360, in version_compatible
    if analyzer_version >= StrictVersion("1.80"):
TypeError: '>=' not supported between instances of 'NoneType' and 'StrictVersion'
```

**CodeChecker version** 
 ```
---------------------------------------------------------------
Kind                 | Version
---------------------------------------------------------------
Base package version | 6.22.2
Package build date   | 2023-10-30T11:55
Git commit ID (hash) | a3d35cfd509b995187288cd8631446415a334257
Git tag information  | 6.22.2
---------------------------------------------------------------
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Remove or uninstall regular version of cppcheck.
2. Install cppcheck premium
  i. Linux instructions https://cppchecksolutions.com/cppcheck-premium-linux-installation
3. Add /opt/cppcheckpremium/ to path.
4. Run a command like `CodeChecker analyzers`

**Expected behaviour**
I expected CodeChecker to be able to analyze with cppcheck premium. Currently I can only get it to work by first running cppcheck and then converting the report with `report-converter`.

**Desktop (please complete the following information)**
 - OS: Linux
 - Version: Ubuntu 22.04 on WSL

**Comment by whisperity** [comment]
This should be an easy fix, I guess we're somewhere reading the word "premium" as if it was a version number.

Unfortunately, I'm not sure if we knew that a premium version existed — to me, this is brand new information.

Thank you for providing the example output, it is likely we will not be able to test this directly due to the lack of a valid premium licence.

**Comment by robertpaananen** [comment]
Hi,
A premium license is not needed to reproduce this. It will work the same as the regular cppcheck if you do not use any premium functionality (for example misra-c-2023 or misra-c++-2008 standard). You should be able to reproduce this with just the information provided in the issue.
