### ISSUE TITLE
Facebook Infer analyzer support

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#4189]
Add support for facebook infer analyzer execution support for C/C++.
https://github.com/facebook/infer

CodeChecker should be able to 
* List checkers: CodeChecker checkers
* Checkers should have "infer" prefix: infer.biabduction_memory_leak
* Execute analysis: `CodeChecker analyze --anlayzers infer ./compile_commands.json`
* Enable/disble checkers for the analysis:` CodeChecker analyze --analyzers infer -e infer.biabduction_memory_leak`
* Enable storing analysis results `CodeChecker store ./report-dir --url https://...`
* Document how the analyzer is supported in 
** https://github.com/Ericsson/codechecker/blob/master/docs/analyzer/checker_and_analyzer_configuration.md
** https://github.com/Ericsson/codechecker/blob/fa1d14f624414056b6ad2d04454b88060d18c2f4/docs/analyzer/user_guide.md
** https://github.com/Ericsson/codechecker/tree/fa1d14f624414056b6ad2d04454b88060d18c2f4/docs#readme

**Comment by dkrupp** [comment]
You can check how gcc static analyzer was integrated in this PR:
https://github.com/Ericsson/codechecker/pull/4030/files

**Comment by vodorok** [comment]
- I would consider adding support to the latest release as well as the tip of the master. The latest release of Infer is almost 3 years old, but the tool is in active development.
- The file output of infer should be processed, instead of the stdout. 
- Consider supporting analyzer options if there are any.

**Comment by jay24rajput** [comment]
Can I try to work on this issue?
