### ISSUE TITLE
Failed to parse check name

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#423]
A new separate issue from #381 two things are discussed there and they might not be related. 

This might be connected to #422

@Xazax-hun 

> Oh, the issue I experienced might be unrelated to the title.
> Here is a sqlite database of a run that has some check results without name: > https://dl.dropboxusercontent.com/u/4131903/codechecker.sqlite.tar.lz

**Comment by bruntib** [comment]
Could you please recheck if this bug is still reproducible? A similar bug (#422) has just been closed because this seems to be fixed.

**Comment by whisperity** [comment]
Bump. @Xazax-hun Is this issue still applicable? The Dropbox link is `404`.

**Comment by Xazax-hun** [comment]
Updated link: https://www.dropbox.com/s/jjorapbq7q7myu6/codechecker.sqlite.tar.lz?dl=0
I did not try to reproduce since then.

**Comment by whisperity** [comment]
Is there a chance you may still have the source files (build json and such), or should we try to extract it from this database?

**Comment by csordasmarton** [comment]
I think this problem has already been solved. If no checker name can be found in the plist, we will set a default value to it:
https://github.com/Ericsson/codechecker/blob/1af4908d085c98375ef5ef7da0cdb640623f6567/codechecker_common/plist_parser.py#L107-L109
https://github.com/Ericsson/codechecker/blob/1af4908d085c98375ef5ef7da0cdb640623f6567/codechecker_common/plist_parser.py#L54-L63

I will close this issue now. If you still experience this problem please feel free to reopen it.
