### ISSUE TITLE
[web] Differential report storage

### ISSUE THREAD

**Issue by vodorok** [Ericsson/codechecker#4267]
In a CodeChecker repository, reports in the CodeChecker analysis runs are frequently repeated. It is not necessary to store those reports to server which are already there as an instance. A run should only reference a report and set the detection and review status states.

During the first phase the CodeChecker server should also return the hashes of the already existing reports to the CodeChecker client. This way the client could create a much smaller package that would be sent to the server for storage.

**Comment by whisperity** [comment]
Dupe #2658.
