### ISSUE TITLE
CodeChecker config file support

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#427]
it should be possible to configure codechecker from config file.

When many programmers use CodeChecker for analyzing their product, it is a common requirement to run the analysis using the same parameters: checker list, gcc_logger_like parameters etc.

The config file path should be possible to be defined from an optional command line parameter or from and environment variable (e.g. $CODECHECKER_CONFIG) . Thus the same config env can be set up for all developers.

- [x] analyzer #2268
- [ ] web #2611

**Comment by gyorb** [comment]
ClangSA:
Could we build this feature based on this clang [configuration file support proposal](http://lists.llvm.org/pipermail/cfe-dev/2016-November/051458.html)?

Clang-tidy:
How about generating clang-tidy configuration files?

A similar configuration file format would be useful so the users could just extend with some CodeChecker specific config options if needed.

**Comment by gyorb** [comment]
I would recommend the [python config](https://docs.python.org/2/library/configparser.html) format which is more human friendly than json if the users want to edit it.
```
[codechecker]
workspace = ~/.codechecker
suppress = ~/my_project/suppress_file
skipp = ~/my_poject/skip_file

[logger]
compilers_to_log = gcc,g++,clang

[pgdatabase]
host = localhost
port = 5432
name = codechecker 
username = codechecker

[server]
host = localhost
port = 8080
host-only = True

[checkers]
enable = core, unix
disable = misc

[saargs]
args = -I~/myinclude

[tidyargs]
args = -I~/myinclude


```
