### ISSUE TITLE
Update `pypi` to v6.24.2

### ISSUE THREAD

**Issue by pdgendt** [Ericsson/codechecker#4336]
**Is your feature request related to a problem? Please describe.**
The version on [pypi](https://pypi.org/project/codechecker/) is outdated.

**Describe the solution you would like**
Update the version on release.

**Describe alternatives you have considered**
N/A

**Comment by pdgendt** [comment]
Any update on 6.24.1 release?

**Comment by zebreus** [comment]
@whisperity Any progress on this? 6.24.1 is already released for 3 weeks and still not published on pypi.

**Comment by pdgendt** [comment]
Updated issue based on the latest release.

**Comment by zebreus** [comment]
6.24.1 and 6.24.2 have been released on pypi so this issue can be closed
