### ISSUE TITLE
--saargs parameters should be appended before any other compiler parameter

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#434]
if new include paths are given in the --saargs parameter, they should be appended before any other compilation parameter to clang. This way compiler defined included paths and defines can be redefined.

The current behavirour is appending the saargs content at the end.

**Comment by bruntib** [comment]
The order of compiler flags really does matter. I think that we can find cons and pros for both placing additional flags at the beginning of the list and at the end. The format of `saargs` could be made conformant with `tidyargs` to cover both cases, but the meaning of "before" and "after" is a bit different at ClangTidy:
```
clang_tool <flags_of_compilation> -- <flags_of_the_tool>
```
I'm not sure about the order, but "before" and "after" here means the left and right side of `--`, i.e. whether the flags are meant to be those of the tool or the compilation. This distinction doesn't exist at ClangSA.

So the final question is: would we like to handle "before" and "after" at ClangSA? If not, then which of these has more use-cases?

**Comment by dkrupp** [comment]
today we pass compiler defined include paths implicitly and not using --saargs, so this bug report is not relevan.t
