### ISSUE TITLE
Extend delete options

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#453]
To support better automatic cleanup the command line delete function could be extended where the user can give a time stamp or run name and every runs before that will be removed.

* ```-keep-after myrunname``` keep runs stored after this run (myrunname will not be deleted)
* ```-keep-before myrunname``` keep runs stored before this run (myrunname will not be deleted)
* ```-keep-after hour:day:month:year``` keep runs stored after the given date
* ```-keep-before hour:day:month:year``` keep runs stored before the given date

**Comment by bruntib** [comment]
I'd prefer `--all-after` instead of `--keep-after` if we would like to keep the given run. "before" and "after" mean strict relation. This way we could say "delete all after <run>". Of course this would apply for the other options too.

**Comment by bruntib** [comment]
Is it on purpose that the user can give hours in the timestamp? What if the user has multiple trial runs in an hour? Moreover wouldn't the `yyyy-mm-dd hh:ss` format be better? To answer my own question, maybe not, since it contains a space character which requires double quotes in the shell.

**Comment by bruntib** [comment]
One more notification: a flag name can't be used both for run names and timestamps. Should we introduce `--all-after-run` and `--all-after-time` or can we say that if it contains a colon, then it's a timestamp?

**Comment by gyorb** [comment]
Another thing would be nice if the -n argument where we define the run name we want to delete would accept some simple regex like parameter ```myrun*```, so all the runs where the name starts with myrun will be deleted.
