### ISSUE TITLE
enable commandline option forwarding to clang

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#469]
currently there is an option for this:
 --saargs CLANGSA_ARGS_CFG_FILE
                        File with arguments which will be forwardeddirectly to

extend the option to enable passing options directly:
 --saargs ClangSA options or CLANGSA_ARGS_CFG_FILE
                        Clang Static Analyzer options directly or  a File with arguments which will be forwardeddirectly to

**Comment by bruntib** [comment]
This issue is not relevant any more, so I close it.
