### ISSUE TITLE
quick check

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#48]
It should be possible to quickly check a small project (set of files) for bugs without storing the results into the postgres db.

The defect list should appear on the console without the bug paths, only showing the source location of the last step of the bugpath, checker name, bug message.

Only the build command should be the required command line parameter:

CodeChecker quickcheck -b "make"

**Comment by Xazax-hun** [comment]
Wouldn't it be better to have a separate command like quickcheck for that? To prevent accidental quickchecks when it is not intended.

**Comment by dkrupp** [comment]
Right. it would probably be safer to implement it like a  subcommand: CodeChecker quickcheck -b "make"
