### ISSUE TITLE
Add tests for plist import

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#485]
The plist import code is not covered by tests at all right now.

**Comment by whisperity** [comment]
At this point, in the subcommand restructuring run, command `plist` turned into a wrapper. `store` handles the "plist import" functionality. `store` is tested by the tests that use `check` (which wraps over `store`) to insert runs into the database, which is read later on.

**Comment by gyorb** [comment]
A separate `store` test might be needed, if we plan to remove or deprecate the `check` command.

**Comment by bruntib** [comment]
This issue seems to be out-of-date, since we don't have a plist importer. To be precise, `store` command covers this functionality and that is tested.
