### ISSUE TITLE
enable suppression without suppress file configured at viewer server start

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#488]
In a centralized environment (one central CodeChecker server) it is possible that not all of the users have access to the configured suppress file (at server start).
If suppression only in the database is enabled they can export the suppressed results (not in suppress file format).
We might need to create a command line tool to better support this.
- [x] enable suppression
- [x] command line tool to export suppress information from the database

Should be done together with Import suppress data #455

**Comment by bruntib** [comment]
Isn't "command line tool to export suppress information from the database" solved by simply exporting bug suppressions? Is there any difference?

**Comment by gyorb** [comment]
Right now if you start `CodeChecker server` without a suppress file you can not suppress on the UI, in that case there is no suppress information to export from the database.
Enabling this type of server start is independent from the suppress export/import feature.

**Comment by whisperity** [comment]
Implemented by #490.
