### ISSUE TITLE
Suppression improvements

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#490]
## Command line
- [x] `CodeChecker cmd suppress -o suppress_file -n $RUN_NAME -h $HOST -p $PORT`  export suppression information from $RUN _NAME to a suppress_file (if suppress file is already contains entries warn the user and merge them, do not overwrite the suppress messages if already available only if `--force` is used)
- [x] `CodeChecker cmd suppress -i suppress_file -h $HOST -n $RUN_NAME -p $PORT` import suppression information and apply to a $RUN _NAME
- [x] `CodeChecker cmd suppress --bugid $BUGID -m "suppress message" -o suppress_file -n $RUN_NAME -h $HOST -p $PORT` suppressed in the selected run and in the suppress file
  * `-h -p -n` argument should be used to suppress only in the selected run on the server
  * `-o` argument should be used to suppress only in the local suppress file
- [x] `CodeChecker cmd suppress -u --bugid $BUGID -o suppress_file -n $RUN_NAME -h HOST -p $PORT` unsuppress a bug in the selected run and in the selected suppress_file
  * `-h -p -n` argument should be used to unsuppress only in the selected run on the server
  * `-o` argument should be used to unsuppress only in the selected suppress file

- [x] command line should warn user if the same suppression information was already found in the database or in the suppress file (use `--force` to overwrite existing data) 

# GUI
- [x] The suppress button should show the suppression command which should be used to suppress a bug `CodeChecker cmd suppress --bugid $BUGID -m "suppress message" -o suppress_file -n $RUN_NAME -p $PORT`
- [x] If a suppressed bug view is active the required informations for unsuppression should be available for the user, with an unsuppress button `CodeChecker cmd  suppress -u --bugid $BUGID -o suppress_file -n $RUN_NAME -p $PORT`

Corresponding issues:
- [x] unsuppress bug #489
- [x] import suppress data #455
- [x] server start no suppress file #488

**Comment by bruntib** [comment]
Which one should be preferred? `CodeChecker suppress ...` or `CodeChecker cmd suppress ...`?

**Comment by whisperity** [comment]
Seeing that this commands are mostly tied to a run on a given CodeChecker server, I think this fits more to be under a `CodeChecker cmd suppress` subcommand.

**Comment by gyorb** [comment]
Yes we already discussed this with @bruntib that it will be under the `CodeChecker cmd` command.

**Comment by bruntib** [comment]
I suggest to slightly change the requested interface: at command line bug suppression the suppress file should be provided by `-u` like at server starting. Thus `-o`, `-i`, `--bugid` could be exclusive alternatives. To unsuppress a bug `-x` or something else could be used.

**Comment by bruntib** [comment]
I don't really understand the distinction between the suppressed bugs in the database and the suppress file which are handled separately according to the `--bugid` use case (3rd point). The `suppress` sub-command is under `cmd` which requires a running CodeChecker server via the host and port number. Isn't it up to the server whether the report should be suppressed only in the database or in the suppress file too? This client shouldn't even know about the suppress file which the server handles.

**Comment by bruntib** [comment]
#495 resolves this issue.
