### ISSUE TITLE
add Clang SA configuration file

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#5]
It should be possible to specify a config file to
CodeChecker check subcommand
where the checker specific configuration can be added.

Preferably in json format:
```
[  
   {  
      "checker_name":[  
         {  
            "parameter_name":"value"
         },
         {  
            "parameter_name":"value"
         }
      ]
   }
]
```

For example:
```
[  
   {  
      "NonPrivateDataChecker":[  
         {  
            "exclude_structs":"true"
         }
      ]
   }
]
```

**Comment by gyorb** [comment]
Instead of separate config files and new format, it is now possible to forward configuration options directly to the analyzers in the command line.
