### ISSUE TITLE
File paths shown badly in web view

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#502]
The file paths of the web view are garbled, the leading `/` is shown at the very end of the path.

![Attached image](https://cloud.githubusercontent.com/assets/1969470/22015045/bb43c364-dca0-11e6-88b9-2038a0883d19.png)

The output works fine in `CodeChecker cmd`

**Comment by bruntib** [comment]
The purpose of "right to left" was to align the long path to the right when not enough room for it on a small screen: we'd like to see `.../c/d/e` instead of `/a/b/c...` so the file name can be visible.

**Comment by bruntib** [comment]
As far as I have seen the special characters at the beginning of the string will jump to the end. We should maybe find something to prepend to prevent this behaviour?
