### ISSUE TITLE
traversing the bug path is really slow

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#516]
Especially with bug path with many arrows, clicking on a bug event hangs the browser for seconds.
also clicking into the source code "freezes" the browser for seconds.

this is very disturbing when analyzing bug paths.

tested on codechecer 5.7, chrome 55

**Comment by dkrupp** [comment]
example:http://md-mtas2.tsp.eth.ericsson.se:4999/#baseline=6&newcheck=5&report=440

**Comment by dkrupp** [comment]
another simple example, when scrolling is slow
http://md-mtas2.tsp.eth.ericsson.se:4999/#baseline=7&newcheck=8&report=1049

**Comment by whisperity** [comment]
Confirming, this bug also affects me. It doesn't get better on more powerful machines, and exists both on Firefox and Chrome browser.
