### ISSUE TITLE
bug overview the result count and the number of shown bugs differs

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#533]
For example in diff view of xerces 3.1.1 and 3.1.2 the number of high priority unsuppressed, unresolved bugs should be 30, but only 5 are shown in the list.

for easy reference see:
http://md-mtas2.tsp.eth.ericsson.se:9997/#baseline=1&newcheck=2

most likely this is a gui bug

**Comment by whisperity** [comment]
Wasn't this the bug that was sometimes solved by resizing the window? [Another example can be found here](http://cc.inf.elte.hu:8080/#baseline=108&newcheck=104) (search for the `unix.Malloc`) results.

**Comment by gyorb** [comment]
Is this bug still valid @csordasmarton ?

**Comment by csordasmarton** [comment]
I think it has been fixed by @bruntib.

**Comment by bruntib** [comment]
I think #917 was the one fixing this issue. If it reoccurs, we can reopen this issue.
