### ISSUE TITLE
clang-tidy results are no longer displayed on the view

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#534]
While the analysis is correctly done:
```

[12:45] - ----==== Summary ====----
[12:45] - Total compilation commands: 6264
[12:45] - Successfully analyzed
[12:45] -   clangsa: 2893
[12:45] -   clang-tidy: 3067
[12:45] - Failed to analyze
[12:45] -   clangsa: 174
[12:45] - Skipped compilation commands: 130
[12:45] - ----=================----
[12:45] - Analysis length: 8351.02141786 sec.
[12:45] - Analysis has finished.
```

The view doesn't show a single clang-tidy based results. Any recent change which might have caused that?

**Comment by whisperity** [comment]
Could it be that there are no bugs in `clang-tidy`'s report? What version of CodeChecker are you running?

On current master 59a658ec64d88c975b86fece87c967cd575225e7, I cannot reproduce this bug. Can you please run the analysis with `--keep-tmp` enabled and check the plist files at `[workspace]/[runname]_report/clang-tidy_[filename]_[something].plist`, if they actually contain anything? (An "empty" file is `268` bytes on my machine.)

**Comment by sylvestre** [comment]
> Could it be that there are no bugs in clang-tidy's report?
I wish :) When it was working, I had around 145 000 defects found by clang-tidy.

I am running master too.

I started a new build with --keep-tmp

**Comment by gyorb** [comment]
Which clang and clang-tidy versions do you use?

**Comment by sylvestre** [comment]
5.0 (snapshot from http://apt.llvm.org/)

**Comment by gyorb** [comment]
Could you try it with the 3.9 release? We support the latest official clang releases [(23 Dec 2016 v3.9.1)](http://releases.llvm.org/)
It is possible that something changed in clang-tidy and we did not update CodeChecker yet.

**Comment by Xazax-hun** [comment]
By default very few clang tidy checkers are enabled in CodeChecker. Is it possible that most of the checkers are actually disabled?

**Comment by gyorb** [comment]
By default we disable all #373 and only re-enable a [few](https://github.com/Ericsson/codechecker/blob/cd543a3bb59e76d7147045799db2b0df198c14aa/config/config.json#L34).

**Comment by sylvestre** [comment]
Switching to an older version of clang-tidy fixed my issue. Sorry for the noise
