### ISSUE TITLE
eliminate duplicate bugs from different files

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#539]
Different plist reports may contain the same bug report with the same hash id but on different paths.
The bug in these cases are reported in a .h file which is included by 2 independent .c files.
Frequently the two different bug is the result of the same problem and the ending steps of the 2 bug paths are the same.

Solution Proposal: Generate the bug hash of the uniquing location into the plist file and take this into consideration when improting.

**Comment by whisperity** [comment]
As a further solution, we could also build upon @zporky's idea in counting on how many different paths a bug is present, which could help in the visualisation of the bug's impact. (Either only storing the count or storing _Related bug paths_ too?)

**Comment by gyorb** [comment]
I do not think this is a bug, by design do we this see issue #69 and pull request #89. Using the extra information from clang would definitely improve the current solution.

**Comment by Xazax-hun** [comment]
I think the uniquing should be done based on uniquing location (as string) and check name. Not baes on hash.

**Comment by Xazax-hun** [comment]
With the new bug unique-ing under development, this is no longer relevant.
