### ISSUE TITLE
An error with thrift on MacOS

### ISSUE THREAD

**Issue by VonFry** [Ericsson/codechecker#546]
```
mkdir -p build
doxygen ./Doxyfile.in && \
	cp -a ./gen-docs /Users/vonfry/codechecker/build/gen-docs
/Users/vonfry/codechecker/docs/usage.md:2: warning: explicit link request to 'CodeChecker' could not be resolved
if [ ! -d "/Users/vonfry/codechecker/build/gen-py" ]; then rm -rf /Users/vonfry/codechecker/build/gen-py; fi
if [ ! -d "/Users/vonfry/codechecker/build/gen-js" ]; then rm -rf /Users/vonfry/codechecker/build/gen-js; fi
thrift -r -o /Users/vonfry/codechecker/build -I thrift_api/ --gen py thrift_api/report_storage_server.thrift
thrift -r -o /Users/vonfry/codechecker/build -I thrift_api/ --gen py --gen js:query thrift_api/report_viewer_server.thrift
[FAILURE:generation:1] Error: unknown option js:query
```
If I remove `:query`, then the command like `thrift -r -o /Users/vonfry/codechecker/build -I thrift_api/ --gen py --gen js thrift_api/report_viewer_server.thrift` can be run and all other thing can be run correctly.

**Comment by gyorb** [comment]
Which thrift compiler version do you use?

**Comment by VonFry** [comment]
@gyorb I installed with `homebrew`.

```
Thrift version 0.10.0
```

**Comment by gyorb** [comment]
Could you check it with `--gen js:jquery`

**Comment by VonFry** [comment]
Uh...I'm so sorry that I don't know how to check it.

If about the error log, I've post in the issue.

I tried make a new thrift file, and run `thrift --gen js:query test.thrift`. It has a log `[FAILURE:generation:1] Error: unknown option js:query`.

**Comment by gyorb** [comment]
I've created a pull request to fix that issue, but I think there will be another problem with the newer thrift compiler, we still download the 0.9.2 python modules in the virtualenv.
You can fix that by switching to an older thrift compiler `brew install homebrew/versions/thrift090`

In MacOS the thrift compiler is already updated to the latest 0.10 but there is no package for Ubuntu distribution yet.

I will update the install requirements for MacOS.

**Comment by gyorb** [comment]
Did you manage to install and create a package with the modifications?

**Comment by tmsblgh** [comment]
I tried to build and use CodeChecker on Mac OS High Sierra (10.13 Beta) and it's worked. 

I only changed the thrift version from 0.9.1(or 2) to 0.10.0.

It was needed because I got an error with that version:
"from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException ImportError: cannot import name TFrozenDict"

But now it's working fine, I think.
