### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by mschmart** [Ericsson/codechecker#562]
Any idea how can we make this run on Windows?

**Comment by whisperity** [comment]
See #555 for the discussion. As of now, Windows is not supported, though most likely it will be in the future. `clang` definitely exists on Windows, so does Python, so basically, it should work.

**Comment by rasjani** [comment]
Been toying around with at least to get the web ui working and at least following approach is looks ok:

1. cmake project, can export compile_commands.json 
2. I have personal project that can run various static analyzers that i wrote that can produce proper clang-tidy run and log it..
3. use report-converter to produce reports that can be "stored" into codechecker server .. 

I wasnt initially able to get main CodeChecker to run on windows so i did a quick workaround - 

after doing a full scan wit clangtidy and converting the  log to report-converter, i transfered the reports to another box (mac), changed the full paths under <files> in the plist to match local  paths on the new box and then i could upload the report to webui .. 

There where few wtf moments  on the windows side .. 

I made a venv (as i dont want to polute CI python modules) - activated and installed what i thought would be necessary inside  that venv. But things where still failing. When code was running, at least portalocker was not found even thought it definitely was installed in the venv .. I checked the sys.path in codechecker_common/util.py and by the looks, when execution gets that far, venv is *completely* by passed..

**Comment by whisperity** [comment]
@rasjani Thanks for trying and looking into the issue! **Could you please post your findings to the ticket #555** opened by `@gyorb`, too? (It's good enough if you just copy-paste what you wrote above!) So we can have all the talk regarding execution on Windows in one place. I'll close this ticket now in favour of the other one (it has some more comments from last year!).
