### ISSUE TITLE
Store system statistics

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#565]
It could be useful if, for an analysis, we stored which version of clang and clang-tidy was used for analysis and various other metadata (discuss?).

Also if we are already modifying the database and interface to accompany the storage of this metadata, showing the "version" of CodeChecker on the web interface and in the help command would also be nice.

**Comment by gyorb** [comment]
There is already a `CodeChecker version` command which prints out the package version in the command line.

**Comment by whisperity** [comment]
Awesome. Though it doesn't query the underlying clang's version information, which I think should be good if shown **and stored** for an analysis. It is put in the log:

> [10:09] - Using analyzer:
> clang
> clang version 5.0.0 (github.com:llvm-mirror/clang 40b4742cc4497f150a9bf3abb06d1bb15afb3e56) (github.com:llvm-mirror/llvm 5b7ece9f05ed866e92707f89a7d4c89db3fab19b)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /home/ericsza/CodeChecker/build/bin
> [10:09] - Using analyzer:
> clang-tidy
> LLVM (http://llvm.org/):
>   LLVM version 5.0.0svn
>   Optimized build.
>   Default target: x86_64-unknown-linux-gnu
>   Host CPU: haswell

but a log is not enough, especially if we attempt to look back to an older analysis from maybe days or weeks ago. (_Did this bug disappear because the checker which gave the warning on was changed?_)

(This is actually a question/issue I received mainly from a friend of mine whom I introduced to CodeChecker.)
