### ISSUE TITLE
Messed up 'Report details' view on GUI

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#566]
![image](https://cloud.githubusercontent.com/assets/1969470/22878355/cc9f0fbc-f1d9-11e6-8a2c-326d06c068d7.png)

The shown "window" is insistent in clamping to the right side and the failure message loses every formatting, essentially rendering this view useless.

**Comment by whisperity** [comment]
:man_facepalming: This issue was accidentally referenced by #567, and is **completely** unrelated to it. Please reopen.

**Comment by gyorb** [comment]
Is this still valid for the new UI @csordasmarton? I do not see the mentioned report details view.

**Comment by csordasmarton** [comment]
No, it isn't.
