### ISSUE TITLE
Code annotation not drawn when jumping to different bug

### ISSUE THREAD

**Issue by whisperity** [Ericsson/codechecker#582]
At first hunch, I'd say broken by #549, when we jump into a different bug when the source file contains more than one bug, no annotation (arrows and inline boxes) are drawn.

**Comment by whisperity** [comment]
I can't test this at the moment, but there were a lot of redesigns to the code since February.

@csordasmarton @gyorb Is this still an issue or did we fix it somewhere down the road?

**Comment by csordasmarton** [comment]
I think this issue has been fixed.

Check this part of code:
https://github.com/Ericsson/codechecker/blob/31d9f1a299edfa3472b9d4ca85caab60075fbb2e/www/scripts/codecheckerviewer/BugViewer.js#L214-L240

First we clear the inline boxes (`clearBubbles`) and arrows (`clearLines`) and redraw the new boxes (`addBubbles`) and arrows (`addLines`).

**Comment by whisperity** [comment]
I've ran some tests on an extensive amount of databases and can't seem to trigger this issue.
