### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#585]
If the user finds some error or have questions about CodeChecker usage, it should be easy to report a bug or ask a question.
We can generate a basic issue description which contains CodeChecker version, browser version, host OS to help resolving the issues.

- [x] add new `report bug` link to the webUI.
- [ ] maybe command line support for this like `CodeChecker bug`?

**Comment by whisperity** [comment]
GitHub supports adding an [issue template](https://github.com/blog/2111-issue-and-pull-request-templates) to the project, if needed.

**Comment by gyorb** [comment]
I was thinking to generate a basic issue description at the webUI which the user can copy/paste into the GitHub issue.
The link might not forward the user to GitHub by default just shows the link and the details which should be provided when a new issue is created.

We might create some minimal issue template but I'm still thinking if we should do this as a GitHub template.

**Comment by bruntib** [comment]
In the top-right corner we already have a drop-down menu. We should add a new item "Report a bug" which navigates directly to the "new issue" page of GitHub. This way the user directly sees the input fields: https://github.com/Ericsson/codechecker/issues/new.
