### ISSUE TITLE
Drop support for guessing check name

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#607]
For clang version older than 3.7 codechecker tries to guess the check name based on error message. I think we should not support old clang versions indefinitely. So the code for this workaround should be deleted in the next major release.

**Comment by whisperity** [comment]
Should the next major release also deprecate the "Hash value wasn't found in plist" error too? If we are already doing #578, CodeChecker could fail in its invocation when the detected clang version is too old.

**Comment by Xazax-hun** [comment]
Since the hash is not generated for clang tidy, our custom hash generation codepath is still required. So it won't be a big cleanup. I am not sure what is the oldest clang version that we would like to support, but since the latest ubuntu LTS is shipping clang 3.8 I am all in favor for removing that message as well.

**Comment by whisperity** [comment]
@gyorb Should I do this as part of #745's pull request, #856?

**Comment by gyorb** [comment]
@whisperity I think this is not that important right now. We can drop support later in one of the 6 releases.
