### ISSUE TITLE
Use report hash and run name in permalinks

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#620]
Introduce bug hash additionally to report_id and use run_name instead of run_id in permalinksas these identifiers remain resilient to data migration (because report id and run id is generated at DB insertion).
If after a db migration report_id becomes invalid, reaload the bug view based on bughash.

The following URL formats will be supported:

* `http://localhost:8888/Xerces/#report=822&run=Xerces&reporthash=#123456` will show report 822 if it has hash #123456, if not (the report is stored later with a different id) it will show a random bug with hash #123456

- [x] use report hash besides report id in all permalinks
- [x] use run name instead of the current run id in permalinks
- [x]  In the bug viewer show a list of instances of the bugs with the same bug hash but different containing runs and files. The list should be a drop down such as.

The same bug occurs:
run1:file1:line_1
run2:file2:line2
run3:file3:line3

When such an item is selected, bug viewer should show the bug from that context.

**Comment by Xazax-hun** [comment]
Note that for reports we might also need the bug path hash in order to be unique.
