### ISSUE TITLE
suppress file format converter

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#622]
Suppress file converter should be created to convert the old (before v6.0) suppress file format to the new.
The current format: `bug hash || filename || comment`
* just plain text
* bug hash
* filename
* suppress comment

The new format:
* should be easy to extend/modify later (json, yaml ...)
* bug hash
* bug path hash (needs to be generated from the database, or plist files)
* filename (optional, bug path hash should give better identification)
* suppress comment (utf8)

```
{
  "suppressed_bugs": [{
    "bug_hash": "bughash",
    "bug_path_hash": "bug path hash",
    "filename": "main.cpp",
    "comment": "comment"
  }]
}
```

**Comment by dkrupp** [comment]
no new suppress file format was created for v6.0
