### ISSUE TITLE
An error during Sorting analysis results 

### ISSUE THREAD

**Issue by liardety** [Ericsson/codechecker#670]
Hello, 

As I had many false positives from clang analyzer due to an custom assertion handler, I tried to add `__attribute__((analyzer_noreturn))` at the end of its declaration. But then this error has shown up : 

`[ERROR] [14:51] - RequestFailed(_message="'NoneType' object has no attribute 'start_bugevent'", error_code=2)`

**Comment by gyorb** [comment]
Hi,

Which CodeChecker version do you use?

**Comment by liardety** [comment]
I made a clone of this commit : 69837a5aa6f0a5df77a95c398468ac469e90c019 (SHA1 ID)

(Basicly I followed the instructions on the README.md)

**Comment by gyorb** [comment]
If you remove the extra attribute you added the analysis and storing the results is successful?
In the analysis command did you use the same name `CodeChecker check -b make -n myproject`?
Do you still get the error if you use a different name for the analysis?

**Comment by gyorb** [comment]
We found some issues on the current master branch which is under investigation. It might be connected to your problem. Could you try a previous more stable release [v5.7.1](https://github.com/Ericsson/codechecker/releases/tag/v5.7.1)?

**Comment by gyorb** [comment]
We made some updates on the master branch which might fix your storage problem, could you check it if you still get the error?

**Comment by liardety** [comment]
Hello, 

The issue seems to be fixed with the recent updates (I don't get the error), thanks a lot. Yet, I still have many false positives around my custom assertion handler. I may be doing something not quite right.

**Comment by whisperity** [comment]
CodeChecker reads the Clang-generated `plist` files and parses them to create the reports that are stored in the database. To ensure no error happens from CodeChecker's end (hopefully this won't be broken again), you shouldn't take away keys from the generated plist XML, as CodeChecker depends on the `plist` being in a valid format.

The false positives from the custom assertion handler is a separate issue. Does using this custom handler involve passing different arguments to Clang SA? Is this in **your** code, or in the Clang Static Analyzer?

For extra arguments, you can create a text file and pass args via `--saargs <txt file path>`.

CodeChecker behaves as a front-end, assembling a proper `clang` invocation. (Use `--verbose debug` to see the exact analyzer invocation that is being fired for your source files.)

The analysis is done by Clang, and after it returns, we only take its output as it is, and work from it. The LLVM community's mailing lists might be a better place to ask about particular, analyzer-internal questions.

**Comment by csordasmarton** [comment]
I think this issue has been solved. Please feel free to reopen it if you still experience this problem.
