### ISSUE TITLE
Security: Storage of issues should be authenticated [90h]

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#683]
In CodeChecker 5.8 users to the viewer can be authenticated, however issue storage cannot be authenticated, because the storage uses direct database connection.
CodeChecker check -n myProject -b "make -j 4" --dbname myProjectdb --dbaddress localhost --dbport 5432
Instead of db location, the users will need to define a CodeChecker server and user name [-u USERNAME] [--host HOST] [-p PORT]. Authentication and authorization then will be performed based on LDAP user name / password.

Implementation
- [x]  Move storage server API implementation into the viewer server (20h) (assuming single thread impl)
- [x]  Remove db start from check command, store command (8h)
- [x]  Remove storage session managment (Client.py) (8h)
- [x]  Rewrite store client to use HTTP, remove db arguments cmd line, add arguments for codechecker server access, login (16h)
- [ ]  remove check command (4h)
- [x]  add/update test cases (32h)
-------
 90h

**Comment by gyorb** [comment]
`check` command is kept for now (might be removed later) but the database arguments are deprecated.
User login is handled as before with the `CodeChecker cmd login` command so no username needs to be provided for the `store` and `check` commands.
