### ISSUE TITLE
Commenting of  issues [28h]

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#685]
It will be possible to add any number of comment for an issue. Author of the comment will also be saved. The comments will be active across all runs.

Implementation
- [x] Add accordion panel to bug code view in GUI, list comments in time order, show author and date and text of comment, add text box and add button (8h)
- [x] Add API call to be able to add/query comment (based bughash:pathhash) (8h)
- [x] create new history table (author, date, text, bug hash)  (4h)
- [x] add tc (8h)
-----
28h

**Comment by csordasmarton** [comment]
I made a "wireframe" for this feature.The main idea is to show comments at the right side of the code view which can be hidden by the **Comment button**. What do you think about it? 

![codechecker_comments](https://user-images.githubusercontent.com/6695818/28110276-263aa382-66f2-11e7-9179-e45176356cc0.png)

**Comment by whisperity** [comment]
@csordasmarton Shame this is not a pull request, I can't green-tick it. Looks very fun and good to me.

A small question: I would move the `Comment` button to the right, anchored to the right end of the code view. So it's like... on GitLab: 

![image](https://user-images.githubusercontent.com/1969470/28111103-aad65cc4-66f4-11e7-98a0-205980181cac.png)

And when opened:

![image](https://user-images.githubusercontent.com/1969470/28111206-066438f4-66f5-11e7-91d4-a48b1eb91315.png)


And maybe the comment view should show the number of comments on the issue. But of course this latter part is just a minor change on the wireframe mock.

**Comment by dkrupp** [comment]
looks good. Name textfield is not needed. It will be the logged in user.

**Comment by gyorb** [comment]
Looks good to me too, just one note:
on the left there is an unused space (under the issues) which could be used for these comments and in that case it will not take space from the source code on the right

What do you think ?

**Comment by whisperity** [comment]
> under the issues

In case there are a lot of bugs (or very long bugpaths) in a file, that window can be densely populated.
Maybe we could introduce a horizontal separation and put the comments under it, but for me, a toggleable comment view seems more user friendly. (I.e. consider presenting the bug for your team or being deeply in the "I am reading source code" mode. Do you _always_ care about comments in this case?)

**Comment by csordasmarton** [comment]
I made a screenshot from this feature:
- We can show/hide comment sidebar with the `Comment` button
- We show the `number of comments` at the Comment button
- All comments are commented `anonymously`
- We can `edit/remove` comment

![cc_comments](https://user-images.githubusercontent.com/6695818/28372754-cf406120-6ca0-11e7-881a-23002461729f.png)

What do you think?

**Comment by whisperity** [comment]
@csordasmarton Looks very good, thank you. :+1: How about my suggestion of moving the `Comments (n)` button to the *right* end of that "button bar"?

**Comment by csordasmarton** [comment]
I don't know which would be better. Here is a screenshot how it would look like if the button were in the right end of the button bar.

![cc_comment_btn_right](https://user-images.githubusercontent.com/6695818/28408461-cd442450-6d37-11e7-81ce-81f519fba275.png)
