### ISSUE TITLE
Complex issue filtering by run names, checkername, severity, checker message, file filter, review status [128h]

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#687]
Extend 5.8 filtering functionality to filter by run names, checkername, severity, checker message, file filter, review status(depends on Review status of issues feature), detection status. Filters will also update permalinks, thus filters can be stored as for example links in wiki pages.

- [x]  update Report list GUI: create a left panel with
run name: regular expressions, text box with drop down-multi select
checker name: use the current getRunResultTypes() call. two-state list (this includes severity)
checker message: regex textbox
file filter: regex multi text box
review stats: two state list of status fields (40h)

- [x]  create permalink for selection (40h)  #775 
- [x]  add run id list to filters (16h)
- [x]  add test cases (16h)
- [x]  performance test (16h)

- [x] fix command-line to use new filtering  #918
----
128h

depends on #688

**Comment by csordasmarton** [comment]
I made a "wireframe" for this feature.
![cc_filters](https://user-images.githubusercontent.com/6695818/28968046-5e9d8d00-791e-11e7-8a19-47ff91759ecb.png)

**Comment by gyorb** [comment]
Looks good to me. We could remove the suppress column. I think those comments will go to the review status and showed with the bug comments together. Am I right?

**Comment by csordasmarton** [comment]
Yes, you are right. I removed the suppress column in the #768 pull request.

**Comment by gyorb** [comment]
First pull request to show the filter values on the url is available #775

**Comment by gyorb** [comment]
The UI and command line should use the new counter API-s introduced in #810 and we should deprecate `getRunResultTypes()` later.
