### ISSUE TITLE
Detection status (new,resolved, unresolved,reopened) to issues. This feature is also known as the stream functionality [80h]

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#688]
new: bug was not present in the previous analysis (did not exist ever in the run)
unresolved: bug was present in the previous analysis
resolved: bug not present in the current analysis, but it was present before
reopened: bug is present in the current analysis and it was resolved before

(outstanding is the sum of new, unresolved and reopened. this is a very frequently used category)

Store command should store content of the plist files into the run. only the most recent file versions should be stored.
- [x]  add detection status column to reports table & update run list view with the number of bugs in each run with state: new,resolved, unresolved,reopened) (4h)
- [x]  remove build action table, and clear from API and rewrite update mode: do not remove old reports (only change it's status), remove stored file contents, add new files (16h)
don't worry about file content hashing
- [x]  rewrite bug path storage (16h)
- [x]  new analysis mode is needed which does not remove all plist files at analysis so incremental analysis can be supported. (This will be done in #702) (4h)
- [x]  update test cases (16h)
- [ ]  store update event in history table (#685 introduces this table) (4h)
- [ ] report uniqueing should be done before storing the reports (20)
-----
80h

+Additional improvement idea: keep old analysis instances so that the user can revert to an old run if something goes wrong with the storage

**Comment by whisperity** [comment]
Follow-up issues discussed in #821.
