### ISSUE TITLE
Add an email notification when new issues are found

### ISSUE THREAD

**Issue by sylvestre** [Ericsson/codechecker#70]
it would be great to receive an email when new issues are found by the tool

**Comment by gyorb** [comment]
Couldn't be this feature achieved with a continous integration tool like jenkins?
For example a jenkins job runs the checking and after it gets the new results sends an email.

**Comment by dkrupp** [comment]
A jenkins/CI  script could check the results of the new run and send an email if needed.

**Comment by sylvestre** [comment]
it could but it would be nice to have this feature into code checker as, to me, this is one of the key goal of this kind of project
