### ISSUE TITLE
source file name with whitespaces are not handled corectly by the analyze subcommand

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#759]
[ERROR] [16:55] - Analyzing lib 2.cpp with clangsa failed.
[ERROR] [16:55] - clang-5.0: error: no such file or directory: '2.cpp_9bffe300.plist'
clang-5.0: error: no such file or directory: '/home/gerazo/repos/codechecker_dev_env/samsungXTU/example/lib'
clang-5.0: error: no such file or directory: '2.cpp'
clang-5.0: error: no input files

**Comment by whisperity** [comment]
I have created a test file named `a b.cpp` and tried every escaping combination possible. Summarising in the table below. In parantheses, the build command passed to `CodeChecker log`.

<table>
<tr>
  <th>logger tool</th>
  <th>escaped file path (<tt>"g++ a\ b.cpp"</tt>)</th>
  <th>single-quote (<tt>"g++ 'a b.cpp'"</tt>)</th>
  <th>double-quote with proper escaping (<tt>"g++ \"a b.cpp\""</tt>)</th>
</tr>
<tr>
  <th><tt>ld-logger</tt></th>
  <td colspan="3"><tt>file</tt> and the end of <tt>command</tt> is <tt>a b.cpp</tt> <b>(1)</b></td>
</tr>
<tr>
  <th><i>(old)</i> <tt>intercept-build</tt> in <tt>clang-5.0</tt></th>
  <td colspan="2"><tt>command</tt> contains the file as <tt>\"a b.cpp\"</tt>, whereas <tt>file</tt> is <tt>a b.cpp</tt> <b>(2)</b></td>
  <td rowspan="2"><b>not possible</b> to call (crashes) &mdash; even if manually invoked, and not through CodeChecker <b>(3)</b></td>
</tr>
<tr>
  <th><i>(new)</i> <tt>intercept-build</tt> from GitHub</th>
  <td colspan="2"><tt>arguments</tt> contains the file as <tt>a b.cpp</tt> in a single vector element, <tt>file</tt> is the same <b>(4)</b></td>
</tr>
</table>

---

The build jsons, verbatim:

# 1.

```
[
        {
                "directory": "/home/whisperity/CodeChecker/codechecker/tmp",
                "command": "g++ -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include /home/whisperity/CodeChecker/codechecker/tmp/a b.cpp",
                "file": "/home/whisperity/CodeChecker/codechecker/tmp/a b.cpp"
        }
]
```

# 2.

```
[
    {
        "command": "c++ -c \"a b.cpp\"", 
        "directory": "/home/whisperity/CodeChecker/codechecker/tmp", 
        "file": "/home/whisperity/CodeChecker/codechecker/tmp/a b.cpp"
    }
]
```

# 3.

`intercept-build` unescapes the double quotes (turns the build command `g++ \"a b.cpp\"` into `g++ a b.cpp`), and g++ throws the error

```
g++: error: a: No such file or directory
g++: fatal error: no input files
compilation terminated.
```

# 4.

```
[
    {
        "arguments": [
            "c++", 
            "-c", 
            "a b.cpp"
        ], 
        "directory": "/home/whisperity/CodeChecker/codechecker/tmp", 
        "file": "a b.cpp"
    }
]
```
