### ISSUE TITLE
file cleanup job

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#785]
filecontent records that are unused by any file are not cleaned and remained orphaned in the database.
Create a cleanup job that runs at server stop to clean up orphaned filecontents.

**Comment by bruntib** [comment]
We should consider removing these files at server start. At the first sight it doesn't seem to be a fast process: we have to find the files which are not members of any bug pat or bug event. One may not understand why it is needed to wait so much for stopping the server so he or she kills it more aggressively interrupting the cleaning process. If garbage collection happens at server start, we force the user to wait for it. Or we can even introduce a flag which prevents garbage collection if the server has to be started quickly.
