### ISSUE TITLE
Detection status known issues

### ISSUE THREAD

**Issue by bruntib** [Ericsson/codechecker#821]
- [x] :exclamation: `store`ing to a server outside local machine **DOES NOT WORK**. :exclamation: #830
  - The ZIP is assembled in a way that the `plist` files and the `metadata.json` still contains the **local** path, such as `/home/username/project/main.cpp`, which does **NOT** exist on the remote server, as files are unpacked to some temporary directory.

```
[12:56:29] [29586] <140389142992640> - plist_parser.py:132 parse_plist() - Parsing plist: /tmp/tmp7LlvMP/reports/main.cpp_ea274a983107bcd3ad4c1f6c69a3656a.plist
[12:56:29] [29586] <140389142992640> - report.py:90 generate_report_hash() - Failed to generate report hash.
[12:56:29] [29586] <140389142992640> - report.py:91 generate_report_hash() - /home/username/project/main.cpp does not exists!
```

```
  File "/home/somebody/dstest/CodeChecker/lib/python2.7/libcodechecker/server/client_db_access_handler.py", line 1503, in massStoreRun
    file_ids[file_name] = file_path_to_id[file_name]
KeyError: '/home/username/project/main.cpp'
```

- [x] `store` prints `Success` to the user even if storing failed. #828
- [x] The suppressions in the file content are currently not stored.
- [x] `CodeChecker store` command needs to be given a report directory which is created by `CodeChecker analyze` command, i.e. the format of its content is important: it should contain the `plist` files and the `metadata.json`. `CodeChecker store` should work if the provided report directory contains only `plist` files. Moreover this command should also work with only one or more `plist` files given.
- [x] Storage crashes if a `plist` file contains a source file path which is not stored in the database and not sent in the `.zip` file.
- [x] A test case should check whether a `reopened` or `unresolved` bug is shown with the latest version of the given source code.

**Comment by gyorb** [comment]
Can we close this? Everything is fixed? @bruntib @dkrupp

**Comment by whisperity** [comment]
#859 is still pending as a PR.

**Comment by gyorb** [comment]
We can close this now. #859 was merged.
