### ISSUE TITLE
Checkers Summary View

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#826]
CodeChecker will provide a summary statistics of reports found by checkers summarized for all runs.

 The new table will be added as a default non closable "Cecker Statistics" tab. 

The new table will have the following columns
Checker Name | Nof Reports| Nof Unreviewed| Nof Confirmed bug| Nof FP | Nof WontFIx |Nof Resolved
The table will be  possible to sort by any column.

**Implementation**
* Filter API could be reused
* New tab  and table in ththe GUI  [16h]

**Comment by whisperity** [comment]
@dkrupp I think the command-line option `CodeChecker cmd sum` should also be extended with this functionality.

**Comment by Xazax-hun** [comment]
@whisperity,  since this is closed now could you open a separate issue for your idea?

**Comment by whisperity** [comment]
#870 aligned `cmd sum` to have the same layout. My idea has been fulfilled.
