### ISSUE TITLE
storage prints success even if storage fails

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#828]
CodeChecker store xerces-test-remote -p 4999 -n xerces
[22:19] - Storing analysis results for run 'xerces'
[WARNING] [22:19] - No JSON object could be decoded
[WARNING] [22:19] - Not valid user authentication file: /home/ednikru/.codechecker.passwords.json
Connection failed to localhost:4999
Check if your CodeChecker server is running.
[22:19] - Storage finished successfully.

**Comment by bruntib** [comment]
Cannot reproduce this issue.
