### ISSUE TITLE
Add codechecker hash to clang sa findings too

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#832]
Clang hash for a report can change with the clang version, which causes the bug to be double found. 
In the future always use codechecker generated hash for bug uniqueing which is more stable.

**Comment by Xazax-hun** [comment]
I am not sure that we can create a stable hash, since the hash algorithm did not change. The inputs of the hash algorithm such as the name of the checker, the error message, where the error is placed can also change across versions.

**Comment by gyorb** [comment]
Multiple hash versions are available now and the user can configure it in the command line to use a context free hash if the builtin hash method is not right because of namespace or function name change during builds ...
