### ISSUE TITLE
diff does not take detection status into consideration

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#837]
Detection status feature introduced a failure in run diff view

When calling diff view in the GUI, reports with detection status == "resolved" should be considered non existent in a given run.
For example
Run_A : BUG1 (Detection status new)
Run_B : BUG1 (Detection status resolved)

Diff A, B should show:
number of new bugs: 0
number of resolved bugs: 1

however now the CodeChecker shows by fault: number of resolved bugs 0

**Comment by bruntib** [comment]
Already fixed.
