### ISSUE TITLE
RunData cleanup

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#841]
`RunData` api type should be cleaned up.
 - [ ]  `5: i64            resultCount,` can be removed if the new report counting api is available in #839
 - [ ]  `7: optional bool  can_delete` can be removed when report removal will be cleaned up

**Comment by csordasmarton** [comment]
I think this problem has already been solved.
https://github.com/Ericsson/codechecker/blob/1af4908d085c98375ef5ef7da0cdb640623f6567/web/api/v6/report_server.thrift#L149-L160

We removed the `can_delete` attribute but we kept the `resultCount` to show the number of unresolved reports in the Run List page.
