### ISSUE TITLE
review and update default enabled checkers, priorities coming with clang 5

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/codechecker#877]
Review also the supposed priorities based on the potential checker improvements since last check-up.

Use `codechecker-checkers --details` to list every checker with their severity.

**Comment by Xazax-hun** [comment]
We were thinking about adding preset "profiles".

We could have a JSON file to describe such profiles such as:
default, strict, style etc.

Each profile could have a separate set of checks that are enabled.

**Comment by Xazax-hun** [comment]
Fixed by   #910.
