### ISSUE TITLE
Confusing names in diff

### ISSUE THREAD

**Issue by Xazax-hun** [Ericsson/codechecker#903]
In diff view it is confusing to say new, resolved, unresolved, since these are also the categories of detection status.

We should use instead:
Only in A,
Only in B,
Both in A and B

**Comment by whisperity** [comment]
I've been saying this for weeks.

**Comment by whisperity** [comment]
Be careful, current command line, Web gui and API terminology relies on the current diff "directions".

**Comment by gyorb** [comment]
Because both the baseline and the new can be a set of runs it can be:
* only in A,B,C ... (baseline)
* only in D,E,F ... (new)
* in multiple runs A,B,C,D,E,F

**Comment by Xazax-hun** [comment]
Do we want to support this? Right now we can only diff two runs in the GUI and I don't think the user want to diff multiple runs at once.

**Comment by dkrupp** [comment]
We can call collectively A the baseline that is the collection of runs 1,2,3 and B the collection of runs 4,5,6.
Then we can stay with the fixed text label: only in A, only i B, both in A and B
