### ISSUE TITLE
Product listing error in Firefox

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/codechecker#912]
I'm getting the following error message in Firefox (55.0.2 (64-bit)) when I'm trying to open the products listing page (http://localhost:8001/products.html):
![cc_products](https://user-images.githubusercontent.com/6695818/30383601-5f66e242-98a2-11e7-9b5a-3a92b5174bf4.png)

**Comment by whisperity** [comment]
Can confirm the issue, it sometimes appeared to me in Firefox too. I have no idea what causes it.

**Comment by whisperity** [comment]
*Sometimes*, it appeared. Right now I'm testing multiple nasty configuration of product settings and I can't get this error to pop up.

**Comment by csordasmarton** [comment]
I tried to debug this problem. If I'm using a non async call here, it works good:
https://github.com/Ericsson/codechecker/blob/82b45a4de4db1285d5b26939d4120fddee664171/www/scripts/productlist/ListOfProducts.js#L254-L264
