### ISSUE TITLE
Clickable checker names and severity levels on statistics view

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#945]
It would be a nice extension to the statistics view if the user clicks on a :
- [ ] checker name a filter view would be shown where the checker name is selected and the result list is filtered
- [ ] severity level a filter view would be shown where the severity level is selected

Filtering should use the selected runs at the statistics view.

**Comment by csordasmarton** [comment]
We already have an issue for this: #905.

**Comment by gyorb** [comment]
Thanks!
I will extend that with the clickable severity option.
