### ISSUE TITLE
Allow setting the header fliter for clang-tidy

### ISSUE THREAD

**Issue by BumblingCoder** [Ericsson/codechecker#972]
Currently it doesn't appear to be easily possible to set the header filter for clang-tidy. This is problematic for some checkers for which the problems most often occur in header files.

**Comment by gyorb** [comment]
You can forward compiler options directly to the analyzers.
Just create a tidy-arguments file with the header filters in it and forward it to clang tidy with the [--tidyargs](https://github.com/Ericsson/codechecker/blob/master/docs/user_guide.md#clang-tidy) argument.

If you want to skip results you can use a [skip file](https://github.com/Ericsson/codechecker/blob/master/docs/user_guide.md#skip-file) too.

**Comment by gyorb** [comment]
@BumblingCoder did you manage to use the header filter for clang-tidy or the skip file?

**Comment by csordasmarton** [comment]
Now you can list the analyzer configuration by using the following command: `CodeChecker analyzers --analyzer-config clang-tidy`. The output will be similar to this:
```sh
 clang-tidy:Checks
 clang-tidy:WarningsAsErrors
 clang-tidy:HeaderFilterRegex
 clang-tidy:AnalyzeTemporaryDtors
 clang-tidy:FormatStyle
 clang-tidy:User
```

And these options can be given to `CodeChecker analyze` command with the `--analyzer-config` option.
