### ISSUE TITLE
Recheck locally running postgresql tests

### ISSUE THREAD

**Issue by gyorb** [Ericsson/codechecker#984]
Some workspace directory and database cleanups are not done properly and the second round of PostgreSQL tests fail to run (pg8000).

With this fix p8000 tests should be re-enabled because they were turned off in #941.

**Comment by whisperity** [comment]
There has to be some misunderstanding here, or in #941. On Travis, there is no such thing as **second** run of PostgreSQL tests. On Travis, 6 instances ran before #941, as per the matrix, and the `psycopg` and the `pg8000` tests ran in entirely separate instances.

**Comment by gyorb** [comment]
Yes, there is no second run in Travis only if I run the PostgreSQL tests locally.
